# Generated by Django 4.0.1 on 2023-07-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoalimentacao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='descricao',
            field=models.TextField(default='Opcional combinado com o cliente'),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamentoalimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamentomonitor',
            name='descricao_monitoria',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orcamentomonitor',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamentoopicional',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
