# Generated by Django 4.0.1 on 2023-07-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0117_eventoscancelados_produto_corporativo_contratado'),
        ('orcamento', '0002_orcamentoalimentacao_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.BooleanField(default=False, verbose_name='Transporte')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Desconto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_recusa', models.CharField(max_length=255, verbose_name='Motivo da recusa')),
                ('promocional', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('necessita_aprovacao_gerencia', models.BooleanField(default=False, verbose_name='Necessita de aprovação da gerência')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio', verbose_name='Cliente')),
                ('opcionais', models.ManyToManyField(blank=True, to='orcamento.OrcamentoOpicional', verbose_name='Opcionais')),
                ('periodo_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentoperiodo', verbose_name='Período da viagem')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.responsavel', verbose_name='Responsável')),
                ('tipo_monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentomonitor', verbose_name='Tipo de monitoria')),
            ],
        ),
    ]
