# Generated by Django 4.0.1 on 2023-07-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='n_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de dias'),
        ),
    ]
