# Generated by Django 4.0.1 on 2023-07-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_orcamento_n_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosPadroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(max_length=50, verbose_name='Refeição')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
        ),
    ]
