# Generated by Django 4.0.1 on 2023-07-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_horariospadroes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='hora_check_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horario_entrada', to='orcamento.horariospadroes', verbose_name='Hora do check in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='hora_check_out',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='horario_saida', to='orcamento.horariospadroes', verbose_name='Hora do check out'),
            preserve_default=False,
        ),
    ]
