# Generated by Django 4.0.1 on 2023-07-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0153_fichadeevento_data_divulgacao'),
        ('orcamento', '0006_orcamento_hora_check_in_orcamento_hora_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(choices=[('micro', 'Micro ônibus'), ('onibus_46', 'Ônibus 46 lugares'), ('onibus_50', 'Ônibus 50 lugares')], max_length=9, verbose_name='Tipo de transporte')),
                ('valor_1_dia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de 1 dia')),
                ('valor_2_dia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de 2 dias')),
                ('valor_3_dia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de 3 dias')),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Acréscimo')),
                ('viacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.empresaonibus', verbose_name='Viação')),
            ],
        ),
    ]
