# Generated by Django 4.0.1 on 2023-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_valorestransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='transporte',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=3, verbose_name='Transporte'),
        ),
    ]
