# Generated by Django 4.0.1 on 2023-07-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_alter_orcamento_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='outros',
            field=models.ManyToManyField(blank=True, related_name='outros', to='orcamento.OrcamentoOpicional', verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='fixo',
            field=models.BooleanField(default=False, verbose_name='Opcional fixo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='opcionais',
            field=models.ManyToManyField(blank=True, related_name='opcionais', to='orcamento.OrcamentoOpicional', verbose_name='Opcionais'),
        ),
    ]
