# Generated by Django 4.0.1 on 2023-07-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0010_orcamento_outros_orcamentoopicional_fixo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorestransporte',
            name='tipo_transporte',
        ),
        migrations.RemoveField(
            model_name='valorestransporte',
            name='viacao',
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='decricao',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='leva_e_busca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Leva e Busca'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='percentual',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3, verbose_name='Percentual'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='periodo',
            field=models.ForeignKey(default='MSPS2023', on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentoperiodo', verbose_name='Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='vai_e_volta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Vai e Volta'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='valor_1_dia',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor de 1 dia'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='valor_2_dia',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor de 2 dias'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='valor_3_dia',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor de 3 dias'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='valor_acrescimo',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Acréscimo'),
        ),
    ]
