# Generated by Django 4.0.1 on 2023-07-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_remove_valorestransporte_tipo_transporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentoperiodo', verbose_name='Periodo')),
            ],
        ),
    ]
