# Generated by Django 4.0.1 on 2023-07-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_orcamentodiaria'),
    ]

#    operations = [
#        migrations.AddField(
#            model_name='orcamentoopicional',
#            name='fixo',
#            field=models.BooleanField(default=False, verbose_name='Opcional fixo'),
#        ),
#    ]
