# Generated by Django 4.0.1 on 2023-07-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0013_orcamentoopicional_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomonitor',
            name='racional_monitoria',
            field=models.PositiveIntegerField(default=8, verbose_name='Racional Monitoria'),
        ),
    ]
