# Generated by Django 4.0.1 on 2023-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0014_auto_20230718_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='objeto_gerencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='objeto_orcamento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
