# Generated by Django 4.0.1 on 2023-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0015_orcamento_objeto_gerencia_orcamento_objeto_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='motivo_recusa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da recusa'),
        ),
    ]
