# Generated by Django 4.0.1 on 2023-07-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0153_fichadeevento_data_divulgacao'),
        ('orcamento', '0016_alter_orcamento_motivo_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peraltas.vendedor'),
            preserve_default=False,
        ),
    ]
