# Generated by Django 4.0.1 on 2023-07-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0153_fichadeevento_data_divulgacao'),
        ('orcamento', '0017_orcamento_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='colaborador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.vendedor'),
        ),
    ]
