# Generated by Django 4.0.1 on 2023-07-21 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamento', '0018_alter_orcamento_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor orçamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='colaborador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
