# Generated by Django 4.0.1 on 2023-07-24 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0019_orcamento_valor_alter_orcamento_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_preenchimento',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de preenchimento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_ulitma_edicao',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data da ultima edição'),
        ),
    ]
