# Generated by Django 4.0.1 on 2023-07-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0020_orcamento_data_preenchimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_preenchimento',
            field=models.DateField(auto_now_add=True, verbose_name='Data de preenchimento'),
        ),
    ]
