# Generated by Django 4.0.1 on 2023-08-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0021_alter_orcamento_data_preenchimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='data_ulitma_edicao',
            new_name='data_ultima_edicao',
        ),
        migrations.RenameField(
            model_name='valorestransporte',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.statusorcamento', verbose_name='Status'),
        ),
    ]
