# Generated by Django 4.0.1 on 2023-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0022_statusorcamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_vencimento',
            field=models.DateField(default='2023-07-30', verbose_name='Data de vencimento'),
            preserve_default=False,
        ),
    ]
