# Generated by Django 4.0.1 on 2023-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0023_orcamento_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='outros',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='opcionais_extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Opcionais extra'),
        ),
    ]
