# Generated by Django 4.0.1 on 2023-08-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0024_remove_orcamento_outros_orcamento_opcionais_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='entrada',
            field=models.BooleanField(default=True),
        ),
    ]
