# Generated by Django 4.0.1 on 2023-09-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0026_delete_detectordebombas'),
        ('peraltas', '0153_fichadeevento_data_divulgacao'),
        ('orcamento', '0025_horariospadroes_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='hora_check_in',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='hora_check_out',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='n_dias',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='periodo_viagem',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='peraltas.AtividadesEco', verbose_name='Atividades Peraltas'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='atividades_ceu',
            field=models.ManyToManyField(blank=True, to='ceu.Atividades', verbose_name='Atividades CEU'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='check_in',
            field=models.DateTimeField(default='2023-09-04', verbose_name='Check in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='check_out',
            field=models.DateTimeField(default='2023-09-06', verbose_name='Check out'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peraltas.produtosperaltas', verbose_name='Produto Peraltas'),
            preserve_default=False,
        ),
    ]
