# Generated by Django 4.0.1 on 2023-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0026_remove_orcamento_hora_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='transporte',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=3, verbose_name='Transporte'),
        ),
    ]
