# Generated by Django 4.0.1 on 2023-11-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0027_alter_orcamento_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='racional',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
