# Generated by Django 4.0.1 on 2023-11-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0029_alter_horariospadroes_racional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariospadroes',
            name='racional',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
