# Generated by Django 4.0.1 on 2023-12-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0155_atividadeseco_valor'),
        ('orcamento', '0031_horariospadroes_racional_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.responsavel', verbose_name='Responsável'),
        ),
    ]
