# Generated by Django 4.0.1 on 2023-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0032_alter_orcamento_cliente_alter_orcamento_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='nome_promocional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do promocional'),
        ),
    ]
