# Generated by Django 4.0.1 on 2023-12-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0155_atividadeseco_valor'),
        ('orcamento', '0033_orcamento_nome_promocional'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDePacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pacote', models.CharField(max_length=255, verbose_name='Nome do Pacote')),
                ('limite_desconto_geral', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Limite de desconto geral')),
                ('minimo_de_diarias', models.PositiveIntegerField(verbose_name='Minimo de diarias')),
                ('maximo_de_diarias', models.PositiveIntegerField(verbose_name='Maximo de diarias')),
                ('minimo_de_pagantes', models.PositiveIntegerField(verbose_name='Minimo de pagantes')),
                ('cortesia', models.BooleanField(default=False, verbose_name='Cortesia')),
                ('limite_cortesia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de cortesias')),
                ('periodos_aplicaveis', models.JSONField(verbose_name='Periodos aplicaveis')),
                ('produtos_elegiveis', models.ManyToManyField(to='peraltas.ProdutosPeraltas', verbose_name='Produtos elegíveis')),
            ],
        ),
    ]
