# Generated by Django 4.0.1 on 2023-12-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0034_dadosdepacotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='nome_promocional',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pacote_promocional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.dadosdepacotes', verbose_name='Pacote promocional'),
        ),
    ]
