# Generated by Django 4.0.1 on 2023-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0035_remove_orcamento_nome_promocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosdepacotes',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição do pacote'),
            preserve_default=False,
        ),
    ]
