# Generated by Django 4.0.1 on 2023-12-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0036_dadosdepacotes_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='orcamento_promocional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.orcamento', verbose_name='Orçamento promocional'),
        ),
    ]
