# Generated by Django 4.0.1 on 2023-12-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0155_atividadeseco_valor'),
        ('orcamento', '0037_orcamento_orcamento_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check in'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check out'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.produtosperaltas', verbose_name='Produto Peraltas'),
        ),
    ]
