# Generated by Django 4.0.1 on 2024-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0038_alter_orcamento_check_in_alter_orcamento_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='taxa_periodo',
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=5),
            preserve_default=False,
        ),
    ]
