# Generated by Django 4.0.1 on 2024-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0039_orcamentoperiodo_taxa_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='ano',
            field=models.PositiveIntegerField(default=2024, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='dias_validos',
            field=models.IntegerField(choices=[(1, 'Meio de semana'), (2, 'Fim de semana'), (3, 'Qualquer dia')], default=1, verbose_name='Dias validos'),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='semestre',
            field=models.PositiveIntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo')], default=1, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='id',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
