# Generated by Django 4.0.1 on 2024-01-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0040_orcamentoperiodo_ano_orcamentoperiodo_dias_validos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_taxa', models.CharField(max_length=255, verbose_name='Nome da taxa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição da taxa')),
                ('id_taxa', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
