# Generated by Django 4.0.1 on 2024-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0041_valorespadrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratativas',
            fields=[
                ('id_tratativa', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('orcamentos', models.ManyToManyField(to='orcamento.Orcamento', verbose_name='Orcamentos')),
            ],
        ),
    ]
