# Generated by Django 4.0.1 on 2024-01-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0042_tratativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativas',
            name='orcamento_aceito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orcamento_aceito', to='orcamento.orcamento', verbose_name='Orcamento aceito'),
        ),
        migrations.AlterField(
            model_name='tratativas',
            name='orcamentos',
            field=models.ManyToManyField(related_name='orcamentos', to='orcamento.Orcamento', verbose_name='Orcamentos'),
        ),
    ]
