# Generated by Django 4.0.1 on 2024-01-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0164_merge_20240128_1235'),
        ('orcamento', '0043_tratativas_orcamento_aceito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
