# Generated by Django 4.0.1 on 2024-01-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamento', '0044_tratativas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativas',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratativas',
            name='ficha_financeira',
            field=models.BooleanField(default=False, verbose_name='Ficha financeira'),
        ),
    ]
