# Generated by Django 4.0.1 on 2024-01-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0045_tratativas_colaborador_tratativas_ficha_financeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativas',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.statusorcamento', verbose_name='Status da Tratativa'),
            preserve_default=False,
        ),
    ]
