# Generated by Django 4.0.1 on 2024-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0046_tratativas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativas',
            name='motivo_recusa',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
    ]
