# Generated by Django 4.0.1 on 2024-01-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0047_tratativas_motivo_recusa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratativas',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.statusorcamento', verbose_name='Status da Tratativa'),
        ),
    ]
