# Generated by Django 4.0.1 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0048_alter_tratativas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Desconto'),
        ),
    ]
