# Generated by Django 4.0.1 on 2024-09-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0048_alter_tratativas_status'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='orcamento',
        #     name='aprovado',
        # ),
        # migrations.RemoveField(
        #     model_name='orcamento',
        #     name='necessita_aprovacao_gerencia',
        # ),
        # migrations.RemoveField(
        #     model_name='orcamento',
        #     name='pacote_promocional',
        # ),
    ]
