# Generated by Django 4.0.1 on 2025-03-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0049_remove_orcamento_aprovado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='ano',
            field=models.PositiveIntegerField(default=2025, verbose_name='Ano'),
        ),
    ]
