# Generated by Django 4.0.1 on 2024-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0049_alter_orcamento_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorestransporte',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='valorestransporte',
            name='vai_e_volta',
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='valor_4_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Valor de 4 dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='valor_5_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Valor de 5 dias'),
            preserve_default=False,
        ),
    ]
