# Generated by Django 4.0.1 on 2024-02-17 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0050_remove_valorestransporte_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 14, 46, 38, 781514, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
