# Generated by Django 4.0.1 on 2024-02-17 17:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0051_valorestransporte_validade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoperiodo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='orcamentoperiodo',
            name='dias_validos',
        ),
        migrations.RemoveField(
            model_name='orcamentoperiodo',
            name='semestre',
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='dias_semana_validos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=1, size=None, verbose_name='Dias validos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 15, 17, 58, 18, 547875, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
