# Generated by Django 4.0.1 on 2024-02-19 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0052_remove_orcamentoperiodo_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 13, 47, 57, 145022, tzinfo=utc), verbose_name='Final da vigência'),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='inicio_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 2, 19, 13, 47, 57, 145022, tzinfo=utc), verbose_name='Início da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 13, 47, 57, 146022, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
