# Generated by Django 4.0.1 on 2024-02-19 13:48

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0053_orcamentoperiodo_final_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 13, 48, 28, 599368, tzinfo=utc), verbose_name='Final da vigência'),
        ),
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='inicio_vigencia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Início da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 13, 48, 28, 601363, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
