# Generated by Django 4.0.1 on 2024-02-19 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0057_alter_orcamentoperiodo_final_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 15, 4, 57, 58884, tzinfo=utc), verbose_name='Final da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 15, 4, 57, 59879, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
