# Generated by Django 4.0.1 on 2024-02-19 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0060_alter_orcamentoperiodo_dias_semana_validos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id_dia', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_dia', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamentoperiodo',
            name='dias_semana_validos',
        ),
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 15, 26, 53, 622706, tzinfo=utc), verbose_name='Final da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 17, 15, 26, 53, 625594, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='dias_semana_validos',
            field=models.ManyToManyField(to='orcamento.DiasSemana'),
        ),
    ]
