# Generated by Django 4.0.1 on 2024-02-20 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0061_diassemana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamentoperiodo',
            old_name='id',
            new_name='id_periodo',
        ),
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='dias_semana_validos',
            field=models.ManyToManyField(to='orcamento.DiasSemana', verbose_name='Dias da semana válido'),
        ),
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 19, 55, 46, 844252, tzinfo=utc), verbose_name='Final da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 19, 55, 46, 845333, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
