# Generated by Django 4.0.1 on 2024-02-20 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0062_rename_id_orcamentoperiodo_id_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 19, 59, 59, 151743, tzinfo=utc), verbose_name='Final da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 19, 59, 59, 152743, tzinfo=utc), verbose_name='Validade dos valores'),
        ),
    ]
