# Generated by Django 4.0.1 on 2024-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0063_alter_orcamentoperiodo_final_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='final_vigencia',
            field=models.DateField(default='self.default_final_vigencia', verbose_name='Final da vigência'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='validade',
            field=models.DateField(default='self.default_validade', verbose_name='Validade dos valores'),
        ),
    ]
