# Generated by Django 4.0.1 on 2024-02-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0065_alter_orcamentoperiodo_final_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='dias_semana_validos',
            field=models.ManyToManyField(to='orcamento.DiasSemana'),
        ),
    ]
