# Generated by Django 4.0.1 on 2024-02-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0066_alter_orcamentoperiodo_dias_semana_validos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='id_periodo',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
