# Generated by Django 4.0.1 on 2024-02-26 19:29

from django.db import migrations, models
import django.utils.timezone
import orcamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0067_alter_orcamentoperiodo_id_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorestransporte',
            name='validade',
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='final_validade',
            field=models.DateField(default=orcamento.models.default_validade, verbose_name='Final vigência dos valores'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='inicio_validade',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Inicio vigência dos valores'),
        ),
    ]
