# Generated by Django 4.0.1 on 2024-03-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0068_remove_valorestransporte_validade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoopicional',
            name='fixo',
        ),
    ]
