# Generated by Django 4.0.1 on 2024-03-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0069_remove_orcamentoopicional_fixo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoopicional',
            name='descricao',
            field=models.TextField(),
        ),
    ]
