# Generated by Django 4.0.1 on 2024-03-22 23:31

from django.db import migrations, models
import django.utils.timezone
import orcamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0070_alter_orcamentoopicional_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomonitor',
            name='final_vigencia',
            field=models.DateField(default=orcamento.models.default_validade),
        ),
        migrations.AddField(
            model_name='orcamentomonitor',
            name='inicio_vigencia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='acrescimo_barra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Acréscimo Barra Bonita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='valor_acrescimo',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Acréscimo dia extra'),
        ),
    ]
