# Generated by Django 4.0.1 on 2024-03-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0072_alter_valorespadrao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorespadrao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
