# Generated by Django 4.0.1 on 2024-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0073_alter_valorespadrao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorestransporte',
            name='titulo_transporte',
            field=models.CharField(default='Alterar título', max_length=255),
            preserve_default=False,
        ),
    ]
