# Generated by Django 4.0.1 on 2024-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0074_valorestransporte_titulo_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='saida',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
