# Generated by Django 4.0.1 on 2024-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0075_horariospadroes_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariospadroes',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='horariospadroes',
            name='saida',
        ),
        migrations.AddField(
            model_name='horariospadroes',
            name='entrada_saida',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
