# Generated by Django 4.0.1 on 2024-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0076_remove_horariospadroes_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorespadrao',
            old_name='valor',
            new_name='valor_padrao',
        ),
        migrations.AddField(
            model_name='valorespadrao',
            name='valor_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor maximo'),
        ),
        migrations.AddField(
            model_name='valorespadrao',
            name='valor_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor minimo'),
        ),
    ]
