# Generated by Django 4.0.1 on 2024-04-12 20:51

from django.db import migrations, models
import django.utils.timezone
import orcamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0077_rename_valor_valorespadrao_valor_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.now)),
                ('final_vigencia', models.DateField(default=orcamento.models.default_validade)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamentoperiodo',
            name='taxa_periodo',
        ),
        migrations.DeleteModel(
            name='OrcamentoDiaria',
        ),
    ]
