# Generated by Django 4.0.1 on 2024-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0078_taxaperiodo_remove_orcamentoperiodo_taxa_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariospadroes',
            name='racional',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Número de diárias de hotelaria', max_digits=3),
        ),
        migrations.AlterField(
            model_name='horariospadroes',
            name='racional_monitor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Número de diárias de monitoria', max_digits=3),
        ),
        migrations.AlterField(
            model_name='valorespadrao',
            name='valor_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Caso não haja, deixe em branco!', max_digits=5, null=True, verbose_name='Valor maximo'),
        ),
        migrations.AlterField(
            model_name='valorespadrao',
            name='valor_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Caso não haja, deixe em branco!', max_digits=5, null=True, verbose_name='Valor minimo'),
        ),
    ]
