# Generated by Django 4.0.1 on 2024-04-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0079_alter_horariospadroes_racional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentosPromocionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento')),
            ],
        ),
        migrations.DeleteModel(
            name='OrcamentoAlimentacao',
        ),
        migrations.AlterModelOptions(
            name='horariospadroes',
            options={'verbose_name': 'Horário de entrada e saída', 'verbose_name_plural': '02 - Horários de entrada e saída'},
        ),
        migrations.AlterModelOptions(
            name='orcamentomonitor',
            options={'verbose_name': 'Valor monitoria', 'verbose_name_plural': '05 - Valores de monitoria'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoopicional',
            options={'verbose_name': 'Valor opcionais', 'verbose_name_plural': '07 - Valores de opcionais'},
        ),
        migrations.AlterModelOptions(
            name='orcamentoperiodo',
            options={'verbose_name': 'Valor do periodo', 'verbose_name_plural': '03 - Valores de diárias'},
        ),
        migrations.AlterModelOptions(
            name='taxaperiodo',
            options={'verbose_name': 'Valor da taxa do periodo', 'verbose_name_plural': '04 - Valores da taxa dos periodos'},
        ),
        migrations.AlterModelOptions(
            name='valorespadrao',
            options={'verbose_name': 'Configuração geral', 'verbose_name_plural': '01 - Configurações gerias'},
        ),
        migrations.AlterModelOptions(
            name='valorestransporte',
            options={'verbose_name': 'Valor do transporte', 'verbose_name_plural': '06 - Valores de transporte'},
        ),
    ]
