# Generated by Django 4.0.1 on 2024-04-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0080_orcamentospromocionais_delete_orcamentoalimentacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': '09 - Orçamentos criados'},
        ),
        migrations.AlterModelOptions(
            name='orcamentospromocionais',
            options={'verbose_name': 'Orçamento promocional', 'verbose_name_plural': '08 - Pacotes prontos criados'},
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='necessita_aprovacao_gerencia',
        ),
    ]
