# Generated by Django 4.0.1 on 2024-04-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0081_alter_orcamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='previa',
            field=models.BooleanField(default=True),
        ),
    ]
