# Generated by Django 4.0.1 on 2024-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0082_orcamento_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='liberado',
            field=models.BooleanField(default=False, help_text='Liberado para o comercial'),
        ),
    ]
