# Generated by Django 4.0.1 on 2024-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0083_orcamentoperiodo_liberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='final_horario',
            field=models.TimeField(default='08:00:00', verbose_name='Final horário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horariospadroes',
            name='horario',
            field=models.TimeField(verbose_name='Início horário'),
        ),
    ]
