# Generated by Django 4.0.1 on 2024-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0084_horariospadroes_final_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='descricao_alimentacao',
            field=models.TextField(default='', verbose_name='Descrição das alimentações'),
            preserve_default=False,
        ),
    ]
