# Generated by Django 4.0.1 on 2024-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0085_horariospadroes_descricao_alimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariospadroes',
            name='final_horario',
            field=models.TimeField(verbose_name='Horário final'),
        ),
        migrations.AlterField(
            model_name='horariospadroes',
            name='horario',
            field=models.TimeField(verbose_name='Horário início'),
        ),
        migrations.AlterField(
            model_name='horariospadroes',
            name='refeicao',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
