# Generated by Django 4.0.1 on 2024-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0086_alter_horariospadroes_final_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='descriyivo',
            field=models.TextField(blank=True, verbose_name='Descritivo'),
        ),
    ]
