# Generated by Django 4.0.1 on 2024-05-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0087_horariospadroes_descriyivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariospadroes',
            old_name='descriyivo',
            new_name='descritivo',
        ),
    ]
