# Generated by Django 4.0.1 on 2024-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0088_rename_descriyivo_horariospadroes_descritivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='apelido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apelido'),
        ),
    ]
