# Generated by Django 4.0.1 on 2024-05-19 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamento', '0089_orcamento_apelido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='colaborador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
