# Generated by Django 4.0.1 on 2024-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0090_alter_orcamento_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='objeto_gerencia',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='objeto_orcamento',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='opcionais_extra',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Opcionais extra'),
        ),
    ]
