# Generated by Django 4.0.1 on 2024-06-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0091_alter_orcamento_objeto_gerencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasOpcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
