# Generated by Django 4.0.1 on 2024-06-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0092_categoriasopcionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoopicional',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orcamento.categoriasopcionais'),
            preserve_default=False,
        ),
    ]
