# Generated by Django 4.0.1 on 2024-06-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0093_orcamentoopicional_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='atividades_ceu',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='opcionais',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='opcionais_ceu',
            field=models.ManyToManyField(blank=True, related_name='opcionais_ceu', to='orcamento.OrcamentoOpicional', verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='opcionais_eco',
            field=models.ManyToManyField(blank=True, related_name='opcionais_eco', to='orcamento.OrcamentoOpicional', verbose_name='Ecoturismo'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='outros_opcionais',
            field=models.ManyToManyField(blank=True, related_name='outros_opcionais', to='orcamento.OrcamentoOpicional', verbose_name='Outros opcionais'),
        ),
    ]
