# Generated by Django 4.0.1 on 2024-06-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0094_remove_orcamento_atividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoopicional',
            name='categoria',
            field=models.CharField(choices=[('ceu', 'CEU'), ('outros', 'Outros opcionais'), ('eco', 'Ecoturismo')], max_length=100),
        ),
    ]
