# Generated by Django 4.0.1 on 2024-06-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0095_alter_orcamentoopicional_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriasOpcionais',
        ),
    ]
