# Generated by Django 4.0.1 on 2024-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0096_delete_categoriasopcionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorespadrao',
            name='comportamento',
            field=models.CharField(choices=[('porcentagem', 'Porcentagem'), ('intervalo_dias', 'Intervalo de dias'), ('numerico', 'Numérico'), ('monetario', 'Monetario')], default='porcentagem', help_text='Comportamento que a variável vai adotar dentro do sistema de orçamento', max_length=255, verbose_name='Comportamento'),
        ),
        migrations.AlterField(
            model_name='valorespadrao',
            name='valor_padrao',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor'),
        ),
    ]
