# Generated by Django 4.0.1 on 2024-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0097_valorespadrao_comportamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorespadrao',
            name='aparecer_comercial',
            field=models.BooleanField(default=True, help_text='Se essa taxa deve ou não ser vista pelo comercial'),
        ),
        migrations.AddField(
            model_name='valorespadrao',
            name='aparecer_gerência',
            field=models.BooleanField(default=True, help_text='Se essa taxa deve ou não ser vista pela gerência'),
        ),
        migrations.AddField(
            model_name='valorespadrao',
            name='nome_taxa_comercial',
            field=models.CharField(default='Taxa comercial', help_text='Nome que irá aparecer para o comercial e/ou para a gerência', max_length=30, verbose_name='Nome da taxa para o comercial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valorespadrao',
            name='nome_taxa',
            field=models.CharField(help_text='Esse nome irá aparecer apaenas para o finenceiro na área administrativa', max_length=255, verbose_name='Nome da taxa'),
        ),
    ]
