# Generated by Django 4.0.1 on 2024-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0098_valorespadrao_aparecer_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_ultima_edicao',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data da ultima edição'),
        ),
    ]
