# Generated by Django 4.0.1 on 2024-06-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0099_alter_orcamento_data_ultima_edicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamentospromocionais',
            options={'verbose_name': 'Pacotes promocionais', 'verbose_name_plural': '08 - Pacotes construidos'},
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='orcamento_promocional',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pacote_promocional',
        ),
        migrations.AddField(
            model_name='orcamentospromocionais',
            name='dados_pacote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orcamento.dadosdepacotes'),
            preserve_default=False,
        ),
    ]
