# Generated by Django 4.0.1 on 2024-06-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0100_alter_orcamentospromocionais_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='opcionais_extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Opcionais extra'),
        ),
    ]
