# Generated by Django 4.0.1 on 2024-06-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0102_orcamento_orcamento_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='orcamento_promocional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_orcamento_promocional', to='orcamento.orcamentospromocionais', verbose_name='Orçamento Promocional'),
        ),
    ]
