# Generated by Django 4.0.1 on 2024-07-20 18:56

from django.db import migrations, models, transaction
import django.db.models.deletion

import orcamento
from orcamento.models import CategoriaOpcionais, OrcamentoOpicional


def CriarCategoriasIniciais(apps, schema_editor):
    with transaction.atomic():
        categorias = apps.get_model('orcamento', 'CategoriaOpcionais')
        categorias_iniciais = ['Outros opcionais', 'Opcionais ecoturismo', 'Opcionais ceu']

        for categoria in categorias_iniciais:
            categorias.objects.create(nome_categoria=categoria)

        opcionais = apps.get_model('orcamento', 'OrcamentoOpicional')
        opcionais.objects.all().update(categoria=1)


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0103_alter_orcamento_orcamento_promocional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOpcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': '07a - Categorias de opcionais',
            },
        ),
        migrations.RunPython(CriarCategoriasIniciais),
        migrations.AlterModelOptions(
            name='orcamentoopicional',
            options={'verbose_name': 'Valor opcionais', 'verbose_name_plural': '07b - Valores de opcionais'},
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='final_vigencia',
            field=models.DateField(default=orcamento.models.default_validade),
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='inicio_vigencia',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamentoopicional',
            name='categoria',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='orcamento.categoriaopcionais',
                # default=1
            ),
        ),
    ]
