# Generated by Django 4.0.1 on 2024-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0104_categoriaopcionais_alter_orcamentoopicional_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='opcionais_ceu',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='opcionais_eco',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='outros_opcionais',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='opcionais',
            field=models.ManyToManyField(blank=True, to='orcamento.OrcamentoOpicional', verbose_name='Opcionais'),
        ),
    ]
