# Generated by Django 4.0.1 on 2024-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0105_remove_orcamento_opcionais_ceu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='aprovacao_diretoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='comentario_desconto',
            field=models.TextField(blank=True),
        ),
    ]
