# Generated by Django 4.0.1 on 2024-08-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0106_orcamento_aprovacao_diretoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaOpcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sub_categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': '07b - Subcategorias de opcionais',
            },
        ),
        migrations.AlterModelOptions(
            name='orcamentoopicional',
            options={'verbose_name': 'Valor opcionais', 'verbose_name_plural': '07c - Valores de opcionais'},
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.subcategoriaopcionais'),
        ),
    ]
