# Generated by Django 4.0.1 on 2024-08-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0107_subcategoriaopcionais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosdepacotes',
            name='limite_cortesia',
        ),
        migrations.AddField(
            model_name='dadosdepacotes',
            name='regra_cortesia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Regra de cortesias'),
        ),
        migrations.AlterField(
            model_name='dadosdepacotes',
            name='cortesia',
            field=models.BooleanField(default=True, verbose_name='Cortesia'),
        ),
    ]
