# Generated by Django 4.0.1 on 2024-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0108_remove_dadosdepacotes_limite_cortesia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomonitor',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
    ]
