# Generated by Django 4.0.1 on 2024-08-25 14:53

from django.db import migrations, models


def orcamento_valor_final(apps, schema_editor):
    valores_padrao = apps.get_model('orcamento', 'ValoresPadrao')
    opcionais = apps.get_model('orcamento', 'OrcamentoOpicional')

    taxa_comercial = float(valores_padrao.objects.get(id_taxa__icontains='comercial').valor_padrao)
    comissao = float(valores_padrao.objects.get(id_taxa__icontains='comissao').valor_padrao)

    for opcional in opcionais.objects.all():
        opcional.valor_final = float(opcional.valor) / (1 - ((taxa_comercial + comissao) / 100))
        opcional.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0109_orcamentomonitor_liberado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoopicional',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
        migrations.RunPython(orcamento_valor_final),
    ]
