# Generated by Django 4.0.1 on 2024-09-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0111_remove_valorestransporte_final_validade_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='orcamentoperiodo',
        #     name='dias_semana_validos',
        # ),
        # Migração necessário para o banco SQLite, ai não é necessário para o PostgresQl
    ]
