# Generated by Django 4.0.1 on 2024-09-01 21:41

from django.db import migrations, models


def resetar_ids(apps, schema_editor):
    OrcamentoPeriodo = apps.get_model('orcamento', 'OrcamentoPeriodo')
    for index, periodo in enumerate(OrcamentoPeriodo.objects.all(), start=1):
        periodo.id = index
        periodo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0112_remove_orcamentoperiodo_dias_semana_validos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoperiodo',
            name='id_periodo',
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RunPython(resetar_ids, reverse_code=migrations.RunPython.noop),
    ]
