# Generated by Django 4.0.1 on 2024-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0113_remove_orcamentoperiodo_id_periodo_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='orcamentoperiodo',
    #         name='dias_semana_validos',
    #         field=models.ManyToManyField(to='orcamento.DiasSemana'),
    #     ),
    # ]
