# Generated by Django 4.0.1 on 2024-09-04 19:25

from django.db import migrations, models
import django.utils.timezone
import orcamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0114_orcamentoperiodo_dias_semana_validos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoPeriodoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_periodo', models.CharField(max_length=255)),
                ('inicio_vigencia', models.DateField(default=django.utils.timezone.now, verbose_name='Início da vigência')),
                ('final_vigencia', models.DateField(default=orcamento.models.default_validade, verbose_name='Final da vigência')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descricao', models.TextField(blank=True)),
                ('liberado', models.BooleanField(default=False, help_text='Liberado para o comercial')),
                ('dias_semana_validos', models.ManyToManyField(to='orcamento.DiasSemana')),
            ],
            options={
                'verbose_name': 'Valor do periodo',
                'verbose_name_plural': '03 - Valores de diárias',
            },
        ),
    ]
