# Generated by Django 4.0.1 on 2024-09-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0115_orcamentoperiodotemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrcamentoPeriodo',
        ),
    ]
