# Generated by Django 4.0.1 on 2024-09-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0116_delete_orcamentoperiodo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrcamentoPeriodoTemp',
            new_name='OrcamentoPeriodo',
        ),
    ]
