# Generated by Django 4.0.1 on 2024-09-29 00:49

from django.db import migrations, models


def orcamento_valor_final(apps, schema_editor):
    valores_padrao = apps.get_model('orcamento', 'ValoresPadrao')
    periodos = apps.get_model('orcamento', 'OrcamentoPeriodo')

    taxa_comercial = float(valores_padrao.objects.get(id_taxa__icontains='comercial').valor_padrao)
    comissao = float(valores_padrao.objects.get(id_taxa__icontains='comissao').valor_padrao)

    for periodo in periodos.objects.all():
        periodo.valor_final = float(periodo.valor) / (1 - ((taxa_comercial + comissao) / 100))
        periodo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0117_rename_orcamentoperiodotemp_orcamentoperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='Preço de venda'),
        ),
        migrations.RunPython(orcamento_valor_final),
    ]
