# Generated by Django 4.0.1 on 2024-09-29 01:51

from django.db import migrations, models


def orcamento_valor_final(apps, schema_editor):
    valores_padrao = apps.get_model('orcamento', 'ValoresPadrao')
    transportes = apps.get_model('orcamento', 'ValoresTransporte')
    taxa_comercial = float(valores_padrao.objects.get(id_taxa__icontains='comercial').valor_padrao)
    comissao = float(valores_padrao.objects.get(id_taxa__icontains='comissao').valor_padrao)

    for transporte in transportes.objects.all():
        transporte.valor_final_1_dia = float(transporte.valor_1_dia) / (1 - ((taxa_comercial + comissao) / 100))
        transporte.valor_final_2_dia = float(transporte.valor_2_dia) / (1 - ((taxa_comercial + comissao) / 100))
        transporte.valor_final_3_dia = float(transporte.valor_3_dia) / (1 - ((taxa_comercial + comissao) / 100))
        transporte.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0119_orcamentomonitor_valor_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorestransporte',
            name='valor_final_1_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7, verbose_name='Preço de venda de 1 dia'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='valor_final_2_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7, verbose_name='Preço de venda de 2 dias'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='valor_final_3_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=7, verbose_name='Preço de venda de 3 dias'),
        ),
        migrations.RunPython(orcamento_valor_final),
    ]
