# Generated by Django 4.0.1 on 2024-10-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0120_valorestransporte_valor_final_1_dia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'permissions': (('aprovar_orcamentos', 'Aprovar orcamentos'),), 'verbose_name': 'Orçamento', 'verbose_name_plural': '09 - Orçamentos criados'},
        ),
    ]
