# Generated by Django 4.0.1 on 2024-11-02 19:17

from django.db import migrations, models


def pacote_personalizado(apps, schema_editor):
    TiposPacote = apps.get_model('orcamento', 'TiposDePacote')
    TiposPacote.objects.create(
        titulo='Personalizado',
        descricao='Montagem de pacotes personalizados',
        aparecer_montagem_pacotes=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0121_alter_orcamento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDePacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('teto_desconto_geral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimo_taxa_negocial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_padrao_taxa_negocial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximo_taxa_negocial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimo_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_padrao_comissoa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximo_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descricao', models.TextField()),
                ('aparecer_montagem_pacotes', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '10 - Tipos de pacote',
            },
        ),
        migrations.RunPython(pacote_personalizado)
    ]
