# Generated by Django 4.0.1 on 2024-11-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0122_tiposdepacote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='produto',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_de_pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.tiposdepacote', verbose_name='Tipo de pacote'),
        ),
    ]
