# Generated by Django 4.0.1 on 2024-11-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0123_remove_orcamento_produto_orcamento_tipo_de_pacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdepacote',
            name='n_diarias',
            field=models.PositiveIntegerField(blank=True, help_text='Deixar em branco em caso de não ter um número de diarias definido', null=True, verbose_name='Número de diarias'),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='maximo_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='maximo_taxa_negocial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='minimo_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='minimo_taxa_negocial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='teto_desconto_geral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='valor_padrao_comissoa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tiposdepacote',
            name='valor_padrao_taxa_negocial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para pegar os valores padrão', max_digits=5, null=True),
        ),
    ]
