# Generated by Django 4.0.1 on 2024-11-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0124_tiposdepacote_n_diarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdepacote',
            name='so_ceu',
            field=models.BooleanField(default=False),
        ),
    ]
