# Generated by Django 4.0.1 on 2024-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0125_tiposdepacote_so_ceu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosdepacotes',
            name='limite_desconto_geral',
        ),
        migrations.RemoveField(
            model_name='dadosdepacotes',
            name='maximo_de_diarias',
        ),
        migrations.RemoveField(
            model_name='dadosdepacotes',
            name='minimo_de_diarias',
        ),
        migrations.RemoveField(
            model_name='dadosdepacotes',
            name='produtos_elegiveis',
        ),
        migrations.AddField(
            model_name='dadosdepacotes',
            name='monitoria_fechado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dadosdepacotes',
            name='opcionais_fechado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dadosdepacotes',
            name='tipos_de_pacote',
            field=models.ManyToManyField(to='orcamento.TiposDePacote', verbose_name='Pacotes elegíveis'),
        ),
        migrations.AddField(
            model_name='dadosdepacotes',
            name='transporte_fechado',
            field=models.BooleanField(default=True),
        ),
    ]
