# Generated by Django 4.0.1 on 2024-11-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0126_remove_dadosdepacotes_limite_desconto_geral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosdepacotes',
            old_name='tipos_de_pacote',
            new_name='tipos_de_pacote_elegivel',
        ),
    ]
