# Generated by Django 4.0.1 on 2024-11-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0127_rename_tipos_de_pacote_dadosdepacotes_tipos_de_pacote_elegivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosdepacotes',
            name='tipos_de_pacote_elegivel',
        ),
        migrations.AddField(
            model_name='dadosdepacotes',
            name='tipos_de_pacote_elegivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orcamento.tiposdepacote', verbose_name='Pacotes elegíveis'),
            preserve_default=False,
        ),
    ]
