# Generated by Django 4.0.1 on 2024-11-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0128_remove_dadosdepacotes_tipos_de_pacote_elegivel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposdepacote',
            old_name='valor_padrao_comissoa',
            new_name='valor_padrao_comissao',
        ),
    ]
