# Generated by Django 4.0.1 on 2024-11-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0164_merge_20240128_1235'),
        ('orcamento', '0129_rename_valor_padrao_comissoa_tiposdepacote_valor_padrao_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.produtosperaltas', verbose_name='Produto'),
        ),
    ]
