# Generated by Django 4.0.1 on 2024-11-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0130_orcamento_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposdepacote',
            name='aparecer_montagem_pacotes',
        ),
        migrations.RemoveField(
            model_name='tiposdepacote',
            name='n_diarias',
        ),
    ]
