# Generated by Django 4.0.1 on 2024-11-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0131_remove_tiposdepacote_aparecer_montagem_pacotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdepacote',
            name='n_diarias',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de diarias'),
        ),
    ]
