# Generated by Django 4.0.1 on 2024-11-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0132_tiposdepacote_n_diarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='exclusivo_montagem_pacote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamentospromocionais',
            name='liberados_para_venda',
            field=models.BooleanField(default=False),
        ),
    ]
