# Generated by Django 4.0.1 on 2024-12-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0133_orcamentoperiodo_exclusivo_montagem_pacote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaopcionais',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
