# Generated by Django 4.0.1 on 2024-12-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0134_categoriaopcionais_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamentospromocionais',
            old_name='liberados_para_venda',
            new_name='liberado_para_venda',
        ),
    ]
