# Generated by Django 4.0.1 on 2024-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0135_rename_liberados_para_venda_orcamentospromocionais_liberado_para_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaopcionais',
            name='ceu_sem_hospedagem',
            field=models.BooleanField(default=False),
        ),
    ]
