# Generated by Django 4.0.1 on 2024-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0136_categoriaopcionais_ceu_sem_hospedagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomonitor',
            name='sem_monitoria',
            field=models.BooleanField(default=False),
        ),
    ]
