# Generated by Django 4.0.1 on 2024-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0137_orcamentomonitor_sem_monitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariospadroes',
            name='so_ceu',
            field=models.BooleanField(default=False),
        ),
    ]
