# Generated by Django 4.0.1 on 2025-02-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_classificacoesitens'),
        ('orcamento', '0138_horariospadroes_so_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomonitor',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AddField(
            model_name='orcamentoopicional',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AddField(
            model_name='orcamentoperiodo',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AddField(
            model_name='taxaperiodo',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AddField(
            model_name='valorespadrao',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AddField(
            model_name='valorestransporte',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
    ]
