# Generated by Django 4.0.1 on 2025-02-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0140_orcamento_gerente_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorcamento',
            name='aprovacao_gerencia',
            field=models.BooleanField(default=False, help_text='Status de orçamento utilizado pela gerência para aprovar um pedido do comercial'),
        ),
        migrations.AddField(
            model_name='statusorcamento',
            name='negativa_gerencia',
            field=models.BooleanField(default=False, help_text='Status de orçamento utilizado pela gerência para negar um pedido do comercial'),
        ),
    ]
