# Generated by Django 4.0.1 on 2025-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0141_statusorcamento_aprovacao_gerencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorcamento',
            name='analise_gerencia',
            field=models.BooleanField(default=False, help_text='Status utilizado para análise da gerência.'),
        ),
        migrations.AlterField(
            model_name='statusorcamento',
            name='aprovacao_gerencia',
            field=models.BooleanField(default=False, help_text='Status de orçamento utilizado pela gerência para aprovar um pedido do comercial.'),
        ),
        migrations.AlterField(
            model_name='statusorcamento',
            name='negativa_gerencia',
            field=models.BooleanField(default=False, help_text='Status de orçamento utilizado pela gerência para negar um pedido do comercial.'),
        ),
    ]
