# Generated by Django 4.0.1 on 2025-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0142_statusorcamento_analise_gerencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorcamento',
            name='analise_gerencia',
            field=models.BooleanField(default=False, help_text='Status utilizado para análise e respostas da gerência.'),
        ),
    ]
