# Generated by Django 4.0.1 on 2025-02-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0143_alter_statusorcamento_analise_gerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorcamento',
            name='aprovacao_cliente',
            field=models.BooleanField(default=False, help_text='Status utilizado para orçamentos aceitos pelo cliente.'),
        ),
        migrations.AddField(
            model_name='statusorcamento',
            name='negado_cliente',
            field=models.BooleanField(default=False, help_text='Status utilizado para orçamentos no qual o cliente não aceitou.'),
        ),
    ]
