# Generated by Django 4.0.1 on 2025-02-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0144_statusorcamento_aprovacao_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorcamento',
            name='orcamento_vencido',
            field=models.BooleanField(default=False, help_text='Status utilizado para orçamentos que estão vencdos.'),
        ),
    ]
