# Generated by Django 4.0.1 on 2025-02-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0145_statusorcamento_orcamento_vencido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativas',
            name='orcamentos_em_previa',
            field=models.ManyToManyField(related_name='orcamentos_em_previa', to='orcamento.Orcamento'),
        ),
    ]
