# Generated by Django 4.0.1 on 2025-04-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_fichafinanceira_data_aprovacao_diretoria_and_more'),
        ('orcamento', '0147_remove_valorespadrao_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoopicional',
            name='classificacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'sintetico_analitico': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AlterField(
            model_name='orcamentoperiodo',
            name='classificacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'sintetico_analitico': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AlterField(
            model_name='taxaperiodo',
            name='classificacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'sintetico_analitico': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
        migrations.AlterField(
            model_name='valorestransporte',
            name='classificacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'sintetico_analitico': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.classificacoesitens'),
        ),
    ]
