# Generated by Django 4.0.1 on 2025-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0149_alter_orcamentomonitor_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='condicoes_finais',
            field=models.TextField(blank=True),
        ),
    ]
