# Generated by Django 4.0.1 on 2025-05-02 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0150_orcamento_condicoes_finais'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_vigencia', models.PositiveIntegerField(default=2025, help_text='Apenas um arquivo de template será permitido por ano. Caso um novo arquivo seja enviado para um ano que já possua um template cadastrado, o arquivo anterior será automaticamente substituído pelo mais recente')),
                ('arquivo', models.FileField(help_text='Arquivo em <strong>PDF</strong> contendo o modelo de orçamento a ser utilizado para o ano correspondente. <strong>A proposta comercial será sempre inserida antes da última página do template</strong>. O arquivo deve conter <strong>somente as informações fixas</strong>, pois todas as páginas referentes à proposta comercial serão geradas automaticamente pelo sistema.', upload_to='orcamentos/templates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
