# Generated by Django 4.0.1 on 2025-05-02 14:35

import django.core.validators
from django.db import migrations, models
import orcamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0151_templateorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateorcamento',
            name='arquivo',
            field=models.FileField(help_text='Arquivo em <strong>PDF</strong> contendo o modelo de orçamento a ser utilizado para o ano correspondente. <strong>A proposta comercial será sempre inserida antes da última página do template</strong>. O arquivo deve conter <strong>somente as informações fixas</strong>, pois todas as páginas referentes à proposta comercial serão geradas automaticamente pelo sistema.', upload_to=orcamento.models.rename_template_orcamento, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
