# Generated by Django 4.0.1 on 2025-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0152_alter_templateorcamento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateorcamento',
            name='ano_vigencia',
            field=models.PositiveIntegerField(default=2025, help_text='Apenas um arquivo de template será permitido por ano. Caso um novo arquivo seja enviado para um ano que já possua um template cadastrado, o arquivo anterior será automaticamente substituído pelo mais recente', unique=True),
        ),
    ]
