# Generated by Django 4.0.1 on 2025-05-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0153_alter_templateorcamento_ano_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_preenchimento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de preenchimento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_ultima_edicao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da ultima edição'),
        ),
    ]
