# Generated by Django 4.0.1 on 2025-05-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0154_alter_orcamento_data_preenchimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'permissions': (('aprovar_orcamentos', 'Aprovar orcamentos'), ('ver_outras_previas', 'Ver outras prévias')), 'verbose_name': 'Orçamento', 'verbose_name_plural': '09 - Orçamentos criados'},
        ),
    ]
