# Generated by Django 4.0.1 on 2025-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0155_alter_orcamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomonitor',
            name='regra_cortesia',
            field=models.TextField(blank=True, help_text='Texto da regra de cortesia que será mostrado dentro das condições finais do orçamento'),
        ),
    ]
