# Generated by Django 4.0.1 on 2025-06-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0156_orcamentomonitor_regra_cortesia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegrasFinais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regras_de_cortesia', models.TextField()),
                ('regras_de_pagantes', models.PositiveIntegerField(default=35)),
                ('extra_condicoes_finais', models.TextField(blank=True)),
                ('n_parcelas', models.PositiveIntegerField(default=6)),
                ('n_parcelas_sistema_pagamentos', models.PositiveIntegerField(default=6)),
                ('n_parcelas_escolas', models.PositiveIntegerField(default=5)),
                ('extra_pagamentos', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='condicoes_finais',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='regras_finais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orcamento.regrasfinais'),
        ),
    ]
