# Generated by Django 4.0.1 on 2025-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0157_regrasfinais_remove_orcamento_condicoes_finais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='regras_finais',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='condicoes_finais',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='regras_de_pagamento',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RegrasFinais',
        ),
    ]
