# Generated by Django 4.0.1 on 2025-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0158_remove_orcamento_regras_finais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='condicoes_finais',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='regras_de_pagamento',
            field=models.TextField(blank=True, default='Os pagamentos podem ser realizados de duas maneiras <ol><li><b>Via Sistema Peraltas</b>: Até 6 parcelas mensais consecutivas. </li><li><b>Via Escola</b>: Em até 5 parcelas.</li><li>Em caso de dúvida, entre em contato com a sua consultora de vendas.</li></ol>'),
        ),
    ]
