# Generated by Django 4.0.1 on 2025-07-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0050_alter_orcamentoperiodo_ano'),
        ('orcamento', '0159_alter_orcamento_condicoes_finais_and_more'),
    ]

    operations = [
    ]
