# Generated by Django 4.0.1 on 2025-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0160_merge_20250722_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosRecusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de recusa')),
            ],
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='motivo_recusa',
            new_name='obs_recusa',
        ),
    ]
