# Generated by Django 4.0.1 on 2025-07-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0161_motivosrecusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='motivo_recusa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamento.motivosrecusa', verbose_name='Motivo da recusa'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='obs_recusa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oservações da recusa'),
        ),
    ]
