# Generated by Django 4.0.1 on 2025-08-10 01:18

from django.db import migrations, models


def add_ficha_financeira(apps, schema_editor):
    Orcamento = apps.get_model('orcamento', 'Orcamento')
    Tratativa = apps.get_model('orcamento', 'Tratativas')
    tratativas_c_ficha_financeira = Tratativa.objects.filter(ficha_financeira=True)

    for tratativa in tratativas_c_ficha_financeira:
        orcamentos = tratativa.orcamentos.all()
        orcamentos.update(ficha_financeira=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0162_orcamento_motivo_recusa_alter_orcamento_obs_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ficha_financeira',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_ficha_financeira),
    ]
