# Generated by Django 4.0.1 on 2025-08-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0163_orcamento_ficha_financeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_aprovacao_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação do cliente'),
        ),
    ]
