# Generated by Django 4.0.1 on 2025-08-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0164_orcamento_data_aprovacao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_aprovacao_cliente',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aprovação do cliente'),
        ),
    ]
