# Generated by Django 4.0.1 on 2022-04-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=300)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponiveis', models.TextField(max_length=500)),
                ('mes', models.IntegerField(choices=[(2, 'Fevereiro'), (9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (8, 'Agosto'), (3, 'Março'), (7, 'Julho'), (6, 'Junho')])),
                ('ano', models.CharField(max_length=20)),
                ('n_dias', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceu.professores')),
            ],
        ),
    ]
