# Generated by Django 3.2.9 on 2022-02-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=300)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponiveis', models.TextField(max_length=500)),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (11, 'Novembro'), (8, 'Agosto'), (9, 'Setembro'), (6, 'Junho'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro'), (10, 'Outubro')])),
                ('ano', models.CharField(max_length=20)),
                ('n_dias', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.professores')),
            ],
        ),
    ]
