# Generated by Django 3.2.9 on 2021-12-30 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalados', models.CharField(max_length=300)),
                ('data', models.DateField(default=datetime.datetime(2021, 12, 30, 1, 49, 53, 501646, tzinfo=utc))),
            ],
        ),
    ]
