# Generated by Django 4.0.1 on 2022-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (6, 'Junho'), (5, 'Maio'), (8, 'Agosto'), (1, 'Janeiro'), (11, 'Novembro'), (2, 'Fevereiro'), (4, 'Abril'), (9, 'Setembro'), (10, 'Outubro'), (7, 'Julho'), (3, 'Março')]),
        ),
    ]
