# Generated by Django 3.2.9 on 2022-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (2, 'Fevereiro'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (3, 'Março'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho')]),
        ),
    ]
