# Generated by Django 3.2.9 on 2022-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (6, 'Junho'), (2, 'Fevereiro'), (10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (1, 'Janeiro'), (3, 'Março'), (4, 'Abril')]),
        ),
    ]
