# Generated by Django 4.0.1 on 2022-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (12, 'Dezembro'), (1, 'Janeiro'), (7, 'Julho'), (11, 'Novembro'), (4, 'Abril'), (10, 'Outubro'), (6, 'Junho'), (2, 'Fevereiro'), (3, 'Março'), (8, 'Agosto'), (5, 'Maio')]),
        ),
    ]
