# Generated by Django 3.2.9 on 2021-12-30 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_auto_20211229_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 23, 7, 54, 147638)),
        ),
    ]
