# Generated by Django 3.2.9 on 2022-02-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (7, 'Julho'), (3, 'Março'), (5, 'Maio'), (1, 'Janeiro'), (12, 'Dezembro'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (2, 'Fevereiro'), (9, 'Setembro')]),
        ),
    ]
