# Generated by Django 4.0.1 on 2022-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (3, 'Março'), (5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (10, 'Outubro')]),
        ),
    ]
