# Generated by Django 3.2.9 on 2022-02-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (9, 'Setembro'), (8, 'Agosto'), (7, 'Julho'), (5, 'Maio'), (10, 'Outubro'), (11, 'Novembro'), (3, 'Março'), (12, 'Dezembro'), (1, 'Janeiro')]),
        ),
    ]
