# Generated by Django 4.0.1 on 2022-04-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (12, 'Dezembro'), (10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (4, 'Abril'), (1, 'Janeiro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro')]),
        ),
    ]
