# Generated by Django 4.0.1 on 2022-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (4, 'Abril'), (11, 'Novembro'), (10, 'Outubro'), (6, 'Junho'), (8, 'Agosto'), (7, 'Julho'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio')]),
        ),
    ]
