# Generated by Django 4.0.1 on 2022-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0005_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (12, 'Dezembro'), (6, 'Junho'), (10, 'Outubro'), (4, 'Abril'), (11, 'Novembro'), (9, 'Setembro'), (3, 'Março'), (2, 'Fevereiro'), (8, 'Agosto'), (7, 'Julho'), (5, 'Maio')]),
        ),
    ]
