# Generated by Django 4.0.1 on 2022-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0005_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (10, 'Outubro'), (3, 'Março'), (2, 'Fevereiro'), (4, 'Abril'), (12, 'Dezembro'), (8, 'Agosto'), (7, 'Julho'), (11, 'Novembro')]),
        ),
    ]
