# Generated by Django 3.2.9 on 2021-12-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_ordemdeservico_coordenador'),
        ('escala', '0005_alter_escala_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='professor_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_5_escala', to='cadastro.professores'),
        ),
    ]
