# Generated by Django 4.0.1 on 2022-02-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0001_initial'),
        ('escala', '0006_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (10, 'Outubro'), (8, 'Agosto'), (2, 'Fevereiro'), (6, 'Junho'), (11, 'Novembro'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceu.professores'),
        ),
    ]
