# Generated by Django 4.0.1 on 2022-01-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0006_escala_professor_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='professor_2',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='professor_3',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='professor_4',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='professor_5',
        ),
        migrations.AddField(
            model_name='escala',
            name='equipe',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
