# Generated by Django 4.0.1 on 2022-03-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0007_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (12, 'Dezembro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (6, 'Junho'), (11, 'Novembro'), (10, 'Outubro'), (1, 'Janeiro'), (9, 'Setembro'), (8, 'Agosto'), (7, 'Julho')]),
        ),
    ]
