# Generated by Django 4.0.1 on 2022-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0007_alter_disponibilidade_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março'), (5, 'Maio'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (6, 'Junho'), (11, 'Novembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
    ]
