# Generated by Django 4.0.1 on 2022-01-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_ordemdeservico_entregue'),
        ('escala', '0007_remove_escala_coordenador_remove_escala_professor_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponiveis', models.TextField(max_length=500)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.professores')),
            ],
        ),
    ]
