# Generated by Django 3.2.9 on 2022-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0008_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (12, 'Dezembro'), (9, 'Setembro'), (11, 'Novembro'), (6, 'Junho'), (5, 'Maio'), (3, 'Março'), (8, 'Agosto'), (7, 'Julho')]),
        ),
    ]
