# Generated by Django 4.0.1 on 2022-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0009_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (1, 'Janeiro'), (8, 'Agosto'), (10, 'Outubro'), (11, 'Novembro'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (9, 'Setembro'), (6, 'Junho')]),
        ),
    ]
