# Generated by Django 4.0.1 on 2022-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0009_disponibilidade_mes_referencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidade',
            old_name='mes_referencia',
            new_name='mes',
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='ano',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
