# Generated by Django 4.0.1 on 2022-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0009_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (10, 'Outubro'), (6, 'Junho'), (9, 'Setembro'), (8, 'Agosto'), (7, 'Julho'), (2, 'Fevereiro'), (11, 'Novembro'), (12, 'Dezembro')]),
        ),
    ]
