# Generated by Django 4.0.1 on 2022-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0010_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (7, 'Julho'), (12, 'Dezembro'), (3, 'Março'), (4, 'Abril'), (2, 'Fevereiro'), (6, 'Junho')]),
        ),
    ]
