# Generated by Django 4.0.1 on 2022-01-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0010_rename_mes_referencia_disponibilidade_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (5, 'Maio'), (10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (2, 'Fevereiro'), (3, 'Março'), (9, 'Setembro')]),
        ),
    ]
