# Generated by Django 4.0.1 on 2022-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0010_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (9, 'Setembro'), (5, 'Maio'), (2, 'Fevereiro'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (3, 'Março'), (12, 'Dezembro'), (11, 'Novembro'), (1, 'Janeiro'), (10, 'Outubro')]),
        ),
    ]
