# Generated by Django 4.0.1 on 2022-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0011_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (11, 'Novembro'), (5, 'Maio'), (6, 'Junho'), (2, 'Fevereiro'), (1, 'Janeiro'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (12, 'Dezembro'), (9, 'Setembro')]),
        ),
    ]
