# Generated by Django 4.0.1 on 2022-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0011_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (12, 'Dezembro'), (5, 'Maio'), (4, 'Abril'), (2, 'Fevereiro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (10, 'Outubro')]),
        ),
    ]
