# Generated by Django 4.0.1 on 2022-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0011_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (9, 'Setembro'), (10, 'Outubro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (4, 'Abril'), (2, 'Fevereiro'), (3, 'Março'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho')]),
        ),
    ]
