# Generated by Django 4.0.1 on 2022-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0012_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (1, 'Janeiro'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (9, 'Setembro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (7, 'Julho'), (12, 'Dezembro')]),
        ),
    ]
