# Generated by Django 4.0.1 on 2022-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0012_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (6, 'Junho')]),
        ),
    ]
