# Generated by Django 4.0.1 on 2022-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0013_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (5, 'Maio'), (9, 'Setembro'), (1, 'Janeiro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (6, 'Junho'), (2, 'Fevereiro'), (11, 'Novembro'), (4, 'Abril')]),
        ),
    ]
