# Generated by Django 4.0.1 on 2022-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0013_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (3, 'Março'), (6, 'Junho'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (1, 'Janeiro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (9, 'Setembro')]),
        ),
    ]
