# Generated by Django 4.0.1 on 2022-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0013_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (6, 'Junho'), (3, 'Março'), (10, 'Outubro'), (1, 'Janeiro')]),
        ),
    ]
