# Generated by Django 4.0.1 on 2022-01-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0014_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (12, 'Dezembro'), (2, 'Fevereiro'), (11, 'Novembro'), (4, 'Abril'), (5, 'Maio'), (8, 'Agosto'), (10, 'Outubro'), (9, 'Setembro'), (6, 'Junho'), (3, 'Março'), (7, 'Julho')]),
        ),
    ]
