# Generated by Django 4.0.1 on 2022-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0014_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (3, 'Março'), (8, 'Agosto'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (11, 'Novembro'), (1, 'Janeiro'), (7, 'Julho')]),
        ),
    ]
