# Generated by Django 4.0.1 on 2022-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0014_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (9, 'Setembro'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (7, 'Julho'), (10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (11, 'Novembro'), (12, 'Dezembro'), (5, 'Maio')]),
        ),
    ]
