# Generated by Django 3.2.9 on 2022-02-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0016_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (10, 'Outubro'), (3, 'Março'), (11, 'Novembro'), (7, 'Julho'), (5, 'Maio')]),
        ),
    ]
