# Generated by Django 4.0.1 on 2022-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0016_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (2, 'Fevereiro'), (12, 'Dezembro'), (6, 'Junho'), (11, 'Novembro'), (8, 'Agosto'), (10, 'Outubro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro')]),
        ),
    ]
