# Generated by Django 4.0.1 on 2022-04-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0016_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (8, 'Agosto'), (3, 'Março'), (1, 'Janeiro'), (2, 'Fevereiro'), (12, 'Dezembro'), (7, 'Julho'), (11, 'Novembro'), (4, 'Abril')]),
        ),
    ]
