# Generated by Django 3.2.9 on 2022-02-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0017_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (2, 'Fevereiro'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (10, 'Outubro'), (6, 'Junho')]),
        ),
    ]
