# Generated by Django 4.0.1 on 2022-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0017_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (3, 'Março'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (8, 'Agosto')]),
        ),
    ]
