# Generated by Django 4.0.1 on 2022-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0017_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (4, 'Abril'), (2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (3, 'Março'), (8, 'Agosto'), (6, 'Junho'), (12, 'Dezembro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio')]),
        ),
    ]
