# Generated by Django 4.0.1 on 2022-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0018_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (2, 'Fevereiro'), (5, 'Maio'), (3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (8, 'Agosto'), (6, 'Junho'), (7, 'Julho'), (1, 'Janeiro'), (12, 'Dezembro'), (10, 'Outubro')]),
        ),
    ]
