# Generated by Django 4.0.1 on 2022-02-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0019_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (11, 'Novembro'), (7, 'Julho'), (1, 'Janeiro'), (4, 'Abril'), (12, 'Dezembro'), (3, 'Março'), (6, 'Junho'), (9, 'Setembro'), (2, 'Fevereiro'), (5, 'Maio'), (10, 'Outubro')]),
        ),
    ]
