# Generated by Django 4.0.1 on 2022-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0019_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (7, 'Julho'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (9, 'Setembro'), (2, 'Fevereiro'), (8, 'Agosto'), (6, 'Junho'), (4, 'Abril')]),
        ),
    ]
