# Generated by Django 4.0.1 on 2022-04-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0020_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (12, 'Dezembro'), (3, 'Março'), (8, 'Agosto'), (4, 'Abril'), (9, 'Setembro'), (6, 'Junho'), (2, 'Fevereiro'), (5, 'Maio'), (10, 'Outubro')]),
        ),
    ]
