# Generated by Django 4.0.1 on 2022-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0020_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (10, 'Outubro'), (2, 'Fevereiro'), (8, 'Agosto'), (11, 'Novembro')]),
        ),
    ]
