# Generated by Django 4.0.1 on 2022-04-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0021_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (4, 'Abril'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (2, 'Fevereiro'), (5, 'Maio'), (6, 'Junho'), (10, 'Outubro'), (12, 'Dezembro'), (3, 'Março')]),
        ),
    ]
