# Generated by Django 4.0.1 on 2022-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0021_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (8, 'Agosto'), (10, 'Outubro'), (12, 'Dezembro'), (4, 'Abril'), (11, 'Novembro'), (2, 'Fevereiro'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março')]),
        ),
    ]
