# Generated by Django 4.0.1 on 2022-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0021_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (4, 'Abril'), (5, 'Maio'), (9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (8, 'Agosto')]),
        ),
    ]
