# Generated by Django 4.0.1 on 2022-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0022_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (3, 'Março'), (4, 'Abril'), (10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (9, 'Setembro')]),
        ),
    ]
