# Generated by Django 4.0.1 on 2022-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0022_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (8, 'Agosto'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (11, 'Novembro'), (9, 'Setembro'), (6, 'Junho'), (3, 'Março')]),
        ),
    ]
