# Generated by Django 4.0.1 on 2022-04-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0023_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (10, 'Outubro'), (1, 'Janeiro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (12, 'Dezembro'), (2, 'Fevereiro'), (6, 'Junho')]),
        ),
    ]
