# Generated by Django 4.0.1 on 2022-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0023_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (12, 'Dezembro'), (7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (4, 'Abril'), (3, 'Março'), (5, 'Maio'), (8, 'Agosto'), (10, 'Outubro')]),
        ),
    ]
