# Generated by Django 4.0.1 on 2022-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0024_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (3, 'Março'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (11, 'Novembro'), (1, 'Janeiro'), (4, 'Abril'), (8, 'Agosto')]),
        ),
    ]
