# Generated by Django 4.0.1 on 2022-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0024_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro'), (5, 'Maio'), (7, 'Julho'), (1, 'Janeiro'), (10, 'Outubro')]),
        ),
    ]
