# Generated by Django 4.0.1 on 2022-02-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0025_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (8, 'Agosto'), (1, 'Janeiro'), (3, 'Março'), (4, 'Abril'), (2, 'Fevereiro'), (7, 'Julho'), (10, 'Outubro'), (6, 'Junho'), (5, 'Maio'), (11, 'Novembro'), (9, 'Setembro')]),
        ),
    ]
