# Generated by Django 4.0.1 on 2022-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0026_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março'), (10, 'Outubro'), (6, 'Junho'), (5, 'Maio'), (7, 'Julho'), (9, 'Setembro'), (8, 'Agosto')]),
        ),
    ]
