# Generated by Django 4.0.1 on 2022-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0028_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (6, 'Junho'), (5, 'Maio'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (7, 'Julho'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (3, 'Março'), (10, 'Outubro')]),
        ),
    ]
