# Generated by Django 4.0.1 on 2022-04-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0028_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (11, 'Novembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (6, 'Junho'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março'), (4, 'Abril'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro')]),
        ),
    ]
