# Generated by Django 4.0.1 on 2022-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0029_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (2, 'Fevereiro'), (8, 'Agosto'), (3, 'Março'), (6, 'Junho'), (11, 'Novembro'), (12, 'Dezembro'), (10, 'Outubro'), (4, 'Abril'), (7, 'Julho')]),
        ),
    ]
