# Generated by Django 4.0.1 on 2022-03-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0029_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (1, 'Janeiro'), (7, 'Julho'), (10, 'Outubro'), (11, 'Novembro'), (9, 'Setembro'), (3, 'Março')]),
        ),
    ]
