# Generated by Django 4.0.1 on 2022-03-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0030_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (7, 'Julho'), (4, 'Abril'), (11, 'Novembro'), (10, 'Outubro'), (9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (3, 'Março'), (8, 'Agosto'), (2, 'Fevereiro'), (5, 'Maio')]),
        ),
    ]
