# Generated by Django 4.0.1 on 2022-02-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0030_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (12, 'Dezembro'), (5, 'Maio'), (11, 'Novembro'), (6, 'Junho'), (2, 'Fevereiro'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março')]),
        ),
    ]
