# Generated by Django 4.0.1 on 2022-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0031_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (2, 'Fevereiro'), (7, 'Julho'), (6, 'Junho'), (9, 'Setembro'), (4, 'Abril'), (11, 'Novembro'), (12, 'Dezembro'), (3, 'Março'), (1, 'Janeiro'), (5, 'Maio'), (10, 'Outubro')]),
        ),
    ]
