# Generated by Django 4.0.1 on 2022-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0031_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (11, 'Novembro'), (8, 'Agosto'), (3, 'Março'), (1, 'Janeiro'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril'), (12, 'Dezembro'), (5, 'Maio'), (2, 'Fevereiro'), (6, 'Junho')]),
        ),
    ]
