# Generated by Django 4.0.1 on 2022-02-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0032_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (8, 'Agosto'), (2, 'Fevereiro'), (4, 'Abril'), (10, 'Outubro'), (1, 'Janeiro'), (3, 'Março'), (11, 'Novembro'), (5, 'Maio'), (12, 'Dezembro'), (6, 'Junho'), (7, 'Julho')]),
        ),
    ]
