# Generated by Django 4.0.1 on 2022-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0032_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (11, 'Novembro'), (7, 'Julho'), (2, 'Fevereiro'), (10, 'Outubro'), (4, 'Abril'), (12, 'Dezembro'), (9, 'Setembro'), (8, 'Agosto')]),
        ),
    ]
