# Generated by Django 4.0.1 on 2022-03-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0033_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (10, 'Outubro'), (6, 'Junho'), (1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (5, 'Maio'), (7, 'Julho')]),
        ),
    ]
