# Generated by Django 4.0.1 on 2022-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0033_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (4, 'Abril'), (10, 'Outubro'), (11, 'Novembro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (5, 'Maio'), (8, 'Agosto')]),
        ),
    ]
