# Generated by Django 4.0.1 on 2022-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0034_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (12, 'Dezembro'), (6, 'Junho'), (9, 'Setembro'), (4, 'Abril'), (8, 'Agosto'), (3, 'Março'), (11, 'Novembro'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro')]),
        ),
    ]
