# Generated by Django 4.0.1 on 2022-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0034_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro')]),
        ),
    ]
