# Generated by Django 4.0.1 on 2022-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0035_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (5, 'Maio'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (2, 'Fevereiro'), (4, 'Abril'), (9, 'Setembro'), (8, 'Agosto'), (10, 'Outubro'), (7, 'Julho')]),
        ),
    ]
