# Generated by Django 4.0.1 on 2022-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0035_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (9, 'Setembro'), (4, 'Abril'), (1, 'Janeiro'), (3, 'Março'), (2, 'Fevereiro'), (10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (11, 'Novembro')]),
        ),
    ]
