# Generated by Django 4.0.1 on 2022-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0036_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (12, 'Dezembro'), (1, 'Janeiro'), (8, 'Agosto'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (5, 'Maio'), (4, 'Abril'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
    ]
