# Generated by Django 4.0.1 on 2022-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0036_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (8, 'Agosto'), (9, 'Setembro'), (4, 'Abril'), (6, 'Junho'), (3, 'Março'), (7, 'Julho'), (1, 'Janeiro'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio')]),
        ),
    ]
