# Generated by Django 4.0.1 on 2022-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0037_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (9, 'Setembro'), (4, 'Abril'), (10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (12, 'Dezembro'), (8, 'Agosto'), (1, 'Janeiro'), (2, 'Fevereiro'), (5, 'Maio'), (11, 'Novembro')]),
        ),
    ]
