# Generated by Django 4.0.1 on 2022-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0037_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (9, 'Setembro'), (12, 'Dezembro'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
    ]
