# Generated by Django 4.0.1 on 2022-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0038_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (5, 'Maio'), (9, 'Setembro'), (2, 'Fevereiro'), (3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (11, 'Novembro')]),
        ),
    ]
