# Generated by Django 4.0.1 on 2022-03-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0038_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro'), (6, 'Junho'), (12, 'Dezembro'), (9, 'Setembro'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro')]),
        ),
    ]
