# Generated by Django 4.0.1 on 2022-03-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0039_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (7, 'Julho'), (8, 'Agosto'), (3, 'Março'), (11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (2, 'Fevereiro'), (12, 'Dezembro'), (4, 'Abril'), (10, 'Outubro')]),
        ),
    ]
