# Generated by Django 4.0.1 on 2022-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0040_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (1, 'Janeiro'), (12, 'Dezembro'), (9, 'Setembro'), (8, 'Agosto'), (10, 'Outubro'), (11, 'Novembro')]),
        ),
    ]
