# Generated by Django 4.0.1 on 2022-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0041_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março')]),
        ),
    ]
