# Generated by Django 4.0.1 on 2022-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0041_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (12, 'Dezembro'), (3, 'Março'), (8, 'Agosto'), (10, 'Outubro'), (5, 'Maio')]),
        ),
    ]
