# Generated by Django 4.0.1 on 2022-03-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0042_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (12, 'Dezembro'), (4, 'Abril'), (9, 'Setembro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (3, 'Março')]),
        ),
    ]
