# Generated by Django 4.0.1 on 2022-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0043_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (11, 'Novembro'), (8, 'Agosto'), (4, 'Abril'), (1, 'Janeiro'), (9, 'Setembro'), (3, 'Março')]),
        ),
    ]
