# Generated by Django 4.0.1 on 2022-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0045_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (7, 'Julho'), (3, 'Março'), (6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (9, 'Setembro'), (5, 'Maio'), (4, 'Abril'), (12, 'Dezembro'), (1, 'Janeiro'), (10, 'Outubro')]),
        ),
    ]
