# Generated by Django 4.0.1 on 2022-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0045_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (11, 'Novembro'), (3, 'Março'), (4, 'Abril'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (8, 'Agosto'), (6, 'Junho'), (1, 'Janeiro')]),
        ),
    ]
