# Generated by Django 4.0.1 on 2022-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0046_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (6, 'Junho'), (12, 'Dezembro')]),
        ),
    ]
