# Generated by Django 4.0.1 on 2022-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0050_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (2, 'Fevereiro'), (11, 'Novembro'), (12, 'Dezembro'), (5, 'Maio'), (7, 'Julho'), (4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro')]),
        ),
    ]
