# Generated by Django 4.0.1 on 2022-03-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0050_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (7, 'Julho'), (10, 'Outubro'), (6, 'Junho'), (9, 'Setembro'), (12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (8, 'Agosto'), (4, 'Abril'), (11, 'Novembro'), (3, 'Março')]),
        ),
    ]
