# Generated by Django 4.0.1 on 2022-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0051_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (3, 'Março'), (10, 'Outubro'), (9, 'Setembro'), (8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (2, 'Fevereiro'), (6, 'Junho'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio')]),
        ),
    ]
