# Generated by Django 4.0.1 on 2022-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0052_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (10, 'Outubro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (11, 'Novembro'), (4, 'Abril'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (1, 'Janeiro'), (6, 'Junho')]),
        ),
    ]
