# Generated by Django 4.0.1 on 2022-06-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0052_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (12, 'Dezembro'), (10, 'Outubro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho'), (1, 'Janeiro')]),
        ),
    ]
