# Generated by Django 4.0.1 on 2022-06-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0053_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro'), (11, 'Novembro'), (3, 'Março'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (9, 'Setembro')]),
        ),
    ]
