# Generated by Django 4.0.1 on 2022-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0055_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (1, 'Janeiro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (4, 'Abril')]),
        ),
    ]
