# Generated by Django 4.0.1 on 2022-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0055_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (5, 'Maio'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (1, 'Janeiro')]),
        ),
    ]
