# Generated by Django 4.0.1 on 2022-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0056_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (9, 'Setembro'), (6, 'Junho'), (11, 'Novembro'), (3, 'Março'), (2, 'Fevereiro'), (7, 'Julho'), (12, 'Dezembro'), (5, 'Maio'), (10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
    ]
