# Generated by Django 4.0.1 on 2022-03-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0056_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (11, 'Novembro'), (1, 'Janeiro'), (7, 'Julho'), (2, 'Fevereiro'), (10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (3, 'Março'), (6, 'Junho'), (9, 'Setembro'), (4, 'Abril')]),
        ),
    ]
