# Generated by Django 4.0.1 on 2022-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0057_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (11, 'Novembro'), (12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (3, 'Março'), (7, 'Julho'), (9, 'Setembro'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio'), (6, 'Junho')]),
        ),
    ]
