# Generated by Django 4.0.1 on 2022-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0057_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (8, 'Agosto'), (7, 'Julho'), (2, 'Fevereiro'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro')]),
        ),
    ]
