# Generated by Django 4.0.1 on 2022-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0060_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (8, 'Agosto'), (4, 'Abril'), (6, 'Junho'), (3, 'Março'), (12, 'Dezembro')]),
        ),
    ]
