# Generated by Django 4.0.1 on 2022-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0063_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (2, 'Fevereiro'), (10, 'Outubro'), (4, 'Abril'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro')]),
        ),
    ]
