# Generated by Django 4.0.1 on 2022-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0064_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro'), (1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (3, 'Março'), (8, 'Agosto'), (7, 'Julho')]),
        ),
    ]
