# Generated by Django 4.0.1 on 2022-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0065_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (7, 'Julho'), (3, 'Março'), (5, 'Maio'), (12, 'Dezembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (6, 'Junho'), (11, 'Novembro'), (8, 'Agosto'), (4, 'Abril'), (9, 'Setembro')]),
        ),
    ]
