# Generated by Django 4.0.1 on 2022-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0066_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (4, 'Abril'), (2, 'Fevereiro'), (11, 'Novembro'), (6, 'Junho'), (9, 'Setembro'), (10, 'Outubro'), (7, 'Julho'), (3, 'Março')]),
        ),
    ]
