# Generated by Django 4.0.1 on 2022-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0067_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (12, 'Dezembro'), (11, 'Novembro'), (8, 'Agosto'), (10, 'Outubro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (1, 'Janeiro'), (5, 'Maio')]),
        ),
    ]
