# Generated by Django 4.0.1 on 2022-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0068_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (11, 'Novembro'), (5, 'Maio'), (7, 'Julho'), (6, 'Junho'), (1, 'Janeiro'), (8, 'Agosto'), (4, 'Abril'), (2, 'Fevereiro'), (12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro')]),
        ),
    ]
