# Generated by Django 4.0.1 on 2022-07-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0068_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (12, 'Dezembro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio'), (1, 'Janeiro'), (6, 'Junho')]),
        ),
    ]
