# Generated by Django 4.0.1 on 2022-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0069_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (5, 'Maio'), (2, 'Fevereiro'), (8, 'Agosto'), (3, 'Março'), (10, 'Outubro'), (7, 'Julho'), (12, 'Dezembro'), (1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (4, 'Abril')]),
        ),
    ]
