# Generated by Django 4.0.1 on 2022-07-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0069_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (3, 'Março'), (6, 'Junho'), (4, 'Abril'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (9, 'Setembro')]),
        ),
    ]
