# Generated by Django 4.0.1 on 2022-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0071_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (7, 'Julho'), (8, 'Agosto'), (3, 'Março'), (10, 'Outubro'), (12, 'Dezembro'), (2, 'Fevereiro'), (9, 'Setembro'), (4, 'Abril'), (6, 'Junho'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
    ]
