# Generated by Django 4.0.1 on 2022-03-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0072_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio'), (2, 'Fevereiro'), (6, 'Junho'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (1, 'Janeiro')]),
        ),
    ]
