# Generated by Django 4.0.1 on 2022-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0072_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (1, 'Janeiro')]),
        ),
    ]
