# Generated by Django 4.0.1 on 2022-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0073_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro')]),
        ),
    ]
