# Generated by Django 4.0.1 on 2022-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0073_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (10, 'Outubro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (6, 'Junho'), (12, 'Dezembro'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (11, 'Novembro'), (9, 'Setembro')]),
        ),
    ]
