# Generated by Django 4.0.1 on 2022-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0074_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (2, 'Fevereiro'), (12, 'Dezembro'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho'), (4, 'Abril'), (9, 'Setembro'), (8, 'Agosto'), (5, 'Maio'), (1, 'Janeiro'), (7, 'Julho')]),
        ),
    ]
