# Generated by Django 4.0.1 on 2022-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0074_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (6, 'Junho'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
    ]
