# Generated by Django 4.0.1 on 2022-08-10 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0075_remove_escala_data_escala_check_in_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (3, 'Março'), (8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (2, 'Fevereiro'), (4, 'Abril'), (6, 'Junho'), (12, 'Dezembro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='check_in_grupo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='escala',
            name='check_out_grupo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
