# Generated by Django 4.0.1 on 2022-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0076_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (4, 'Abril'), (5, 'Maio'), (8, 'Agosto'), (10, 'Outubro'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (1, 'Janeiro'), (3, 'Março'), (6, 'Junho'), (2, 'Fevereiro')]),
        ),
    ]
