# Generated by Django 4.0.1 on 2022-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0077_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (9, 'Setembro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril')]),
        ),
    ]
