# Generated by Django 4.0.1 on 2022-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0077_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (3, 'Março'), (1, 'Janeiro'), (2, 'Fevereiro'), (6, 'Junho'), (11, 'Novembro'), (8, 'Agosto'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (7, 'Julho'), (12, 'Dezembro')]),
        ),
    ]
