# Generated by Django 4.0.1 on 2022-08-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0077_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (3, 'Março'), (5, 'Maio'), (6, 'Junho'), (12, 'Dezembro'), (11, 'Novembro'), (10, 'Outubro'), (2, 'Fevereiro'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho')]),
        ),
    ]
