# Generated by Django 4.0.1 on 2022-03-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0078_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (4, 'Abril'), (1, 'Janeiro'), (10, 'Outubro'), (9, 'Setembro'), (8, 'Agosto'), (6, 'Junho'), (12, 'Dezembro')]),
        ),
    ]
