# Generated by Django 4.0.1 on 2022-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0078_alter_disponibilidade_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
        migrations.RemoveField(
            model_name='escala',
            name='equipe',
        ),
        migrations.AddField(
            model_name='escala',
            name='equipe',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
