# Generated by Django 4.0.1 on 2022-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0078_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (2, 'Fevereiro'), (1, 'Janeiro'), (7, 'Julho'), (12, 'Dezembro'), (4, 'Abril'), (9, 'Setembro'), (5, 'Maio'), (11, 'Novembro'), (3, 'Março'), (6, 'Junho')]),
        ),
    ]
