# Generated by Django 4.0.1 on 2022-03-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0079_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (1, 'Janeiro'), (7, 'Julho'), (3, 'Março'), (9, 'Setembro'), (8, 'Agosto'), (11, 'Novembro'), (10, 'Outubro'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (12, 'Dezembro')]),
        ),
    ]
