# Generated by Django 4.0.1 on 2022-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0082_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (9, 'Setembro'), (8, 'Agosto'), (2, 'Fevereiro'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril')]),
        ),
    ]
