# Generated by Django 4.0.1 on 2022-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0083_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (12, 'Dezembro'), (4, 'Abril'), (2, 'Fevereiro'), (9, 'Setembro'), (10, 'Outubro'), (7, 'Julho'), (3, 'Março'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (5, 'Maio')]),
        ),
    ]
