# Generated by Django 4.0.1 on 2022-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0084_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (5, 'Maio'), (8, 'Agosto'), (3, 'Março'), (12, 'Dezembro'), (9, 'Setembro'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (4, 'Abril')]),
        ),
    ]
