# Generated by Django 4.0.1 on 2022-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0085_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (3, 'Março'), (1, 'Janeiro'), (9, 'Setembro'), (4, 'Abril'), (11, 'Novembro'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro')]),
        ),
    ]
