# Generated by Django 4.0.1 on 2022-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0086_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (7, 'Julho'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
    ]
