# Generated by Django 4.0.1 on 2022-03-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0088_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (6, 'Junho'), (12, 'Dezembro'), (7, 'Julho'), (3, 'Março'), (9, 'Setembro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (10, 'Outubro'), (11, 'Novembro'), (5, 'Maio')]),
        ),
    ]
