# Generated by Django 4.0.1 on 2022-03-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0089_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (10, 'Outubro'), (2, 'Fevereiro'), (9, 'Setembro'), (8, 'Agosto'), (7, 'Julho')]),
        ),
    ]
