# Generated by Django 4.0.1 on 2022-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0090_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (9, 'Setembro'), (12, 'Dezembro'), (1, 'Janeiro'), (6, 'Junho'), (3, 'Março'), (7, 'Julho'), (5, 'Maio'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro')]),
        ),
    ]
