# Generated by Django 4.0.1 on 2022-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0091_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (10, 'Outubro'), (2, 'Fevereiro'), (9, 'Setembro'), (8, 'Agosto'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (1, 'Janeiro')]),
        ),
    ]
