# Generated by Django 4.0.1 on 2022-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0094_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (12, 'Dezembro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (3, 'Março'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril')]),
        ),
    ]
