# Generated by Django 4.0.1 on 2022-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0095_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (1, 'Janeiro'), (4, 'Abril'), (11, 'Novembro'), (10, 'Outubro'), (12, 'Dezembro'), (7, 'Julho'), (3, 'Março'), (6, 'Junho'), (8, 'Agosto'), (5, 'Maio'), (2, 'Fevereiro')]),
        ),
    ]
