# Generated by Django 4.0.1 on 2022-03-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0096_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (2, 'Fevereiro'), (10, 'Outubro'), (7, 'Julho'), (6, 'Junho'), (5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (3, 'Março'), (12, 'Dezembro')]),
        ),
    ]
