# Generated by Django 4.0.1 on 2022-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0097_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (3, 'Março'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (4, 'Abril'), (11, 'Novembro'), (12, 'Dezembro'), (8, 'Agosto'), (6, 'Junho'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
    ]
