# Generated by Django 4.0.1 on 2022-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0098_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (6, 'Junho'), (11, 'Novembro'), (4, 'Abril'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro')]),
        ),
    ]
