# Generated by Django 4.0.1 on 2022-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0100_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (5, 'Maio'), (1, 'Janeiro'), (12, 'Dezembro')]),
        ),
    ]
