# Generated by Django 4.0.1 on 2022-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0101_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (4, 'Abril'), (12, 'Dezembro'), (5, 'Maio'), (8, 'Agosto'), (6, 'Junho'), (11, 'Novembro'), (2, 'Fevereiro'), (10, 'Outubro'), (7, 'Julho'), (1, 'Janeiro'), (9, 'Setembro')]),
        ),
    ]
