# Generated by Django 4.0.1 on 2022-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0102_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (10, 'Outubro'), (6, 'Junho'), (2, 'Fevereiro'), (1, 'Janeiro'), (9, 'Setembro'), (8, 'Agosto'), (5, 'Maio'), (4, 'Abril'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro')]),
        ),
    ]
