# Generated by Django 4.0.1 on 2022-03-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0103_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (5, 'Maio'), (6, 'Junho'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (10, 'Outubro'), (1, 'Janeiro'), (9, 'Setembro'), (2, 'Fevereiro')]),
        ),
    ]
