# Generated by Django 4.0.1 on 2022-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0104_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (12, 'Dezembro'), (10, 'Outubro'), (4, 'Abril'), (1, 'Janeiro'), (6, 'Junho'), (2, 'Fevereiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (11, 'Novembro'), (9, 'Setembro')]),
        ),
    ]
