# Generated by Django 4.0.1 on 2022-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0105_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (12, 'Dezembro'), (9, 'Setembro'), (2, 'Fevereiro'), (11, 'Novembro'), (3, 'Março'), (6, 'Junho'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
    ]
