# Generated by Django 4.0.1 on 2022-04-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0108_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (7, 'Julho'), (10, 'Outubro'), (12, 'Dezembro'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (4, 'Abril'), (6, 'Junho'), (5, 'Maio'), (3, 'Março')]),
        ),
    ]
