# Generated by Django 4.0.1 on 2022-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0109_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (11, 'Novembro'), (2, 'Fevereiro'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (9, 'Setembro'), (8, 'Agosto'), (3, 'Março'), (6, 'Junho'), (4, 'Abril'), (10, 'Outubro')]),
        ),
    ]
