# Generated by Django 4.0.1 on 2022-04-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0111_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (10, 'Outubro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho')]),
        ),
    ]
