# Generated by Django 4.0.1 on 2022-04-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0112_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (10, 'Outubro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (5, 'Maio'), (9, 'Setembro')]),
        ),
    ]
