# Generated by Django 4.0.1 on 2022-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0114_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (10, 'Outubro'), (1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (12, 'Dezembro')]),
        ),
    ]
