# Generated by Django 4.0.1 on 2022-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0116_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (11, 'Novembro'), (2, 'Fevereiro'), (8, 'Agosto'), (6, 'Junho'), (10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (5, 'Maio')]),
        ),
    ]
