# Generated by Django 4.0.1 on 2022-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0118_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (10, 'Outubro'), (12, 'Dezembro'), (3, 'Março'), (5, 'Maio'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (2, 'Fevereiro'), (1, 'Janeiro')]),
        ),
    ]
