# Generated by Django 4.0.1 on 2022-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0119_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (11, 'Novembro'), (2, 'Fevereiro'), (4, 'Abril'), (10, 'Outubro'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (12, 'Dezembro'), (3, 'Março'), (9, 'Setembro')]),
        ),
    ]
