# Generated by Django 4.0.1 on 2022-04-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0120_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro'), (12, 'Dezembro'), (5, 'Maio'), (7, 'Julho'), (9, 'Setembro'), (6, 'Junho'), (10, 'Outubro'), (11, 'Novembro'), (8, 'Agosto')]),
        ),
    ]
