# Generated by Django 4.0.1 on 2022-04-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0121_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (7, 'Julho'), (3, 'Março'), (6, 'Junho'), (11, 'Novembro'), (12, 'Dezembro'), (9, 'Setembro'), (5, 'Maio'), (2, 'Fevereiro'), (8, 'Agosto')]),
        ),
    ]
