# Generated by Django 4.0.1 on 2022-04-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0122_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (5, 'Maio'), (2, 'Fevereiro'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (1, 'Janeiro'), (11, 'Novembro'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (3, 'Março')]),
        ),
    ]
