# Generated by Django 4.0.1 on 2022-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0123_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (1, 'Janeiro'), (2, 'Fevereiro'), (11, 'Novembro'), (12, 'Dezembro'), (6, 'Junho'), (7, 'Julho'), (5, 'Maio'), (4, 'Abril')]),
        ),
    ]
