# Generated by Django 4.0.1 on 2022-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0125_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (9, 'Setembro'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (8, 'Agosto'), (6, 'Junho'), (7, 'Julho'), (3, 'Março'), (5, 'Maio'), (11, 'Novembro')]),
        ),
    ]
