# Generated by Django 4.0.1 on 2022-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0126_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (11, 'Novembro'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março')]),
        ),
    ]
