# Generated by Django 4.0.1 on 2022-04-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0127_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (4, 'Abril'), (3, 'Março'), (6, 'Junho'), (2, 'Fevereiro'), (5, 'Maio'), (12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
    ]
