# Generated by Django 4.0.1 on 2022-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0131_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (3, 'Março'), (2, 'Fevereiro'), (4, 'Abril'), (12, 'Dezembro'), (7, 'Julho'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (1, 'Janeiro'), (10, 'Outubro'), (11, 'Novembro')]),
        ),
    ]
