# Generated by Django 4.0.1 on 2022-04-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0132_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (11, 'Novembro'), (3, 'Março'), (9, 'Setembro'), (6, 'Junho'), (8, 'Agosto'), (2, 'Fevereiro'), (4, 'Abril')]),
        ),
    ]
