# Generated by Django 4.0.1 on 2022-04-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0133_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (9, 'Setembro'), (5, 'Maio'), (12, 'Dezembro'), (8, 'Agosto'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (10, 'Outubro'), (11, 'Novembro'), (7, 'Julho'), (2, 'Fevereiro')]),
        ),
    ]
