# Generated by Django 4.0.1 on 2022-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDeAtendimentoPublicoCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('data_atendimento', models.DateField()),
                ('equipe', models.JSONField(blank=True)),
                ('atividades', models.JSONField(blank=True)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
            ],
        ),
    ]
