# Generated by Django 4.0.1 on 2022-04-21 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peraltas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDeAtendimentoPublicoCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='Público', max_length=7)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('data_atendimento', models.DateField()),
                ('equipe', models.JSONField(blank=True)),
                ('atividades', models.JSONField(blank=True)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('data_hora_salvo', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Relatórios de atendimento ao público (CEU)',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDeAtendimentoEmpresaCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='Empresa', max_length=7)),
                ('instituicao', models.CharField(max_length=255)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('equipe', models.JSONField(blank=True)),
                ('atividades', models.JSONField(blank=True, null=True)),
                ('locacoes', models.JSONField(blank=True, null=True)),
                ('horas_totais_locacoes', models.DurationField(blank=True, null=True)),
                ('data_hora_salvo', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('coordenador_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.monitor')),
            ],
            options={
                'verbose_name_plural': 'Relatórios de atendimento à empresa (CEU)',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDeAtendimentoColegioCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='Colégio', max_length=7)),
                ('instituicao', models.CharField(max_length=255)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True)),
                ('check_out', models.DateTimeField(blank=True)),
                ('responsaveis', models.IntegerField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('equipe', models.JSONField(blank=True)),
                ('atividades', models.JSONField(blank=True)),
                ('locacoes', models.JSONField(blank=True, null=True)),
                ('horas_totais_locacoes', models.DurationField(blank=True, null=True)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('data_hora_salvo', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('entregue', models.BooleanField(default=False)),
                ('coordenador_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.monitor')),
            ],
            options={
                'verbose_name_plural': 'Relatórios de atendimento com colégio (CEU)',
            },
        ),
    ]
