# Generated by Django 3.2.9 on 2022-02-20 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Locaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrutura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('diarista', models.BooleanField(default=False)),
                ('nota', models.FloatField(default=0.0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, default=models.IntegerField(), null=True)),
                ('responsaveis', models.IntegerField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('coordenador_peraltas', models.CharField(blank=True, max_length=100)),
                ('equipe', models.JSONField()),
                ('atividades', models.JSONField()),
                ('locacoes', models.JSONField()),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('solicitado', models.BooleanField(default=False)),
                ('entregue', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
                ('numero_de_participantes', models.IntegerField()),
                ('duracao', models.DurationField()),
                ('publico', models.BooleanField(default=False)),
                ('local_da_atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='local', to='cadastro.locaveis')),
                ('nao_pode_ser_realizado', models.ManyToManyField(to='cadastro.Limitacoes')),
            ],
        ),
    ]
