# Generated by Django 4.0.1 on 2022-03-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriodeatendimentopublicoceu',
            options={'verbose_name_plural': 'Relatórios de atendimento ao público (CEU)'},
        ),
        migrations.CreateModel(
            name='RelatorioDeAtendimentoEmpresaCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('equipe', models.JSONField(blank=True)),
                ('atividades', models.JSONField(blank=True)),
                ('locacoes', models.JSONField(blank=True, null=True)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('coordenador_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.monitor')),
            ],
            options={
                'verbose_name_plural': 'Relatórios de atendimento à empresa (CEU)',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDeAtendimentoColegioCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('responsaveis', models.IntegerField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('equipe', models.JSONField(blank=True)),
                ('atividades', models.JSONField(blank=True)),
                ('locacoes', models.JSONField(blank=True, null=True)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('solicitado', models.BooleanField(default=False)),
                ('entregue', models.BooleanField(default=False)),
                ('coordenador_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.monitor')),
            ],
            options={
                'verbose_name_plural': 'Relatórios de atendimento com colégio (CEU)',
            },
        ),
    ]
