# Generated by Django 3.2.9 on 2021-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_atividade_1',
            field=models.JSONField(default=[]),
        ),
    ]
