# Generated by Django 3.2.9 on 2021-12-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='hora_atividade_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='hora_atividade_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='hora_atividade_4',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
