# Generated by Django 3.2.9 on 2021-12-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='professor_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor2', to='cadastro.professores'),
        ),
    ]
