# Generated by Django 3.2.9 on 2021-12-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_ordemdeservico_professores_atividade_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='professores_atividade_1',
            field=models.JSONField(verbose_name={'hora_atividade_1': models.TimeField(), 'professor_1': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='A1_professor_2', to='cadastro.professores')}),
        ),
    ]
