# Generated by Django 3.2.9 on 2021-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_ordemdeservico_professor_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_confirmados',
            field=models.IntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_previa',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='responsaveis',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
