# Generated by Django 4.0.1 on 2022-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_relatoriodeatendimentopublicoceu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodeatendimentocolegioceu',
            name='tipo',
            field=models.CharField(default='Colégio', max_length=7),
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentoempresaceu',
            name='tipo',
            field=models.CharField(default='Empresa', max_length=7),
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentopublicoceu',
            name='tipo',
            field=models.CharField(default='Público', max_length=7),
        ),
    ]
