# Generated by Django 3.2.9 on 2021-12-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20211201_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='atividade_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.atividades'),
        ),
    ]
