# Generated by Django 3.2.9 on 2022-02-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20220220_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemDeServico',
            new_name='RelatorioDeAtendimentoCeu',
        ),
    ]
