# Generated by Django 3.2.9 on 2021-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_ordemdeservico_professores_atividade_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='professores_atividade_1',
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='atividade_1',
            field=models.JSONField(),
        ),
    ]
