# Generated by Django 3.2.9 on 2021-12-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_ordemdeservico_atividade_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_confirmados',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_previa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='responsaveis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
