# Generated by Django 3.2.9 on 2021-12-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20211208_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='atividade_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atividade_5', to='cadastro.atividades'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='hora_atividade_5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_1_atv_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_1_atv_1', to='cadastro.professores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_1_atv_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_1_atv_2', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_1_atv_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_1_atv_3', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_1_atv_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_1_atv_4', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_1_atv_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_1_atv_5', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_2_atv_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_2_atv_1', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_2_atv_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_2_atv_2', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_2_atv_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_2_atv_3', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_2_atv_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_2_atv_4', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_2_atv_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_2_atv_5', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_3_atv_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_3_atv_1', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_3_atv_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_3_atv_2', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_3_atv_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_3_atv_3', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_3_atv_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_3_atv_4', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_3_atv_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_3_atv_5', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_4_atv_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_4_atv_1', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_4_atv_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_4_atv_2', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_4_atv_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_4_atv_3', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_4_atv_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_4_atv_4', to='cadastro.professores'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prf_4_atv_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prf_4_atv_5', to='cadastro.professores'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='atividade_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atividade_1', to='cadastro.atividades'),
        ),
    ]
