# Generated by Django 4.0.1 on 2022-02-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0002_alter_fichadeavaliacao_atividade_1_and_more'),
        ('escala', '0007_alter_disponibilidade_mes_and_more'),
        ('cadastro', '0006_remove_professores_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professores',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='relatoriodeatendimentoceu',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Atividades',
        ),
        migrations.DeleteModel(
            name='Limitacoes',
        ),
        migrations.DeleteModel(
            name='Locaveis',
        ),
        migrations.DeleteModel(
            name='Professores',
        ),
        migrations.DeleteModel(
            name='RelatorioDeAtendimentoCeu',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
