# Generated by Django 3.2.9 on 2021-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20211215_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
