# Generated by Django 4.0.1 on 2022-02-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceu', '0002_delete_relatoriodeatendimentoceu'),
        ('cadastro', '0007_remove_professores_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDeAtendimentoCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('participantes_previa', models.IntegerField()),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('responsaveis', models.IntegerField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('coordenador_peraltas', models.CharField(blank=True, max_length=100)),
                ('equipe', models.JSONField()),
                ('atividades', models.JSONField()),
                ('locacoes', models.JSONField(blank=True, null=True)),
                ('relatorio', models.TextField(default='Atividades realizadas com sucesso', max_length=400)),
                ('solicitado', models.BooleanField(default=False)),
                ('entregue', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ceu.tipo')),
            ],
        ),
    ]
