# Generated by Django 3.2.9 on 2021-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_ordemdeservico_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_confirmados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
