# Generated by Django 4.0.1 on 2022-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_relatoriodeatendimentopublicoceu_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodeatendimentopublicoceu',
            name='equipe',
            field=models.JSONField(blank=True),
        ),
    ]
