# Generated by Django 3.2.9 on 2022-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodeatendimentoceu',
            name='atividades',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentoceu',
            name='equipe',
            field=models.JSONField(blank=True),
        ),
    ]
