# Generated by Django 3.2.9 on 2021-12-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_ordemdeservico_participantes_confirmados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa_entrada_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa_entrada_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa_saida_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa_saida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa_saida_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='soma_horas_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
