# Generated by Django 4.0.1 on 2022-02-26 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20220222_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodeatendimentoceu',
            name='data_publico',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
