# Generated by Django 3.2.9 on 2021-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20211220_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='soma_horas_1',
            field=models.DurationField(),
        ),
    ]
