# Generated by Django 4.0.1 on 2022-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_relatoriodeatendimentopublicoceu_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodeatendimentopublicoceu',
            name='equipe',
            field=models.JSONField(blank=True),
        ),
    ]
