# Generated by Django 4.0.1 on 2022-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_relatoriodeatendimentopublicoceu_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodeatendimentoempresaceu',
            name='atividades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
