# Generated by Django 3.2.9 on 2021-12-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20211220_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='horas_totais',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
