# Generated by Django 4.0.1 on 2022-03-28 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_relatoriodeatendimentoempresaceu_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodeatendimentopublicoceu',
            name='data_hora_salvo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentocolegioceu',
            name='check_in',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentocolegioceu',
            name='check_out',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentocolegioceu',
            name='tipo',
            field=models.CharField(blank=True, default='Colégio', max_length=7),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentoempresaceu',
            name='tipo',
            field=models.CharField(blank=True, default='Empresa', max_length=7),
        ),
    ]
