# Generated by Django 3.2.9 on 2021-12-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_ordemdeservico_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordenador', to='cadastro.professores'),
        ),
    ]
