# Generated by Django 3.2.9 on 2022-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_ordemdeservico_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='solicitado',
            field=models.BooleanField(default=False),
        ),
    ]
