# Generated by Django 4.0.1 on 2022-03-29 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_relatoriodeatendimentocolegioceu_horas_totais_locacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodeatendimentocolegioceu',
            name='solicitado',
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentocolegioceu',
            name='data_hora_salvo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentoempresaceu',
            name='data_hora_salvo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
