# Generated by Django 4.0.1 on 2022-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_ordemdeservico_solicitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
    ]
