# Generated by Django 3.2.9 on 2022-02-06 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_professores_diarista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrutura', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_1_entrada_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_1_entrada_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_1_entrada_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_1_saida_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_1_saida_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_1_saida_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_2_entrada_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_2_entrada_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_2_entrada_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_2_saida_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_2_saida_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_2_saida_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_3_entrada_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_3_entrada_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_3_entrada_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_3_saida_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_3_saida_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividade_3_saida_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_1_atv_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_1_atv_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_1_atv_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_1_atv_4',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_1_atv_5',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_2_atv_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_2_atv_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_2_atv_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_2_atv_4',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_2_atv_5',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_3_atv_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_3_atv_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_3_atv_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_3_atv_4',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_3_atv_5',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_4_atv_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_4_atv_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_4_atv_3',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_4_atv_4',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='prf_4_atv_5',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='horarios_locacao_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='horarios_locacao_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='horarios_locacao_3',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_atividade_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_atividade_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_atividade_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_atividade_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_atividade_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_locacao_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_locacao_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='professores_locacao_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professores',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='atividade_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atividade_1', to='cadastro.atividades'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='hora_atividade_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='locacao_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locacao_1', to='cadastro.locaveis'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='locacao_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locacao_2', to='cadastro.locaveis'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='locacao_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locacao_3', to='cadastro.locaveis'),
        ),
    ]
