# Generated by Django 4.0.1 on 2022-02-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_alter_ordemdeservico_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='coordenador',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001C21509EAA0>', on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordenador', to='cadastro.professores'),
        ),
    ]
