# Generated by Django 4.0.1 on 2022-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_atividades_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_atendimento',
            field=models.DateField(),
        ),
    ]
