# Generated by Django 4.0.1 on 2022-02-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_alter_ordemdeservico_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_previa',
            field=models.IntegerField(max_length=10),
        ),
    ]
