# Generated by Django 4.0.1 on 2022-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_alter_ordemdeservico_participantes_previa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_atendimento',
            field=models.DateField(max_length=100),
        ),
    ]
