# Generated by Django 4.0.1 on 2022-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0028_alter_ordemdeservico_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_atendimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='participantes_previa',
            field=models.IntegerField(),
        ),
    ]
