# Generated by Django 4.0.1 on 2022-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0030_alter_ordemdeservico_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='horarios_locacao_1',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='horarios_locacao_2',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='horarios_locacao_3',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_1_locacao_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_1_locacao_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_1_locacao_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_2_locacao_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_2_locacao_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_2_locacao_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_3_locacao_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_3_locacao_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada_3_locacao_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_1_locacao_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_1_locacao_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_1_locacao_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_2_locacao_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_2_locacao_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_2_locacao_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_3_locacao_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_3_locacao_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='saida_3_locacao_3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
