# Generated by Django 4.0.1 on 2022-04-21 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDeAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(blank=True, max_length=400, null=True)),
                ('cidade', models.CharField(max_length=300)),
                ('n_alunos', models.IntegerField()),
                ('n_educadores', models.IntegerField()),
                ('serie', models.CharField(max_length=300)),
                ('nome_educador_1', models.CharField(max_length=400)),
                ('cargo_educador_1', models.CharField(max_length=400)),
                ('email_educador_1', models.EmailField(max_length=254)),
                ('nome_educador_2', models.CharField(blank=True, max_length=400, null=True)),
                ('cargo_educador_2', models.CharField(blank=True, max_length=400, null=True)),
                ('email_educador_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_vendedor', models.CharField(blank=True, max_length=400, null=True)),
                ('avaliacao_vendedor', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('justificativa_avaliacao_vendedor', models.TextField(blank=True, max_length=300)),
                ('data_atividade_1', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('avaliacao_atividade_1', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')])),
                ('data_atividade_2', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_2', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('data_atividade_3', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_3', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('data_atividade_4', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_4', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('data_atividade_5', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_5', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('data_atividade_6', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_6', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('data_atividade_7', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_7', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('data_atividade_8', models.DateField(blank=True, null=True)),
                ('avaliacao_atividade_8', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('justificativa_avaliacao_atividades', models.TextField(blank=True, max_length=400)),
                ('avaliacao_professor_1', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('avaliacao_professor_2', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('avaliacao_professor_3', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('avaliacao_professor_4', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('avaliacao_professor_5', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('avaliacao_professor_6', models.IntegerField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True)),
                ('justificativa_avaliacao_professores', models.TextField(blank=True, max_length=400)),
                ('motivo_trazer_grupo', models.TextField(blank=True, max_length=400)),
                ('avaliacao_conteudo_pedagogico', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')])),
                ('limpeza_instalacoes', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')])),
                ('estado_jardim', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')])),
                ('observacoes', models.TextField(blank=True, max_length=400)),
                ('data_preenchimento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('atividade_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_1', to='ceu.atividades')),
                ('atividade_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_2', to='ceu.atividades')),
                ('atividade_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_3', to='ceu.atividades')),
                ('atividade_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_4', to='ceu.atividades')),
                ('atividade_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_5', to='ceu.atividades')),
                ('atividade_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_6', to='ceu.atividades')),
                ('atividade_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_7', to='ceu.atividades')),
                ('atividade_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_8', to='ceu.atividades')),
                ('professor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_1', to='ceu.professores')),
                ('professor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_2', to='ceu.professores')),
                ('professor_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_3', to='ceu.professores')),
                ('professor_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_4', to='ceu.professores')),
                ('professor_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_5', to='ceu.professores')),
                ('professor_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_6', to='ceu.professores')),
            ],
        ),
    ]
