# Generated by Django 4.0.1 on 2022-04-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0002_monitor_n_avaliacoes_vendedor_n_avaliacoes'),
        ('fichaAvaliacao', '0003_fichadeavaliacao_estado_conservacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio'),
        ),
    ]
