# Generated by Django 4.0.1 on 2022-11-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0004_alter_fichadeavaliacao_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_vendedor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
