# Generated by Django 4.0.1 on 2023-10-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0025_auto_20231020_2158'),
        ('fichaAvaliacao', '0005_alter_fichadeavaliacao_avaliacao_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeavaliacao',
            name='ordem_de_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ordemDeServico.ordemdeservico'),
            preserve_default=False,
        ),
    ]
