# Generated by Django 4.0.1 on 2024-08-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0176_alter_eventos_colaborador_and_more'),
        ('fichaAvaliacao', '0006_fichadeavaliacao_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.clientecolegio'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='nome_avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.responsavel'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='nome_vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peraltas.vendedor'),
        ),
    ]
