# Generated by Django 4.0.1 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0007_alter_fichadeavaliacao_instituicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeavaliacao',
            name='motivo_nao_respondido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichadeavaliacao',
            name='nao_respondido',
            field=models.BooleanField(default=False),
        ),
    ]
