# Generated by Django 4.0.1 on 2025-07-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0008_fichadeavaliacao_motivo_nao_respondido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeavaliacao',
            name='motivo_nao_respondido',
        ),
        migrations.RemoveField(
            model_name='fichadeavaliacao',
            name='nao_respondido',
        ),
    ]
