# Generated by Django 4.0.1 on 2022-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0006_reembolsosprofessores'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolsosprofessores',
            name='valores',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
