# Generated by Django 4.0.1 on 2022-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0017_alter_reembolsosprofessores_comprovante_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolsosprofessores',
            name='comprovante_reembolso',
            field=models.FileField(upload_to='comprovantes/<function ReembolsosProfessores.nome_completo at 0x0000015011251240>/%Y/%m'),
        ),
    ]
