# Generated by Django 4.0.1 on 2022-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0018_alter_reembolsosprofessores_comprovante_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolsosprofessores',
            name='comprovante_reembolso',
            field=models.FileField(upload_to='comprovantes/<function ReembolsosProfessores.__str__ at 0x000001FE3F741240>/%Y/%m'),
        ),
    ]
