# Generated by Django 4.0.1 on 2022-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0022_alter_atividades_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='limitacao',
            field=models.ManyToManyField(blank=True, to='ceu.Limitacoes'),
        ),
    ]
