# Generated by Django 4.0.1 on 2022-09-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0024_detectordebombas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectordebombas',
            name='mostrar',
        ),
    ]
