# Generated by Django 4.0.1 on 2022-09-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0025_remove_detectordebombas_mostrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectorDeBombas',
        ),
    ]
