# Generated by Django 4.0.1 on 2023-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0026_delete_detectordebombas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
