# Generated by Django 4.0.1 on 2024-03-24 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0165_tipoaividadeperaltas_atividadeseco_serie_and_more'),
        ('ceu', '0027_atividades_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividadesCeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(max_length=255, verbose_name='Tipo de Atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividades',
            name='serie',
            field=models.ManyToManyField(blank=True, to='peraltas.PerfilsParticipantes'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='tipo_pacote',
            field=models.ManyToManyField(blank=True, to='peraltas.ProdutosPeraltas'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='tipo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ceu.tipoatividadesceu'),
        ),
    ]
