# Generated by Django 4.0.1 on 2025-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0027_atividades_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='a_definir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividades',
            name='sem_atividade',
            field=models.BooleanField(default=False),
        ),
    ]
