# Generated by Django 4.0.1 on 2024-04-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0028_tipoatividadesceu_atividades_serie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='tipo_atividade',
            new_name='tema_atividade',
        ),
    ]
