# Generated by Django 4.0.1 on 2024-05-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0168_disciplinas_intencaoatividade_and_more'),
        ('ceu', '0029_rename_tipo_atividade_atividades_tema_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='tema_atividade',
        ),
        migrations.AddField(
            model_name='atividades',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='peraltas.Disciplinas'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='intencao_atividade',
            field=models.ManyToManyField(blank=True, to='peraltas.IntencaoAtividade'),
        ),
        migrations.DeleteModel(
            name='TipoAtividadesCeu',
        ),
    ]
