# Generated by Django 4.0.1 on 2024-05-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0169_remove_atividadeseco_disciplinas_and_more'),
        ('ceu', '0030_remove_atividades_tema_atividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='atividades',
            name='disciplina_primaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disciplina_primaria_ceu', to='peraltas.disciplinas', verbose_name='Disciplina Primaria'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='disciplinas_secundarias',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_secundarias_ceu', to='peraltas.Disciplinas', verbose_name='Disciplnas secundárias'),
        ),
    ]
