# Generated by Django 4.0.1 on 2024-05-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0031_remove_atividades_disciplinas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='disciplinas_secundarias',
            new_name='disciplinas',
        ),
    ]
