# Generated by Django 4.0.1 on 2024-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0172_alter_atividadeseco_disciplinas'),
        ('ceu', '0032_rename_disciplinas_secundarias_atividades_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_secundarias_ceu', to='peraltas.Disciplinas', verbose_name='Disciplnas trabalhadas'),
        ),
    ]
