# Generated by Django 4.0.1 on 2025-02-05 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remetente', models.CharField(blank=True, help_text='Salva o nome do remetente no caso do usuário ser excluido', max_length=100, null=True)),
                ('nome_destinatario', models.CharField(blank=True, help_text='Salva o nome do destinatário no caso do usuário ser excluido', max_length=100, null=True)),
                ('conteudo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='mensagens/arquivos/')),
                ('data_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('data_hora_leitura', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remetente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
