# Generated by Django 4.0.1 on 2022-04-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (1, 'Janeiro'), (7, 'Julho'), (10, 'Outubro'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (8, 'Agosto'), (12, 'Dezembro'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março')]),
        ),
    ]
