# Generated by Django 4.0.1 on 2022-04-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro'), (10, 'Outubro'), (4, 'Abril'), (9, 'Setembro'), (1, 'Janeiro'), (5, 'Maio'), (8, 'Agosto'), (6, 'Junho')]),
        ),
    ]
