# Generated by Django 4.0.1 on 2022-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0006_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (2, 'Fevereiro'), (8, 'Agosto'), (9, 'Setembro'), (12, 'Dezembro'), (1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (11, 'Novembro'), (4, 'Abril')]),
        ),
    ]
