# Generated by Django 4.0.1 on 2022-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0008_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (10, 'Outubro'), (4, 'Abril'), (11, 'Novembro'), (5, 'Maio'), (6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (2, 'Fevereiro'), (8, 'Agosto'), (1, 'Janeiro'), (7, 'Julho')]),
        ),
    ]
