# Generated by Django 4.0.1 on 2022-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0010_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (5, 'Maio'), (1, 'Janeiro'), (2, 'Fevereiro'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
    ]
