# Generated by Django 4.0.1 on 2022-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0011_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (3, 'Março'), (5, 'Maio'), (12, 'Dezembro'), (2, 'Fevereiro'), (6, 'Junho'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril')]),
        ),
    ]
