# Generated by Django 4.0.1 on 2022-04-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0024_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (10, 'Outubro'), (7, 'Julho'), (3, 'Março'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (2, 'Fevereiro'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
    ]
