# Generated by Django 4.0.1 on 2022-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0030_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (7, 'Julho'), (12, 'Dezembro'), (4, 'Abril'), (10, 'Outubro'), (9, 'Setembro'), (2, 'Fevereiro'), (6, 'Junho'), (1, 'Janeiro'), (3, 'Março'), (5, 'Maio'), (8, 'Agosto')]),
        ),
    ]
