# Generated by Django 4.0.1 on 2022-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0033_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (12, 'Dezembro'), (8, 'Agosto'), (10, 'Outubro'), (4, 'Abril'), (3, 'Março'), (5, 'Maio'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (6, 'Junho')]),
        ),
    ]
