# Generated by Django 4.0.1 on 2022-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0039_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (3, 'Março'), (5, 'Maio'), (8, 'Agosto'), (7, 'Julho'), (12, 'Dezembro'), (9, 'Setembro'), (2, 'Fevereiro'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril')]),
        ),
    ]
