# Generated by Django 4.0.1 on 2022-05-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0043_dialimite_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (6, 'Junho'), (9, 'Setembro'), (4, 'Abril'), (10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto'), (5, 'Maio')]),
        ),
    ]
