# Generated by Django 4.0.1 on 2022-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0044_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro'), (5, 'Maio')]),
        ),
    ]
