# Generated by Django 4.0.1 on 2022-05-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0046_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (7, 'Julho'), (5, 'Maio'), (1, 'Janeiro'), (11, 'Novembro'), (12, 'Dezembro'), (8, 'Agosto'), (9, 'Setembro'), (4, 'Abril'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
    ]
