# Generated by Django 4.0.1 on 2022-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0048_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (5, 'Maio'), (3, 'Março'), (9, 'Setembro'), (6, 'Junho'), (10, 'Outubro'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (7, 'Julho')]),
        ),
    ]
