# Generated by Django 4.0.1 on 2022-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0049_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (1, 'Janeiro'), (10, 'Outubro'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (5, 'Maio')]),
        ),
    ]
