# Generated by Django 4.0.1 on 2022-06-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0054_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (8, 'Agosto'), (9, 'Setembro'), (11, 'Novembro'), (12, 'Dezembro'), (1, 'Janeiro'), (3, 'Março')]),
        ),
    ]
