# Generated by Django 4.0.1 on 2022-06-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0058_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (8, 'Agosto'), (7, 'Julho'), (4, 'Abril'), (9, 'Setembro'), (6, 'Junho'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (11, 'Novembro'), (5, 'Maio')]),
        ),
    ]
