# Generated by Django 4.0.1 on 2022-07-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0061_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (8, 'Agosto'), (10, 'Outubro'), (7, 'Julho'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (4, 'Abril')]),
        ),
    ]
