# Generated by Django 4.0.1 on 2022-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0065_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (5, 'Maio'), (4, 'Abril'), (6, 'Junho'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho')]),
        ),
    ]
