# Generated by Django 4.0.1 on 2022-07-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0066_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (5, 'Maio'), (7, 'Julho'), (8, 'Agosto'), (6, 'Junho'), (4, 'Abril'), (3, 'Março')]),
        ),
    ]
