# Generated by Django 4.0.1 on 2022-07-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0070_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
    ]
