# Generated by Django 4.0.1 on 2022-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0071_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (3, 'Março'), (12, 'Dezembro'), (2, 'Fevereiro')]),
        ),
    ]
