# Generated by Django 4.0.1 on 2022-08-10 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0038_alter_disponibilidadeacampamento_mes_and_more'),
        ('escala', '0074_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='data',
        ),
        migrations.AddField(
            model_name='escala',
            name='check_in_grupo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='escala',
            name='check_out_grupo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='escala',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
        ),
        migrations.AddField(
            model_name='escala',
            name='tipo_escala',
            field=models.IntegerField(choices=[(1, 'Público'), (2, 'Grupo')], default=1),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (3, 'Março'), (2, 'Fevereiro'), (9, 'Setembro'), (10, 'Outubro'), (6, 'Junho'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='equipe',
            field=models.JSONField(),
        ),
    ]
