# Generated by Django 4.0.1 on 2022-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0023_alter_atividades_limitacao'),
        ('escala', '0076_alter_disponibilidade_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.RemoveField(
            model_name='escala',
            name='equipe',
        ),
        migrations.AddField(
            model_name='escala',
            name='equipe',
            field=models.ManyToManyField(to='ceu.Professores'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='tipo_escala',
            field=models.IntegerField(choices=[(0, ''), (1, 'Público'), (2, 'Grupo')], default=0),
        ),
    ]
