# Generated by Django 4.0.1 on 2022-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0077_alter_disponibilidade_mes_remove_escala_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (12, 'Dezembro'), (3, 'Março'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='check_in_grupo',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='check_out_grupo',
            field=models.DateTimeField(blank=True),
        ),
    ]
