# Generated by Django 4.0.1 on 2022-08-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0079_alter_disponibilidade_mes_remove_escala_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (11, 'Novembro'), (8, 'Agosto'), (6, 'Junho'), (12, 'Dezembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (9, 'Setembro')]),
        ),
    ]
