# Generated by Django 4.0.1 on 2022-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0080_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (4, 'Abril'), (11, 'Novembro'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho')]),
        ),
    ]
