# Generated by Django 4.0.1 on 2022-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0081_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='check_in_grupo',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='check_out_grupo',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='tipo_escala',
        ),
        migrations.AddField(
            model_name='escala',
            name='data_escala',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (9, 'Setembro'), (11, 'Novembro'), (2, 'Fevereiro'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (6, 'Junho'), (3, 'Março'), (8, 'Agosto'), (10, 'Outubro'), (5, 'Maio')]),
        ),
    ]
