# Generated by Django 4.0.1 on 2022-08-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0082_remove_escala_check_in_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='ano',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (9, 'Setembro'), (11, 'Novembro')], default=9),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
    ]
