# Generated by Django 4.0.1 on 2022-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0083_escala_ano_escala_mes_alter_disponibilidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (5, 'Maio')], default=10),
        ),
    ]
