# Generated by Django 4.0.1 on 2022-09-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0084_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (8, 'Agosto'), (7, 'Julho'), (4, 'Abril'), (1, 'Janeiro'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (8, 'Agosto'), (7, 'Julho'), (4, 'Abril'), (1, 'Janeiro'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (11, 'Novembro')], default=10),
        ),
    ]
