# Generated by Django 4.0.1 on 2022-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0085_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (11, 'Novembro'), (5, 'Maio'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (11, 'Novembro'), (5, 'Maio'), (9, 'Setembro')], default=10),
        ),
    ]
