# Generated by Django 4.0.1 on 2022-10-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0086_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (12, 'Dezembro'), (7, 'Julho'), (9, 'Setembro'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (10, 'Outubro'), (8, 'Agosto'), (3, 'Março'), (4, 'Abril'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (12, 'Dezembro'), (7, 'Julho'), (9, 'Setembro'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (10, 'Outubro'), (8, 'Agosto'), (3, 'Março'), (4, 'Abril'), (2, 'Fevereiro')], default=11),
        ),
    ]
