# Generated by Django 4.0.1 on 2022-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0087_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (4, 'Abril'), (2, 'Fevereiro'), (6, 'Junho'), (5, 'Maio'), (8, 'Agosto'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (4, 'Abril'), (2, 'Fevereiro'), (6, 'Junho'), (5, 'Maio'), (8, 'Agosto'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (11, 'Novembro')], default=11),
        ),
    ]
