# Generated by Django 4.0.1 on 2022-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0089_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (1, 'Janeiro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (1, 'Janeiro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho')], default=12),
        ),
    ]
