# Generated by Django 4.0.1 on 2022-11-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0090_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro')], default=12),
        ),
    ]
