# Generated by Django 4.0.1 on 2022-11-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0091_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (3, 'Março')], default=12),
        ),
    ]
