# Generated by Django 4.0.1 on 2022-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0092_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (10, 'Outubro'), (8, 'Agosto'), (3, 'Março'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (10, 'Outubro'), (8, 'Agosto'), (3, 'Março'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro')], default=12),
        ),
    ]
