# Generated by Django 4.0.1 on 2022-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0093_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (11, 'Novembro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (11, 'Novembro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro')], default=12),
        ),
    ]
