# Generated by Django 4.0.1 on 2022-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0094_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (11, 'Novembro'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (10, 'Outubro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (11, 'Novembro'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (10, 'Outubro'), (2, 'Fevereiro'), (7, 'Julho')], default=12),
        ),
    ]
