# Generated by Django 4.0.1 on 2022-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0095_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (12, 'Dezembro'), (5, 'Maio'), (8, 'Agosto'), (3, 'Março'), (11, 'Novembro'), (6, 'Junho'), (1, 'Janeiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (12, 'Dezembro'), (5, 'Maio'), (8, 'Agosto'), (3, 'Março'), (11, 'Novembro'), (6, 'Junho'), (1, 'Janeiro'), (10, 'Outubro')], default=12),
        ),
    ]
