# Generated by Django 4.0.1 on 2022-11-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0096_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (5, 'Maio'), (10, 'Outubro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (1, 'Janeiro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (5, 'Maio'), (10, 'Outubro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (1, 'Janeiro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (2, 'Fevereiro')], default=12),
        ),
    ]
