# Generated by Django 4.0.1 on 2022-11-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0097_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (6, 'Junho'), (3, 'Março'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (6, 'Junho'), (3, 'Março'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (7, 'Julho')], default=12),
        ),
    ]
