# Generated by Django 4.0.1 on 2022-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0099_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (7, 'Julho'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março'), (12, 'Dezembro'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro'), (10, 'Outubro'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (7, 'Julho'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março'), (12, 'Dezembro'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro'), (10, 'Outubro'), (6, 'Junho')], default=12),
        ),
    ]
