# Generated by Django 4.0.1 on 2022-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0100_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (9, 'Setembro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (6, 'Junho'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (9, 'Setembro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (6, 'Junho'), (11, 'Novembro')], default=12),
        ),
    ]
