# Generated by Django 4.0.1 on 2022-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0101_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro')], default=12),
        ),
    ]
