# Generated by Django 4.0.1 on 2022-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0102_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro'), (8, 'Agosto'), (1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro'), (8, 'Agosto'), (1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (6, 'Junho')], default=12),
        ),
    ]
