# Generated by Django 4.0.1 on 2022-11-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0103_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto'), (11, 'Novembro'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto'), (11, 'Novembro'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro')], default=12),
        ),
    ]
