# Generated by Django 4.0.1 on 2022-11-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0104_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro'), (8, 'Agosto'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (10, 'Outubro'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro'), (8, 'Agosto'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (10, 'Outubro'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio')], default=12),
        ),
    ]
