# Generated by Django 4.0.1 on 2022-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0105_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (2, 'Fevereiro'), (10, 'Outubro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (2, 'Fevereiro'), (10, 'Outubro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio')], default=12),
        ),
    ]
