# Generated by Django 4.0.1 on 2022-11-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0108_alter_disponibilidade_mes_alter_escala_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (4, 'Abril'), (10, 'Outubro'), (5, 'Maio'), (6, 'Junho'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (4, 'Abril'), (10, 'Outubro'), (5, 'Maio'), (6, 'Junho'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
    ]
