# Generated by Django 4.0.1 on 2022-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0109_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (12, 'Dezembro'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (12, 'Dezembro'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (8, 'Agosto')]),
        ),
    ]
