# Generated by Django 4.0.1 on 2022-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0110_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (6, 'Junho'), (12, 'Dezembro'), (9, 'Setembro'), (4, 'Abril'), (5, 'Maio'), (11, 'Novembro'), (3, 'Março'), (7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (6, 'Junho'), (12, 'Dezembro'), (9, 'Setembro'), (4, 'Abril'), (5, 'Maio'), (11, 'Novembro'), (3, 'Março'), (7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro')]),
        ),
    ]
