# Generated by Django 4.0.1 on 2022-12-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0111_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio')]),
        ),
    ]
