# Generated by Django 4.0.1 on 2022-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0112_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio')]),
        ),
    ]
