# Generated by Django 4.0.1 on 2022-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0113_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro')]),
        ),
    ]
