# Generated by Django 4.0.1 on 2022-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0114_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho')]),
        ),
    ]
