# Generated by Django 4.0.1 on 2022-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0115_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (4, 'Abril')]),
        ),
    ]
