# Generated by Django 4.0.1 on 2022-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0116_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (5, 'Maio'), (3, 'Março'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (5, 'Maio'), (3, 'Março'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro')]),
        ),
    ]
