# Generated by Django 4.0.1 on 2022-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0117_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (7, 'Julho'), (12, 'Dezembro'), (2, 'Fevereiro'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (7, 'Julho'), (12, 'Dezembro'), (2, 'Fevereiro'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março'), (11, 'Novembro')]),
        ),
    ]
