# Generated by Django 4.0.1 on 2022-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0118_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro')]),
        ),
    ]
