# Generated by Django 4.0.1 on 2022-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0119_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro'), (2, 'Fevereiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro'), (2, 'Fevereiro'), (3, 'Março')]),
        ),
    ]
