# Generated by Django 4.0.1 on 2022-12-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0120_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (10, 'Outubro'), (4, 'Abril'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (10, 'Outubro'), (4, 'Abril'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março')]),
        ),
    ]
