# Generated by Django 4.0.1 on 2022-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0121_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (2, 'Fevereiro'), (11, 'Novembro'), (1, 'Janeiro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (2, 'Fevereiro'), (11, 'Novembro'), (1, 'Janeiro'), (5, 'Maio')]),
        ),
    ]
