# Generated by Django 4.0.1 on 2022-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0123_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (11, 'Novembro'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (11, 'Novembro'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (3, 'Março')]),
        ),
    ]
