# Generated by Django 4.0.1 on 2022-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0124_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (12, 'Dezembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (12, 'Dezembro')]),
        ),
    ]
