# Generated by Django 4.0.1 on 2022-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0125_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (10, 'Outubro'), (12, 'Dezembro'), (2, 'Fevereiro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (10, 'Outubro'), (12, 'Dezembro'), (2, 'Fevereiro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (5, 'Maio')]),
        ),
    ]
