# Generated by Django 4.0.1 on 2022-12-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0127_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (9, 'Setembro'), (6, 'Junho'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (9, 'Setembro'), (6, 'Junho'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto')]),
        ),
    ]
