# Generated by Django 4.0.1 on 2022-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0128_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (3, 'Março'), (11, 'Novembro'), (8, 'Agosto'), (9, 'Setembro'), (2, 'Fevereiro'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (1, 'Janeiro'), (4, 'Abril'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (3, 'Março'), (11, 'Novembro'), (8, 'Agosto'), (9, 'Setembro'), (2, 'Fevereiro'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (1, 'Janeiro'), (4, 'Abril'), (6, 'Junho')]),
        ),
    ]
