# Generated by Django 4.0.1 on 2022-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0129_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (2, 'Fevereiro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (2, 'Fevereiro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto')]),
        ),
    ]
