# Generated by Django 4.0.1 on 2022-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0130_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (11, 'Novembro'), (2, 'Fevereiro'), (8, 'Agosto'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (11, 'Novembro'), (2, 'Fevereiro'), (8, 'Agosto'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro')]),
        ),
    ]
