# Generated by Django 4.0.1 on 2022-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0131_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (8, 'Agosto')]),
        ),
    ]
