# Generated by Django 4.0.1 on 2022-12-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0132_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (12, 'Dezembro'), (11, 'Novembro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (12, 'Dezembro'), (11, 'Novembro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
    ]
