# Generated by Django 4.0.1 on 2022-12-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0133_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
    ]
