# Generated by Django 4.0.1 on 2022-12-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0134_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
    ]
