# Generated by Django 4.0.1 on 2022-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0135_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (7, 'Julho'), (1, 'Janeiro'), (12, 'Dezembro'), (2, 'Fevereiro'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (3, 'Março'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (7, 'Julho'), (1, 'Janeiro'), (12, 'Dezembro'), (2, 'Fevereiro'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (3, 'Março'), (10, 'Outubro')]),
        ),
    ]
