# Generated by Django 4.0.1 on 2022-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0136_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (5, 'Maio'), (4, 'Abril'), (7, 'Julho'), (11, 'Novembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (5, 'Maio'), (4, 'Abril'), (7, 'Julho'), (11, 'Novembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (10, 'Outubro')]),
        ),
    ]
