# Generated by Django 4.0.1 on 2022-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0137_alter_disponibilidade_mes_alter_escala_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (2, 'Fevereiro'), (8, 'Agosto'), (4, 'Abril'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (2, 'Fevereiro'), (8, 'Agosto'), (4, 'Abril'), (10, 'Outubro')]),
        ),
    ]
