# Generated by Django 3.2.9 on 2022-01-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeavaliacao',
            name='justificativa_avaliacao_vendedor',
        ),
    ]
