# Generated by Django 4.0.1 on 2022-02-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0001_initial'),
        ('fichaAvaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_1', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_2', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_3', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_4', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_5', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_6', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_7', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='atividade_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_8', to='ceu.atividades'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='professor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_1', to='ceu.professores'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='professor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_2', to='ceu.professores'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='professor_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_3', to='ceu.professores'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='professor_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_4', to='ceu.professores'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='professor_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_5', to='ceu.professores'),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='professor_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_professor_6', to='ceu.professores'),
        ),
    ]
