# Generated by Django 4.0.1 on 2022-01-14 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='data_preenchimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
