# Generated by Django 3.2.9 on 2022-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0003_fichadeavaliacao_justificativa_avaliacao_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_1',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_2',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_3',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_4',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_5',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_7',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_8',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_conteudo_pedagogico',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_1',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_2',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_3',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_4',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_5',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_6',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_vendedor',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='estado_jardim',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='limpeza_instalacoes',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10),
        ),
    ]
