# Generated by Django 4.0.1 on 2022-01-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0003_alter_fichadeavaliacao_atividade_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='justificativa_avaliacao_atividades',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='justificativa_avaliacao_professores',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='justificativa_avaliacao_vendedor',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='motivo_trazer_grupo',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='observacoes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
