# Generated by Django 4.0.1 on 2022-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0004_alter_fichadeavaliacao_justificativa_avaliacao_atividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_1',
            field=models.IntegerField(choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_2',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_3',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_4',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_5',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_6',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_7',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_8',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_conteudo_pedagogico',
            field=models.IntegerField(choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_1',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_2',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_3',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_4',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_5',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_professor_6',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_vendedor',
            field=models.IntegerField(blank=True, choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='estado_jardim',
            field=models.IntegerField(choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='limpeza_instalacoes',
            field=models.IntegerField(choices=[('', ''), (5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')]),
        ),
    ]
