# Generated by Django 3.2.9 on 2022-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0005_auto_20220111_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='data_atividade_1',
            field=models.DateTimeField(),
        ),
    ]
