# Generated by Django 4.0.1 on 2022-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0005_alter_fichadeavaliacao_avaliacao_atividade_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='n_alunos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='n_educadores',
            field=models.IntegerField(),
        ),
    ]
