# Generated by Django 3.2.9 on 2022-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0007_alter_fichadeavaliacao_avaliacao_atividade_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_1',
            field=models.CharField(choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], default=' Avaliação ', max_length=10),
        ),
    ]
