# Generated by Django 3.2.9 on 2022-01-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_ordemdeservico_solicitado'),
        ('fichaAvaliacao', '0009_alter_fichadeavaliacao_avaliacao_atividade_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeavaliacao',
            name='atividade_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacao_atividade_6', to='cadastro.atividades'),
        ),
        migrations.AddField(
            model_name='fichadeavaliacao',
            name='avaliacao_atividade_6',
            field=models.CharField(blank=True, choices=[(5, 'Excelente'), (4, 'Ótimo'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fichadeavaliacao',
            name='data_atividade_6',
            field=models.DateField(blank=True, null=True),
        ),
    ]
