# Generated by Django 3.2.9 on 2022-01-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0010_auto_20220111_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='data_preenchimento',
            field=models.TextField(),
        ),
    ]
