# Generated by Django 3.2.9 on 2022-01-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0015_auto_20220112_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='n_alunos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='n_educadores',
            field=models.IntegerField(),
        ),
    ]
