# Generated by Django 3.2.9 on 2022-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0018_auto_20220112_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='n_alunos',
            field=models.IntegerField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='n_educadores',
            field=models.IntegerField(default='', max_length=200),
        ),
    ]
