# Generated by Django 3.2.9 on 2022-01-12 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaAvaliacao', '0022_alter_fichadeavaliacao_data_atividade_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeavaliacao',
            name='data_preenchimento',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 1, 4, 33, 525092)),
        ),
    ]
