# Generated by Django 4.0.1 on 2025-05-03 22:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peraltas', '0191_produtocorporativo_brotas_eco'),
        ('ordemDeServico', '0028_ordemdeservico_observacoes_ficha_de_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenacaoAvaliandoMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_resposta', models.DateTimeField(auto_now_add=True)),
                ('observacoes_equipe', models.TextField()),
                ('captou_orientacoes', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')])),
                ('captou_orientacoes_obs', models.TextField(blank=True)),
                ('pontualidade_chegada', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('pontualidade_chegada_obs', models.TextField(blank=True)),
                ('pontualidade_atividades', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('pontualidade_atividades_obs', models.TextField(blank=True)),
                ('programacao_aplicada', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('programacao_aplicada_obs', models.TextField(blank=True)),
                ('seguiu_programacao', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('seguiu_programacao_obs', models.TextField(blank=True)),
                ('cuidados_materiais', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('cuidados_materiais_obs', models.TextField(blank=True)),
                ('iniciativa_empenho', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')])),
                ('iniciativa_empenho_obs', models.TextField(blank=True)),
                ('palavras_descricao', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escala_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorAvaliandoCoordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_resposta', models.DateTimeField(auto_now_add=True)),
                ('pontualidade_chegada', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('pontualidade_chegada_obs', models.TextField(blank=True)),
                ('pontualidade_atividades', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('pontualidade_atividades_obs', models.TextField(blank=True)),
                ('cuidados_materiais', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('cuidados_materiais_obs', models.TextField(blank=True)),
                ('desenvoltura_equipe', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('desenvoltura_equipe_obs', models.TextField(blank=True)),
                ('organizacao_evento', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('organizacao_evento_obs', models.TextField(blank=True)),
                ('programacao_aplicada', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('programacao_aplicada_obs', models.TextField(blank=True)),
                ('seguiu_programacao', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('seguiu_programacao_obs', models.TextField(blank=True)),
                ('teve_briefing', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')])),
                ('briefing_obs', models.TextField(blank=True)),
                ('teve_feedback', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')])),
                ('feedback_obs', models.TextField(blank=True)),
                ('coordenador_participou', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')])),
                ('participacao_obs', models.TextField(blank=True)),
                ('tem_consideracoes_pedagogicas', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')])),
                ('consideracoes_pedagogicas', models.TextField(blank=True)),
                ('palavras_chave', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5)),
                ('escala_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordemDeServico.ordemdeservico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestaqueAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisasSatisfacao.coordenacaoavaliandomonitoria')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor')),
            ],
            options={
                'ordering': ['posicao'],
                'unique_together': {('avaliacao', 'monitor')},
            },
        ),
        migrations.CreateModel(
            name='DesempenhoAcimaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisasSatisfacao.coordenacaoavaliandomonitoria')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor')),
            ],
            options={
                'ordering': ['posicao'],
                'unique_together': {('avaliacao', 'monitor')},
            },
        ),
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_acima_media',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_acima_media', through='pesquisasSatisfacao.DesempenhoAcimaMedia', to='peraltas.Monitor'),
        ),
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_atividades',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_atividades', through='pesquisasSatisfacao.DestaqueAtividades', to='peraltas.Monitor'),
        ),
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_evento',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_evento', to='peraltas.Monitor'),
        ),
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_pedagogicas',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_pedagogicas', to='peraltas.Monitor'),
        ),
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='ordem_de_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordemDeServico.ordemdeservico'),
        ),
        migrations.CreateModel(
            name='AvaliacaoIndividualMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('observacao', models.TextField(blank=True, null=True)),
                ('avaliacao_geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_individuais', to='pesquisasSatisfacao.coordenacaoavaliandomonitoria')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor')),
            ],
            options={
                'unique_together': {('avaliacao_geral', 'monitor')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoIndividualCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('observacao', models.TextField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_coordenadores', to='pesquisasSatisfacao.monitoravaliandocoordenacao')),
            ],
            options={
                'unique_together': {('pesquisa', 'coordenador')},
            },
        ),
    ]
