# Generated by Django 4.0.1 on 2025-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0191_produtocorporativo_brotas_eco'),
        ('pesquisasSatisfacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='captou_orientacoes',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='A equipe captou todas as orientações passadas durante o evento?'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='cuidados_materiais',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Cuidados com os materiais da empresa - Equipe como um todo.'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='iniciativa_empenho',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='A equipe demonstrou iniciativa e empenho no trabalho realizado?'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_evento',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_evento', to='peraltas.Monitor', verbose_name='Algum monitor teve destaque no evento em questão?'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_pedagogicas',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_pedagogicas', to='peraltas.Monitor', verbose_name='Algum monitor se destacou durante as atividades pedagógicas?'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='observacoes_equipe',
            field=models.TextField(help_text='Conte um pouco sobre a sinergia da equipe perante o evento'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='pontualidade_atividades',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Pontualidade nas atividades'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='pontualidade_chegada',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Pontualidade da equipe como um todo na chegada'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='seguiu_programacao',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Seguiu a Programação proposta para o período?'),
        ),
    ]
