# Generated by Django 4.0.1 on 2025-05-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0002_alter_coordenacaoavaliandomonitoria_captou_orientacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoravaliandocoordenacao',
            old_name='consideracoes_pedagogicas',
            new_name='consideracoes_pedagogicas_obs',
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='coordenador_participou',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='Os coordenadores participaram das atividades?'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='cuidados_materiais',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Cuidado com os materiais da empresa'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='desenvoltura_equipe',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Desenvoltura com a equipe de monitoria'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='organizacao_evento',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Organização do evento como um todo'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='pontualidade_atividades',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Pontualidade nas atividades'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='pontualidade_chegada',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Pontualidade na chegada (dos coordenadores)'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='seguiu_programacao',
            field=models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Seguiu a Programação proposta para o período?'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='tem_consideracoes_pedagogicas',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='Tem alguma consideração sobre as atividades pedagógicas propostas?'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='teve_briefing',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='Teve briefing prévio ao evento? Foram passadas todas as informações necessárias para o evento no briefing inicial?'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='teve_feedback',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='O coordenador deu feedback para a equipe no final do evento?'),
        ),
    ]
