# Generated by Django 4.0.1 on 2025-05-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0003_rename_consideracoes_pedagogicas_monitoravaliandocoordenacao_consideracoes_pedagogicas_obs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_evento',
        ),
        migrations.RemoveField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_pedagogicas',
        ),
    ]
