# Generated by Django 4.0.1 on 2025-05-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0191_produtocorporativo_brotas_eco'),
        ('pesquisasSatisfacao', '0004_remove_coordenacaoavaliandomonitoria_monitores_destaque_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_evento',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_evento', to='peraltas.Monitor', verbose_name='Algum monitor teve destaque no evento em questão?'),
        ),
        migrations.AddField(
            model_name='coordenacaoavaliandomonitoria',
            name='monitores_destaque_pedagogicas',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_destaque_pedagogicas', to='peraltas.Monitor', verbose_name='Algum monitor se destacou durante as atividades pedagógicas?'),
        ),
    ]
