# Generated by Django 4.0.1 on 2025-05-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0192_escalaacampamento_avaliou_coordenadores'),
        ('pesquisasSatisfacao', '0005_coordenacaoavaliandomonitoria_monitores_destaque_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoindividualcoordenador',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_recebidas', to='peraltas.monitor'),
        ),
    ]
