# Generated by Django 4.0.1 on 2025-05-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0006_alter_avaliacaoindividualcoordenador_coordenador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoravaliandocoordenacao',
            old_name='briefing_obs',
            new_name='coordenador_participou_obs',
        ),
        migrations.RenameField(
            model_name='monitoravaliandocoordenacao',
            old_name='consideracoes_pedagogicas_obs',
            new_name='tem_consideracoes_pedagogicas_obs',
        ),
        migrations.RenameField(
            model_name='monitoravaliandocoordenacao',
            old_name='feedback_obs',
            new_name='teve_briefing_obs',
        ),
        migrations.RenameField(
            model_name='monitoravaliandocoordenacao',
            old_name='participacao_obs',
            new_name='teve_feedback_obs',
        ),
    ]
