# Generated by Django 4.0.1 on 2025-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0007_rename_briefing_obs_monitoravaliandocoordenacao_coordenador_participou_obs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoravaliandocoordenacao',
            name='tem_consideracoes_pedagogicas_obs',
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='tem_consideracoes_pedagogicas',
            field=models.TextField(blank=True),
        ),
    ]
