# Generated by Django 4.0.1 on 2025-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0008_remove_monitoravaliandocoordenacao_tem_consideracoes_pedagogicas_obs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoravaliandocoordenacao',
            name='coordenador_participou_obs',
        ),
        migrations.RemoveField(
            model_name='monitoravaliandocoordenacao',
            name='teve_briefing_obs',
        ),
        migrations.RemoveField(
            model_name='monitoravaliandocoordenacao',
            name='teve_feedback_obs',
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='tem_consideracoes_pedagogicas',
            field=models.TextField(blank=True, verbose_name='Tem alguma consideração sobre as atividades pedagógicas propostas?'),
        ),
    ]
