# Generated by Django 4.0.1 on 2025-05-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0192_escalaacampamento_avaliou_coordenadores'),
        ('ordemDeServico', '0029_ordemdeservico_avaliou_monitoria'),
        ('pesquisasSatisfacao', '0009_remove_monitoravaliandocoordenacao_coordenador_participou_obs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcoesMotivacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoindividualcoordenador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avaliacaoindividualcoordenador',
            name='avaliacao_monitoria',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoindividualcoordenador',
            unique_together={('pesquisa', 'coordenador', 'avaliacao_monitoria')},
        ),
        migrations.CreateModel(
            name='AvaliacaoColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_resposta', models.DateTimeField(auto_now_add=True)),
                ('processo_vendas', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o processo de vendas')),
                ('processo_vendas_obs', models.TextField(blank=True)),
                ('transporte_utilizado', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o transporte utilizado')),
                ('transporte_utilizada_obs', models.TextField(blank=True)),
                ('equipe_monitoria', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o equipe de monitores como um todo')),
                ('equipe_monitoria_obs', models.TextField(blank=True)),
                ('atendimento_enfermeira', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Avalie o atendimento de enfermeira durante o evento')),
                ('atendimento_obs', models.TextField(blank=True)),
                ('atividades_recreativas', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Avalie as atividades recreativas propostas pela monitoria')),
                ('atividades_recreativas_obs', models.TextField(blank=True)),
                ('cafe_manha', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o café da manhã')),
                ('cafe_manha_obs', models.TextField(blank=True)),
                ('almoco', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o almoco')),
                ('almoco_obs', models.TextField(blank=True)),
                ('jantar', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o jantar')),
                ('jantar_obs', models.TextField(blank=True)),
                ('lanche_noite', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o lanche da noite')),
                ('lanche_noite_obs', models.TextField(blank=True)),
                ('estrutura_geral', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o estrutura em geral')),
                ('estrutura_geral_obs', models.TextField(blank=True)),
                ('quartos', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre a estrutura dos quartos')),
                ('quarto_obs', models.TextField(blank=True)),
                ('piscina', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre a estrutura da piscina')),
                ('piscina_obs', models.TextField(blank=True)),
                ('destaque', models.TextField()),
                ('sugestoes', models.TextField(blank=True)),
                ('outros_motivos', models.TextField(blank=True)),
                ('volta_proximo_ano', models.CharField(choices=[('primeiro_semestre', 'Sim - Primeiro semestre do ano seguinte'), ('segundo_semestre', 'Sim - Segundo semestre do ano seguinte'), ('daqui_dois_anos', 'Sim - 2027'), ('nao', 'Não'), ('talvez', 'Talvez')], max_length=50, verbose_name='Faria outro evento aqui no Peraltas, em 2026?')),
                ('volta_proximo_ano_obs', models.TextField(blank=True)),
                ('material_divigulgacao', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='Quer receber material com as novidades e promoções para o próximo ano?')),
                ('interesse_hospedar_com_familia', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], help_text='Caso sim, temos descontos exclusivos para pedagogos.', verbose_name='Tem interesse em se hospedar com o familia?')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.responsavel')),
                ('escala_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento')),
                ('motivo_trazer_grupo', models.ManyToManyField(to='pesquisasSatisfacao.OpcoesMotivacao')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordemDeServico.ordemdeservico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoIndividualAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('observacao', models.TextField(blank=True, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.atividadeseco')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_coordenadores', to='pesquisasSatisfacao.avaliacaocolegio')),
            ],
            options={
                'unique_together': {('pesquisa', 'atividade')},
            },
        ),
    ]
