# Generated by Django 4.0.1 on 2025-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0010_opcoesmotivacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoindividualatividade',
            name='avaliacao_colegio',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacaocolegio',
            name='volta_proximo_ano',
            field=models.CharField(choices=[('primeiro_semestre', 'Sim - Primeiro semestre do ano seguinte'), ('segundo_semestre', 'Sim - Segundo semestre do ano seguinte'), ('daqui_dois_anos', 'Sim - 2027'), ('talvez', 'Talvez'), ('nao', 'Não')], max_length=50, verbose_name='Faria outro evento aqui no Peraltas, em 2026?'),
        ),
    ]
