# Generated by Django 4.0.1 on 2025-05-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0011_avaliacaoindividualatividade_avaliacao_colegio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaocolegio',
            name='volta_proximo_ano',
            field=models.CharField(choices=[('primeiro_semestre', 'Sim - Primeiro semestre do ano seguinte'), ('segundo_semestre', 'Sim - Segundo semestre do ano seguinte'), ('daqui_dois_anos', 'Sim - Daqui dois anos'), ('talvez', 'Talvez'), ('nao', 'Não')], max_length=50),
        ),
    ]
