# Generated by Django 4.0.1 on 2025-05-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pesquisasSatisfacao', '0012_alter_avaliacaocolegio_volta_proximo_ano'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacaoindividualcoordenador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avaliacaoindividualcoordenador',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaoindividualcoordenador',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='avaliacaoindividualcoordenador',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'coordenador'), name='avaliacao_unica_por_coordenador'),
        ),
        migrations.RemoveField(
            model_name='avaliacaoindividualcoordenador',
            name='pesquisa',
        ),
    ]
