# Generated by Django 4.0.1 on 2025-05-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0013_alter_avaliacaoindividualcoordenador_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaoindividualcoordenador',
            name='avaliacao_monitoria',
        ),
    ]
