# Generated by Django 4.0.1 on 2025-05-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pesquisasSatisfacao', '0014_remove_avaliacaoindividualcoordenador_avaliacao_monitoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacaoindividualatividade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avaliacaoindividualatividade',
            name='atividade_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='atividade_avaliacoes', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaoindividualatividade',
            name='atividade_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaoindividualatividade',
            name='pesquisa_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_avaliacoes', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaoindividualatividade',
            name='pesquisa_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='avaliacaoindividualatividade',
            index=models.Index(fields=['pesquisa_content_type', 'pesquisa_object_id'], name='pesquisasSa_pesquis_e28540_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoindividualatividade',
            index=models.Index(fields=['atividade_content_type', 'atividade_object_id'], name='pesquisasSa_ativida_ecef32_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaoindividualatividade',
            constraint=models.UniqueConstraint(fields=('pesquisa_content_type', 'pesquisa_object_id', 'atividade_content_type', 'atividade_object_id'), name='avaliacao_unica_por_atividade'),
        ),
        migrations.RemoveField(
            model_name='avaliacaoindividualatividade',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='avaliacaoindividualatividade',
            name='avaliacao_colegio',
        ),
        migrations.RemoveField(
            model_name='avaliacaoindividualatividade',
            name='pesquisa',
        ),
    ]
