# Generated by Django 4.0.1 on 2025-05-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0192_escalaacampamento_avaliou_coordenadores'),
        ('ordemDeServico', '0029_ordemdeservico_avaliou_monitoria'),
        ('pesquisasSatisfacao', '0015_alter_avaliacaoindividualatividade_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_resposta', models.DateTimeField(auto_now_add=True)),
                ('equipe_monitoria', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o equipe de monitores como um todo')),
                ('equipe_monitoria_obs', models.TextField(blank=True)),
                ('estrutura_ceu', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre a estrutura do Centro de Estudos do Universo')),
                ('estrutura_ceu_obs', models.TextField(blank=True)),
                ('cafe_manha', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o café da manhã')),
                ('cafe_manha_obs', models.TextField(blank=True)),
                ('coffee_break', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o coffee break')),
                ('coffee_break_obs', models.TextField(blank=True)),
                ('almoco', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o almoco')),
                ('almoco_obs', models.TextField(blank=True)),
                ('jantar', models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o jantar')),
                ('jantar_obs', models.TextField(blank=True)),
                ('estrutura_geral', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o estrutura em geral')),
                ('estrutura_geral_obs', models.TextField(blank=True)),
                ('quartos', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Avalie a habitação que esteve hospedada')),
                ('quarto_obs', models.TextField(blank=True)),
                ('atendimento_bar', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], verbose_name='Comente sobre o atendimento do bar')),
                ('atendimento_obs', models.TextField(blank=True)),
                ('mais_valorizou', models.TextField(verbose_name='O que você mais valorizou durante a sua estadia no Brotas eco?')),
                ('sugestoes', models.TextField(blank=True, verbose_name='Sugestões para melhorias')),
                ('volta_proximo_ano', models.CharField(choices=[('primeiro_semestre', 'Sim - Primeiro semestre do ano seguinte'), ('segundo_semestre', 'Sim - Segundo semestre do ano seguinte'), ('daqui_dois_anos', 'Sim - Daqui dois anos'), ('talvez', 'Talvez'), ('nao', 'Não')], max_length=50)),
                ('volta_proximo_ano_obs', models.TextField(blank=True)),
                ('material_divigulgacao', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], verbose_name='Quer receber material com as novidades e promoções para o próximo ano?')),
                ('interesse_hospedar_com_familia', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], help_text='Caso a resposta seja sim, vamos gerar um cupom de desconto para você!', verbose_name='Tem interesse em trazer a sua família ao Brotas eco?')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.responsavel')),
                ('escala_peraltas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordemDeServico.ordemdeservico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
