# Generated by Django 4.0.1 on 2025-05-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pesquisasSatisfacao', '0016_avaliacaocorporativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoIndividualSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesquisa_corporativo_object_id', models.PositiveIntegerField()),
                ('sala_object_id', models.PositiveIntegerField()),
                ('avaliacao', models.IntegerField(choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')])),
                ('observacao', models.TextField(blank=True, null=True)),
                ('pesquisa_corporativo_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_corporativo_avaliacoes', to='contenttypes.contenttype')),
                ('sala_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sala_avaliacoes', to='contenttypes.contenttype')),
            ],
        ),
    ]
