# Generated by Django 4.0.1 on 2025-05-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0017_avaliacaoindividualsala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaocolegio',
            old_name='transporte_utilizada_obs',
            new_name='transporte_utilizado_obs',
        ),
    ]
