# Generated by Django 4.0.1 on 2025-05-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0018_rename_transporte_utilizada_obs_avaliacaocolegio_transporte_utilizado_obs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaocolegio',
            old_name='atendimento_obs',
            new_name='atendimento_enfermeira_obs',
        ),
        migrations.RenameField(
            model_name='avaliacaocolegio',
            old_name='quarto_obs',
            new_name='quartos_obs',
        ),
    ]
