# Generated by Django 4.0.1 on 2025-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0019_rename_atendimento_obs_avaliacaocolegio_atendimento_enfermeira_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaocolegio',
            name='volta_proximo_ano',
            field=models.CharField(choices=[('', '-----------'), ('primeiro_semestre', 'Sim - Primeiro semestre do ano seguinte'), ('segundo_semestre', 'Sim - Segundo semestre do ano seguinte'), ('daqui_dois_anos', 'Sim - Daqui dois anos'), ('talvez', 'Talvez'), ('nao', 'Não')], max_length=50),
        ),
        migrations.AlterField(
            model_name='avaliacaocorporativo',
            name='volta_proximo_ano',
            field=models.CharField(choices=[('', '-----------'), ('primeiro_semestre', 'Sim - Primeiro semestre do ano seguinte'), ('segundo_semestre', 'Sim - Segundo semestre do ano seguinte'), ('daqui_dois_anos', 'Sim - Daqui dois anos'), ('talvez', 'Talvez'), ('nao', 'Não')], max_length=50),
        ),
    ]
