# Generated by Django 4.0.1 on 2025-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0020_alter_avaliacaocolegio_volta_proximo_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaocolegio',
            name='lanche_noite',
            field=models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o lanche da noite'),
        ),
    ]
