# Generated by Django 4.0.1 on 2025-05-28 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0192_escalaacampamento_avaliou_coordenadores'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ordemDeServico', '0029_ordemdeservico_avaliou_monitoria'),
        ('pesquisasSatisfacao', '0021_alter_avaliacaocolegio_lanche_noite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('monitor', 'Monitor')], max_length=20)),
                ('avaliacao_object_id', models.PositiveIntegerField()),
                ('avaliacao_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_feitas', to='peraltas.monitor')),
            ],
        ),
        migrations.RenameField(
            model_name='avaliacaocorporativo',
            old_name='atendimento_obs',
            new_name='atendimento_bar_obs',
        ),
        migrations.RenameField(
            model_name='avaliacaocorporativo',
            old_name='quarto_obs',
            new_name='quartos_obs',
        ),
        migrations.AlterField(
            model_name='avaliacaocolegio',
            name='escala_peraltas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento'),
        ),
        migrations.AlterField(
            model_name='avaliacaocorporativo',
            name='escala_peraltas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento'),
        ),
        migrations.AlterField(
            model_name='coordenacaoavaliandomonitoria',
            name='escala_peraltas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento'),
        ),
        migrations.AlterField(
            model_name='monitoravaliandocoordenacao',
            name='escala_peraltas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peraltas.escalaacampamento'),
        ),
        migrations.CreateModel(
            name='NotaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliado_como_coordenador', models.BooleanField(default=False)),
                ('nota_cliente', models.FloatField(blank=True, null=True)),
                ('nota_media_coordenadores', models.FloatField(blank=True, null=True)),
                ('nota_media_monitores', models.FloatField(blank=True, null=True)),
                ('media_final', models.FloatField(blank=True, null=True)),
                ('avaliacoes', models.ManyToManyField(to='pesquisasSatisfacao.Avaliacao')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.monitor')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordemDeServico.ordemdeservico')),
            ],
            options={
                'unique_together': {('ordem_de_servico', 'avaliado')},
            },
        ),
    ]
