# Generated by Django 4.0.1 on 2025-05-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0022_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notaevento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notaevento',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='notaevento',
            name='avaliado',
        ),
        migrations.RemoveField(
            model_name='notaevento',
            name='ordem_de_servico',
        ),
        migrations.AlterField(
            model_name='avaliacaocorporativo',
            name='coffee_break',
            field=models.IntegerField(blank=True, choices=[(1, 'Ruim'), (2, 'Regular'), (3, 'Bom'), (4, 'Ótimo'), (5, 'Excelente')], null=True, verbose_name='Comente sobre o coffee break'),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='NotaEvento',
        ),
    ]
