# Generated by Django 4.0.1 on 2025-05-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0023_alter_notaevento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaocolegio',
            name='avaliador',
        ),
        migrations.RemoveField(
            model_name='avaliacaocorporativo',
            name='avaliador',
        ),
        migrations.AddField(
            model_name='avaliacaocolegio',
            name='cargo_avaliador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocolegio',
            name='email_avaliador',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocolegio',
            name='nome_avaliador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocolegio',
            name='telefone_avaliador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocorporativo',
            name='cargo_avaliador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocorporativo',
            name='email_avaliador',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocorporativo',
            name='nome_avaliador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaocorporativo',
            name='telefone_avaliador',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
