# Generated by Django 4.0.1 on 2025-06-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisasSatisfacao', '0024_remove_avaliacaocolegio_avaliador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoravaliandocoordenacao',
            name='observacoes_equipe',
            field=models.TextField(default=' ', help_text='Conte um pouco sobre a sinergia dos coordenadores com a equipe perante ao evento'),
            preserve_default=False,
        ),
    ]
