# Generated by Django 4.0.1 on 2024-10-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_mon', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Relação participantes por monitor')),
                ('min_media_diarias', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor mínimo da média de diarias')),
                ('max_media_diarias', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor máximo da média de diarias')),
            ],
        ),
    ]
