# Generated by Django 4.0.1 on 2024-10-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelDiretoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metas',
            options={'permissions': (('ver_estatisticas_monitoria', 'Ver estatísticas da monitoria'),)},
        ),
    ]
