# Generated by Django 4.0.1 on 2024-02-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peraltas', '0164_merge_20240128_1235'),
        ('orcamento', '0068_remove_valorestransporte_validade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_financeiro', models.CharField(max_length=255, verbose_name='Responsável financeiro')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comissão')),
                ('check_in', models.DateTimeField(verbose_name='Check in')),
                ('check_out', models.DateTimeField(verbose_name='Check out')),
                ('coordenacao', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Coordenação')),
                ('monitoria', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Monitoria')),
                ('onibus', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Ônibus')),
                ('seguro', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Seguro')),
                ('qtd_reservada', models.PositiveIntegerField(verbose_name='Qtd reserva')),
                ('alunos_confirmados', models.PositiveIntegerField(default=0, verbose_name='Alunos confirmados')),
                ('responsaveis_confirmados', models.PositiveIntegerField(default=0, verbose_name='Responsáveis confirmados')),
                ('cortesia_alunos', models.PositiveIntegerField(default=0, verbose_name='Cortesia de alunos')),
                ('cortesia_responsaveis', models.PositiveIntegerField(default=0, verbose_name='Cortesia de responsáveis')),
                ('responsaveis_outros_locais', models.PositiveIntegerField(default=0, verbose_name='Responsáveis em outros locais')),
                ('alunos_outros_locais', models.PositiveIntegerField(default=0, verbose_name='Alunos em outros locais')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('responsavel_operecional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.responsavel', verbose_name='Responsável operacional')),
            ],
        ),
        migrations.CreateModel(
            name='DadosPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Período')),
                ('descritivo_periodo', models.JSONField(editable=False)),
                ('monitoria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monitoria')),
                ('descritivo_monitoria', models.JSONField(editable=False)),
                ('atividades_ceu', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Atividades CEU')),
                ('descritivo_atividades_ceu', models.JSONField(editable=False)),
                ('atividades_peraltas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Atividades Peraltas')),
                ('descritivo_atividades_peraltas', models.JSONField(editable=False)),
                ('opcionais', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Opcionais')),
                ('descritivo_opcionais', models.JSONField(editable=False)),
                ('op_extra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Opcionais extra')),
                ('descritivo_extra', models.JSONField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razao social')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='PlanosPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_a_vista', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor à vista')),
                ('forma_pagamento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Forma de pagamento')),
                ('parcelas', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
                ('inicio_vencimento', models.DateField(verbose_name='Início vencimento')),
                ('final_vencimento', models.DateField(verbose_name='Final vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='FichaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.BooleanField(default=False, verbose_name='NF')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('descritivo_ficha_financeira', models.JSONField(editable=False)),
                ('autorizado_diretoria', models.BooleanField(default=False, verbose_name='Autorizado pela diretoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio', verbose_name='Cliente')),
                ('dados_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.dadosevento', verbose_name='Dados do evento')),
                ('dados_nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.notafiscal', verbose_name='Dados da nota fiscal')),
                ('dados_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.dadospagamento', verbose_name='Dados do pagamento')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamento', verbose_name='Orçamento')),
                ('planos_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.planospagamento', verbose_name='Planos de pagamento')),
            ],
        ),
    ]
