# Generated by Django 4.0.1 on 2024-02-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichafinanceira',
            name='enviado_ac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enviado a/c'),
        ),
    ]
