# Generated by Django 4.0.1 on 2024-02-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_fichafinanceira_enviado_ac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosevento',
            old_name='responsavel_operecional',
            new_name='responsavel_operacional',
        ),
    ]
