# Generated by Django 4.0.1 on 2024-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_rename_responsavel_operecional_dadosevento_responsavel_operacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichafinanceira',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='fichafinanceira',
            name='observacoes_ficha_financeira',
            field=models.TextField(blank=True, verbose_name='Observações ficha financeira'),
        ),
        migrations.AddField(
            model_name='fichafinanceira',
            name='observaoes_orcamento',
            field=models.TextField(blank=True, verbose_name='Observações orcamento'),
        ),
    ]
