# Generated by Django 4.0.1 on 2024-02-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_remove_fichafinanceira_observacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichafinanceira',
            old_name='observaoes_orcamento',
            new_name='observacoes_orcamento',
        ),
    ]
