# Generated by Django 4.0.1 on 2024-02-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0164_merge_20240128_1235'),
        ('financeiro', '0005_rename_observaoes_orcamento_fichafinanceira_observacoes_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichafinanceira',
            name='planos_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.planospagamento', verbose_name='Planos de pagamento'),
        ),
        migrations.AlterField(
            model_name='planospagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.tipospagamentos', verbose_name='Forma de pagamento'),
        ),
    ]
