# Generated by Django 4.0.1 on 2024-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_fichafinanceira_planos_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planospagamento',
            name='parcelas',
            field=models.IntegerField(default=1, verbose_name='Parcelas'),
        ),
    ]
