# Generated by Django 4.0.1 on 2024-03-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_planospagamento_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosevento',
            name='responsavel_financeiro',
            field=models.CharField(max_length=250, verbose_name='Responsável financeiro'),
        ),
    ]
