# Generated by Django 4.0.1 on 2024-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_dadosevento_responsavel_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosevento',
            name='responsavel_financeiro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Responsável financeiro'),
        ),
    ]
