# Generated by Django 4.0.1 on 2024-03-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_alter_dadosevento_responsavel_financeiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='atividades_ceu',
            new_name='valor_atividades_ceu',
        ),
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='atividades_peraltas',
            new_name='valor_atividades_peraltas',
        ),
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='monitoria',
            new_name='valor_monitoria',
        ),
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='op_extra',
            new_name='valor_op_extra',
        ),
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='opcionais',
            new_name='valor_opcionais',
        ),
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='periodo',
            new_name='valor_periodo',
        ),
    ]
