# Generated by Django 4.0.1 on 2024-03-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_rename_atividades_ceu_dadospagamento_valor_atividades_ceu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospagamento',
            name='descritivo_transporte',
            field=models.JSONField(default=0.0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospagamento',
            name='valor_transporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Transporte'),
            preserve_default=False,
        ),
    ]
