# Generated by Django 4.0.1 on 2024-03-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_dadospagamento_descritivo_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichafinanceira',
            name='comentario_financeiro',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário para o financeiro'),
        ),
        migrations.AddField(
            model_name='fichafinanceira',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da recusa'),
        ),
    ]
