# Generated by Django 4.0.1 on 2024-03-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_fichafinanceira_comentario_financeiro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichafinanceira',
            old_name='comentario_financeiro',
            new_name='comentario_diretoria',
        ),
    ]
