# Generated by Django 4.0.1 on 2024-03-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_rename_comentario_financeiro_fichafinanceira_comentario_diretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichafinanceira',
            name='negado',
            field=models.BooleanField(default=False, verbose_name='Negado'),
        ),
    ]
