# Generated by Django 4.0.1 on 2024-03-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_fichafinanceira_negado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichafinanceira',
            name='faturado',
            field=models.BooleanField(default=False, verbose_name='Faturado'),
        ),
    ]
