# Generated by Django 4.0.1 on 2024-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_fichafinanceira_faturado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosevento',
            name='alunos_outros_locais',
        ),
        migrations.RemoveField(
            model_name='dadosevento',
            name='responsaveis_confirmados',
        ),
        migrations.RemoveField(
            model_name='dadosevento',
            name='responsaveis_outros_locais',
        ),
        migrations.AddField(
            model_name='dadosevento',
            name='cortesias_externas',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Cortesias externas'),
        ),
        migrations.AddField(
            model_name='dadosevento',
            name='email_financeiro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='E-mail financeiro'),
        ),
        migrations.AddField(
            model_name='dadosevento',
            name='pgto_neto',
            field=models.ImageField(choices=[(0, 'Não'), (1, 'Sim')], default=0, upload_to='', verbose_name='Pgto neto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosevento',
            name='professores_confirmados',
            field=models.PositiveIntegerField(default=0, verbose_name='Professores confirmados'),
        ),
        migrations.AddField(
            model_name='dadosevento',
            name='telefone_financeiro',
            field=models.CharField(default='(11) 11111-1111', max_length=250, verbose_name='Telefone financeiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planospagamento',
            name='codigo_eficha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo E-Ficha'),
        ),
        migrations.AddField(
            model_name='planospagamento',
            name='comissoes_externas',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Comissões externas'),
        ),
        migrations.AlterField(
            model_name='dadosevento',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='dadosevento',
            name='coordenacao',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=1, verbose_name='Coordenação'),
        ),
        migrations.AlterField(
            model_name='dadosevento',
            name='cortesia_responsaveis',
            field=models.PositiveIntegerField(default=0, verbose_name='Cortesia de professores'),
        ),
        migrations.AlterField(
            model_name='dadosevento',
            name='qtd_reservada',
            field=models.PositiveIntegerField(verbose_name='Qtd reservada'),
        ),
    ]
