# Generated by Django 4.0.1 on 2024-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_remove_dadosevento_alunos_outros_locais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosevento',
            name='pgto_neto',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], verbose_name='Pgto neto'),
        ),
    ]
