# Generated by Django 4.0.1 on 2024-03-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_alter_dadosevento_pgto_neto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razao social'),
        ),
    ]
