# Generated by Django 4.0.1 on 2024-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_alter_notafiscal_cnpj_alter_notafiscal_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosevento',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Comissão'),
        ),
    ]
