# Generated by Django 4.0.1 on 2025-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_alter_dadosevento_comissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacoesItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_padrao', models.CharField(max_length=255, verbose_name='Codigo Padrão')),
                ('codigo_simplificado', models.CharField(max_length=255, verbose_name='Codigo Simplificado')),
                ('descritivo', models.TextField(verbose_name='Descritivo')),
                ('sintetico_analitico', models.IntegerField(choices=[(0, 'Sintético'), (1, 'Analítico')], verbose_name='Sintético/Analítico')),
                ('ativado', models.BooleanField(default=False, verbose_name='Ativado')),
            ],
        ),
    ]
