# Generated by Django 4.0.1 on 2025-02-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_classificacoesitens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacoesitens',
            name='codigo_padrao',
            field=models.CharField(max_length=255, unique=True, verbose_name='Codigo Padrão'),
        ),
        migrations.AlterField(
            model_name='classificacoesitens',
            name='codigo_simplificado',
            field=models.CharField(max_length=255, unique=True, verbose_name='Codigo Simplificado'),
        ),
    ]
