# Generated by Django 4.0.1 on 2025-03-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_alter_classificacoesitens_codigo_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospagamento',
            name='descritivo_atividades_ceu',
        ),
        migrations.RemoveField(
            model_name='dadospagamento',
            name='descritivo_atividades_peraltas',
        ),
        migrations.RemoveField(
            model_name='dadospagamento',
            name='valor_atividades_ceu',
        ),
        migrations.RemoveField(
            model_name='dadospagamento',
            name='valor_atividades_peraltas',
        ),
    ]
