# Generated by Django 4.0.1 on 2025-04-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0165_responsavel_whats_alter_responsavel_fone'),
        ('financeiro', '0022_remove_dadospagamento_descritivo_atividades_ceu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosevento',
            name='alunos_confirmados',
            field=models.CharField(max_length=255, null=True, blank=True)
        ),
        migrations.RemoveField(
            model_name='dadosevento',
            name='email_financeiro',
            field=models.CharField(max_length=255, null=True, blank=True)
        ),
        migrations.RemoveField(
            model_name='dadosevento',
            name='professores_confirmados',
            field=models.CharField(max_length=255, null=True, blank=True)
        ),
        migrations.RemoveField(
            model_name='dadosevento',
            name='telefone_financeiro',
            field=models.CharField(max_length=255, null=True, blank=True)
        ),
        migrations.RemoveField(
            model_name='fichafinanceira',
            name='observacoes_orcamento',
            field=models.CharField(max_length=255, null=True, blank=True)
        ),
    ]
