# Generated by Django 4.0.1 on 2025-04-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0165_responsavel_whats_alter_responsavel_fone'),
        ('financeiro', '0023_remove_dadosevento_alunos_confirmados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosevento',
            name='responsavel_operacional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_operacional', to='peraltas.responsavel', verbose_name='Responsável operacional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosevento',
            name='responsavel_financeiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_financeiro', to='peraltas.responsavel', verbose_name='Responsável financeiro'),
            preserve_default=False,
        ),
    ]
