# Generated by Django 4.0.1 on 2025-04-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0165_responsavel_whats_alter_responsavel_fone'),
        ('financeiro', '0024_alter_dadosevento_responsavel_financeiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichafinanceira',
            name='enviado_ac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peraltas.responsavel', verbose_name='Enviado a/c'),
        ),
    ]
