# Generated by Django 4.0.1 on 2025-04-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_alter_fichafinanceira_enviado_ac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosevento',
            name='seguro',
        ),
    ]
