# Generated by Django 4.0.1 on 2025-04-05 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_remove_dadosevento_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichafinanceira',
            name='data_aprovacao_diretoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovacao pela diretoria'),
        ),
        migrations.AddField(
            model_name='fichafinanceira',
            name='data_faturamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Preenchimento de faturamento'),
        ),
        migrations.AddField(
            model_name='fichafinanceira',
            name='data_preenchimento_comercial',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 23, 41, 53, 80070, tzinfo=utc), verbose_name='Data de Preenchimento pelo comercial'),
            preserve_default=False,
        ),
    ]
