# Generated by Django 4.0.1 on 2025-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_fichafinanceira_data_aprovacao_diretoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(max_length=255)),
                ('offline', models.BooleanField(default=False)),
            ],
        ),
    ]
