# Generated by Django 4.0.1 on 2025-05-31 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_tipospagamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacoesitens',
            name='arredondamento',
            field=models.BooleanField(default=False, help_text='Categoria na Ficha Financeira que será utilizada para o arredondamento.', verbose_name='Arredondamento'),
        ),
        migrations.AlterField(
            model_name='planospagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.tipospagamentos', verbose_name='Forma de pagamento'),
        ),
    ]
