# Generated by Django 4.0.1 on 2025-07-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0029_classificacoesitens_arredondamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichafinanceira',
            options={'permissions': (('pode_aprovar_ficha_financeira', 'Pode aprovar ficha financeira'), ('pode_faturar_ficha_financeira', 'Pode faturar ficha financeira'))},
        ),
    ]
