# Generated by Django 4.0.1 on 2025-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0030_alter_fichafinanceira_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipospagamentos',
            name='eficha',
            field=models.BooleanField(default=False, verbose_name='e-Ficha'),
        ),
    ]
