# Generated by Django 4.0.1 on 2023-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0156_fichadeevento_agencia'),
        ('cadastro', '0003_rename_entregue_relatoriodeatendimentocolegioceu_ficha_avaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodeatendimentocolegioceu',
            name='coordenador_peraltas',
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentocolegioceu',
            name='coordenador_peraltas',
            field=models.ManyToManyField(to='peraltas.Monitor'),
        ),
    ]
