# Generated by Django 4.0.1 on 2023-10-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_relatoriodeatendimentocolegioceu_coordenador_peraltas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodeatendimentocolegioceu',
            name='tipo',
            field=models.CharField(blank=True, default='colegio', max_length=7),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentoempresaceu',
            name='tipo',
            field=models.CharField(blank=True, default='empresa', max_length=7),
        ),
        migrations.AlterField(
            model_name='relatoriodeatendimentopublicoceu',
            name='tipo',
            field=models.CharField(blank=True, default='publico', max_length=7),
        ),
    ]
