# Generated by Django 4.0.1 on 2023-10-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0025_auto_20231020_2158'),
        ('cadastro', '0005_alter_relatoriodeatendimentocolegioceu_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodeatendimentocolegioceu',
            name='ordem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ordemDeServico.ordemdeservico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentoempresaceu',
            name='ordem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ordemDeServico.ordemdeservico'),
            preserve_default=False,
        ),
    ]
