# Generated by Django 4.0.1 on 2023-10-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0157_fichadeevento_adesao'),
        ('cadastro', '0006_relatoriodeatendimentocolegioceu_ordem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodeatendimentoempresaceu',
            name='coordenador_peraltas',
        ),
        migrations.AddField(
            model_name='relatoriodeatendimentoempresaceu',
            name='coordenador_peraltas',
            field=models.ManyToManyField(to='peraltas.Monitor'),
        ),
    ]
