# Generated by Django 4.0.1 on 2022-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0003_alter_clientecolegio_codigo_app_pf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='quais_atividades',
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='quais_atividades',
            field=models.ManyToManyField(blank=True, to='peraltas.AtividadesEco'),
        ),
    ]
