# Generated by Django 4.0.1 on 2022-05-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0004_remove_informacoesadcionais_quais_atividades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeHotelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponiveis', models.TextField(max_length=500)),
                ('mes', models.IntegerField(choices=[(10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro')])),
                ('ano', models.CharField(max_length=20)),
                ('n_dias', models.IntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadeAcampamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponiveis', models.TextField(max_length=500)),
                ('mes', models.IntegerField(choices=[(10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro')])),
                ('ano', models.CharField(max_length=20)),
                ('n_dias', models.IntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor')),
            ],
        ),
    ]
