# Generated by Django 4.0.1 on 2022-05-20 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0007_rename_cnpj_empresaonibus_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='ficha_financeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='tipo_veiculo',
            field=models.IntegerField(blank=True, choices=[(1, 'Ônibus'), (1, 'Micro ônibus')], null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (11, 'Novembro')]),
        ),
        migrations.CreateModel(
            name='DadosSegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segurados', models.JSONField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio')),
            ],
        ),
    ]
