# Generated by Django 4.0.1 on 2022-05-26 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0013_rename_dia_limite_acampamento_dialimitehotelaria_dia_limite_hotelaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalahotelaria',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro'), (5, 'Maio')]),
        ),
    ]
