# Generated by Django 4.0.1 on 2022-05-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0014_escalahotelaria_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalahotelaria',
            name='cliente',
        ),
        migrations.AddField(
            model_name='escalaacampamneto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (11, 'Novembro'), (3, 'Março'), (2, 'Fevereiro'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (5, 'Maio'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (11, 'Novembro'), (3, 'Março'), (2, 'Fevereiro'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (5, 'Maio'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (1, 'Janeiro')]),
        ),
        migrations.RemoveField(
            model_name='escalaacampamneto',
            name='monitores_acampamento',
        ),
        migrations.AddField(
            model_name='escalaacampamneto',
            name='monitores_acampamento',
            field=models.ManyToManyField(to='peraltas.Monitor'),
        ),
        migrations.RemoveField(
            model_name='escalahotelaria',
            name='monitores_hotelaria',
        ),
        migrations.AddField(
            model_name='escalahotelaria',
            name='monitores_hotelaria',
            field=models.ManyToManyField(to='peraltas.Monitor'),
        ),
    ]
