# Generated by Django 4.0.1 on 2022-05-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0015_remove_escalahotelaria_cliente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscalaAcampamneto',
            new_name='EscalaAcampamento',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (3, 'Março'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (8, 'Agosto'), (12, 'Dezembro'), (9, 'Setembro'), (4, 'Abril'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (3, 'Março'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (8, 'Agosto'), (12, 'Dezembro'), (9, 'Setembro'), (4, 'Abril'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
    ]
