# Generated by Django 4.0.1 on 2022-05-28 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0018_remove_escalaacampamento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (2, 'Fevereiro'), (11, 'Novembro'), (12, 'Dezembro'), (5, 'Maio'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (2, 'Fevereiro'), (11, 'Novembro'), (12, 'Dezembro'), (5, 'Maio'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='check_in_cliente',
            field=models.DateTimeField(default=datetime.timezone),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='check_out_cliente',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
