# Generated by Django 4.0.1 on 2022-05-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0019_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (1, 'Janeiro'), (2, 'Fevereiro'), (12, 'Dezembro'), (9, 'Setembro'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (1, 'Janeiro'), (2, 'Fevereiro'), (12, 'Dezembro'), (9, 'Setembro'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio'),
        ),
    ]
