# Generated by Django 4.0.1 on 2022-06-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0020_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (12, 'Dezembro'), (3, 'Março'), (4, 'Abril'), (10, 'Outubro'), (9, 'Setembro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (12, 'Dezembro'), (3, 'Março'), (4, 'Abril'), (10, 'Outubro'), (9, 'Setembro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho')]),
        ),
        migrations.CreateModel(
            name='PreReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('participantes', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor')),
            ],
        ),
    ]
