# Generated by Django 4.0.1 on 2022-06-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0021_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prereserva',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (11, 'Novembro'), (10, 'Outubro'), (3, 'Março'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (11, 'Novembro'), (10, 'Outubro'), (3, 'Março'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio'), (9, 'Setembro')]),
        ),
    ]
