# Generated by Django 4.0.1 on 2022-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0023_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='lista_segurados',
            field=models.FileField(blank=True, upload_to='seguros/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (5, 'Maio'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (11, 'Novembro'), (7, 'Julho'), (10, 'Outubro'), (6, 'Junho'), (3, 'Março'), (9, 'Setembro'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (5, 'Maio'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (11, 'Novembro'), (7, 'Julho'), (10, 'Outubro'), (6, 'Junho'), (3, 'Março'), (9, 'Setembro'), (1, 'Janeiro')]),
        ),
    ]
