# Generated by Django 4.0.1 on 2022-07-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0027_monitor_biologo_monitor_fotos_e_filmagens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (4, 'Abril'), (3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (6, 'Junho'), (10, 'Outubro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (4, 'Abril'), (3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (6, 'Junho'), (10, 'Outubro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='prereserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
        ),
    ]
