# Generated by Django 4.0.1 on 2022-07-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0031_remove_informacoesadcionais_terceirizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (5, 'Maio'), (8, 'Agosto'), (6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (1, 'Janeiro'), (9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (5, 'Maio'), (8, 'Agosto'), (6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (3, 'Março')]),
        ),
    ]
