# Generated by Django 4.0.1 on 2022-07-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0035_alter_atividadeperaltas_manual_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='idade_max',
            field=models.PositiveIntegerField(verbose_name='Idade máxima'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='idade_min',
            field=models.PositiveIntegerField(verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='lista_materiais',
            field=models.CharField(max_length=255, verbose_name='Lista de materiais'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='manual_atividade',
            field=models.FileField(blank=True, upload_to='manuais_atividades_acampamento/%Y/%m/%d', verbose_name='Manual'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='monitores_max',
            field=models.PositiveIntegerField(verbose_name='Número máximo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='monitores_min',
            field=models.PositiveIntegerField(verbose_name='Número mínimo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='nivel_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.nivelmonitoria', verbose_name='Nível da atividade'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='nome_atividade',
            field=models.CharField(max_length=255, verbose_name='Nome da atividade'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='participantes_max',
            field=models.PositiveIntegerField(verbose_name='Número máximo de participantes'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='participantes_min',
            field=models.PositiveIntegerField(verbose_name='Número mínimo de participantes'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='tipo_atividade',
            field=models.ManyToManyField(to='peraltas.TipoAtividade', verbose_name='Tipo da atividade'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='idade_max',
            field=models.PositiveIntegerField(verbose_name='Idade máxima'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='idade_min',
            field=models.PositiveIntegerField(verbose_name='Idade mínima'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='lista_materiais',
            field=models.CharField(max_length=255, verbose_name='Lista de materiais'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='manual_atividade',
            field=models.FileField(blank=True, upload_to='manuais_atividades_eco/%Y/%m/%d', verbose_name='Manual'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='monitores_max',
            field=models.PositiveIntegerField(verbose_name='Número máximo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='monitores_min',
            field=models.PositiveIntegerField(verbose_name='Número mínimo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='nivel_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.nivelmonitoria', verbose_name='Nível da atividade'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='nome_atividade_eco',
            field=models.CharField(max_length=255, verbose_name='Nome da atividade'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='participantes_max',
            field=models.PositiveIntegerField(verbose_name='Número máximo de participantes'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='participantes_min',
            field=models.PositiveIntegerField(verbose_name='Número mínimo de participantes'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='tipo_atividade',
            field=models.ManyToManyField(to='peraltas.TipoAtividade', verbose_name='Tipo de atividade'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (1, 'Janeiro')]),
        ),
    ]
