# Generated by Django 4.0.1 on 2022-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0036_alter_atividadeperaltas_idade_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro')]),
        ),
    ]
