# Generated by Django 4.0.1 on 2022-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0037_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (2, 'Fevereiro'), (11, 'Novembro'), (9, 'Setembro'), (3, 'Março'), (1, 'Janeiro'), (10, 'Outubro'), (6, 'Junho'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (2, 'Fevereiro'), (11, 'Novembro'), (9, 'Setembro'), (3, 'Março'), (1, 'Janeiro'), (10, 'Outubro'), (6, 'Junho'), (5, 'Maio')]),
        ),
    ]
