# Generated by Django 4.0.1 on 2022-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0040_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (1, 'Janeiro'), (11, 'Novembro'), (9, 'Setembro'), (10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (12, 'Dezembro'), (3, 'Março'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (1, 'Janeiro'), (11, 'Novembro'), (9, 'Setembro'), (10, 'Outubro'), (5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (12, 'Dezembro'), (3, 'Março'), (8, 'Agosto')]),
        ),
    ]
