# Generated by Django 4.0.1 on 2022-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0041_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho')]),
        ),
    ]
