# Generated by Django 4.0.1 on 2022-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0044_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (11, 'Novembro'), (9, 'Setembro'), (2, 'Fevereiro'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (6, 'Junho'), (8, 'Agosto'), (3, 'Março'), (10, 'Outubro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (11, 'Novembro'), (9, 'Setembro'), (2, 'Fevereiro'), (4, 'Abril'), (1, 'Janeiro'), (12, 'Dezembro'), (6, 'Junho'), (8, 'Agosto'), (3, 'Março'), (10, 'Outubro'), (5, 'Maio')]),
        ),
    ]
