# Generated by Django 4.0.1 on 2022-08-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0045_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (6, 'Junho'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
    ]
