# Generated by Django 4.0.1 on 2022-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0046_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (7, 'Julho'), (5, 'Maio')]),
        ),
    ]
