# Generated by Django 4.0.1 on 2022-09-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0047_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (4, 'Abril'), (12, 'Dezembro'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (11, 'Novembro')]),
        ),
    ]
