# Generated by Django 4.0.1 on 2022-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0048_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (6, 'Junho'), (8, 'Agosto'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (11, 'Novembro'), (5, 'Maio'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (6, 'Junho'), (8, 'Agosto'), (4, 'Abril'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (11, 'Novembro'), (5, 'Maio'), (9, 'Setembro')]),
        ),
    ]
