# Generated by Django 4.0.1 on 2022-10-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0049_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='cidade_horigem',
            field=models.CharField(blank=True, max_length=255, verbose_name='Moradia'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (12, 'Dezembro'), (6, 'Junho'), (7, 'Julho'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (8, 'Agosto'), (10, 'Outubro'), (3, 'Março'), (4, 'Abril'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (12, 'Dezembro'), (6, 'Junho'), (7, 'Julho'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (8, 'Agosto'), (10, 'Outubro'), (3, 'Março'), (4, 'Abril'), (2, 'Fevereiro')]),
        ),
    ]
