# Generated by Django 4.0.1 on 2022-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0050_monitor_cidade_horigem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (4, 'Abril'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (3, 'Março'), (12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (4, 'Abril'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (3, 'Março'), (12, 'Dezembro'), (10, 'Outubro'), (9, 'Setembro'), (11, 'Novembro')]),
        ),
    ]
