# Generated by Django 4.0.1 on 2022-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0051_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (5, 'Maio'), (3, 'Março'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (5, 'Maio'), (3, 'Março'), (8, 'Agosto'), (4, 'Abril'), (7, 'Julho'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
    ]
