# Generated by Django 4.0.1 on 2022-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0052_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosapp',
            name='cliente_pf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='cliente_pj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='evento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='reserva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (1, 'Janeiro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (12, 'Dezembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (1, 'Janeiro'), (2, 'Fevereiro'), (11, 'Novembro'), (7, 'Julho')]),
        ),
    ]
