# Generated by Django 4.0.1 on 2022-11-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0053_alter_codigosapp_cliente_pf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='material_apoio',
            field=models.FileField(blank=True, null=True, upload_to='materiais_apoio/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (10, 'Outubro'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (10, 'Outubro'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (3, 'Março'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='monitoria',
            field=models.IntegerField(blank=True, choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20'), (3, 'Monitoria completa (em quarto - 1/12)')], null=True),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='tipo_veiculo',
            field=models.IntegerField(blank=True, choices=[(1, 'Micro ônibus'), (2, 'Ônibus 46 lugares'), (3, 'Ônibus 50 lugares')], null=True),
        ),
    ]
