# Generated by Django 4.0.1 on 2022-11-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0054_fichadeevento_material_apoio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (6, 'Junho'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (2, 'Fevereiro'), (8, 'Agosto'), (6, 'Junho'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (3, 'Março')]),
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.grupoatividade'),
        ),
    ]
