# Generated by Django 4.0.1 on 2022-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0055_grupoatividade_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (6, 'Junho'), (4, 'Abril'), (10, 'Outubro'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho'), (3, 'Março'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (6, 'Junho'), (4, 'Abril'), (10, 'Outubro'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (2, 'Fevereiro'), (7, 'Julho'), (3, 'Março'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='atividades_peraltas',
            field=models.ManyToManyField(blank=True, to='peraltas.GrupoAtividade'),
        ),
    ]
