# Generated by Django 4.0.1 on 2022-11-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0056_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeseco',
            name='grupo',
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.grupoatividade'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (7, 'Julho'), (8, 'Agosto'), (11, 'Novembro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (7, 'Julho'), (8, 'Agosto'), (11, 'Novembro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (3, 'Março'), (2, 'Fevereiro')]),
        ),
    ]
