# Generated by Django 4.0.1 on 2022-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0058_remove_atividadeseco_tipo_atividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeseco',
            name='nivel_atividade',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (12, 'Dezembro'), (8, 'Agosto'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro'), (6, 'Junho'), (11, 'Novembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (12, 'Dezembro'), (8, 'Agosto'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro'), (6, 'Junho'), (11, 'Novembro'), (10, 'Outubro')]),
        ),
    ]
