# Generated by Django 4.0.1 on 2022-11-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0059_remove_atividadeseco_nivel_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigosapp',
            name='pagamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (5, 'Maio'), (10, 'Outubro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (1, 'Janeiro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (6, 'Junho'), (5, 'Maio'), (10, 'Outubro'), (8, 'Agosto'), (12, 'Dezembro'), (11, 'Novembro'), (1, 'Janeiro'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (2, 'Fevereiro')]),
        ),
    ]
