# Generated by Django 4.0.1 on 2022-11-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0060_codigosapp_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='horario_garantia',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (3, 'Março'), (1, 'Janeiro'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (2, 'Fevereiro'), (8, 'Agosto'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (9, 'Setembro'), (3, 'Março'), (1, 'Janeiro'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (2, 'Fevereiro'), (8, 'Agosto'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='enfermaria',
            field=models.IntegerField(choices=[(2, '8h às 22h'), (3, '8h às 8h (24h)'), (1, 'Sem enfermeira')], default=1),
        ),
    ]
