# Generated by Django 4.0.1 on 2022-11-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0061_remove_informacoesadcionais_horario_garantia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_embarque', models.CharField(max_length=255)),
                ('horario_embarque', models.TextField()),
                ('dados_veiculos', models.JSONField()),
                ('empresa_onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.empresaonibus')),
            ],
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='endereco_embarque',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='hora_embarque',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='tipo_veiculo',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='viacao',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (7, 'Julho'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (7, 'Julho'), (11, 'Novembro')]),
        ),
        migrations.DeleteModel(
            name='DadosSegurado',
        ),
    ]
