# Generated by Django 4.0.1 on 2022-11-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0062_dadostransporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='informacoes_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.dadostransporte'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (7, 'Julho'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março'), (8, 'Agosto'), (11, 'Novembro'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (4, 'Abril'), (7, 'Julho'), (9, 'Setembro'), (5, 'Maio'), (3, 'Março'), (8, 'Agosto'), (11, 'Novembro'), (10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
    ]
