# Generated by Django 4.0.1 on 2022-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0063_informacoesadcionais_informacoes_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostransporte',
            name='dados_veiculos',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (9, 'Setembro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (6, 'Junho'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (2, 'Fevereiro'), (12, 'Dezembro'), (9, 'Setembro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (8, 'Agosto'), (7, 'Julho'), (6, 'Junho'), (11, 'Novembro')]),
        ),
    ]
