# Generated by Django 4.0.1 on 2022-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0064_alter_dadostransporte_dados_veiculos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostransporte',
            name='horario_embarque',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (7, 'Julho'), (10, 'Outubro'), (5, 'Maio'), (8, 'Agosto'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
    ]
