# Generated by Django 4.0.1 on 2022-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0065_alter_dadostransporte_horario_embarque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecolegio',
            name='codigo_app_pf',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='codigo_app_pj',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (3, 'Março'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (3, 'Março'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (11, 'Novembro'), (7, 'Julho'), (6, 'Junho')]),
        ),
    ]
