# Generated by Django 4.0.1 on 2022-11-10 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0066_alter_clientecolegio_codigo_app_pf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecolegio',
            name='responsavel_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (9, 'Setembro'), (6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (9, 'Setembro'), (6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
    ]
