# Generated by Django 4.0.1 on 2022-11-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0067_clientecolegio_responsavel_alteracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeCargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro'), (8, 'Agosto'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (10, 'Outubro'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (2, 'Fevereiro'), (12, 'Dezembro'), (8, 'Agosto'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (10, 'Outubro'), (7, 'Julho'), (4, 'Abril'), (5, 'Maio')]),
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='cargo',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='cargo',
            field=models.ManyToManyField(to='peraltas.ListaDeCargos'),
        ),
    ]
