# Generated by Django 4.0.1 on 2022-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0068_listadecargos_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (6, 'Junho'), (4, 'Abril'), (8, 'Agosto'), (2, 'Fevereiro'), (10, 'Outubro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (6, 'Junho'), (4, 'Abril'), (8, 'Agosto'), (2, 'Fevereiro'), (10, 'Outubro'), (9, 'Setembro'), (3, 'Março'), (12, 'Dezembro'), (7, 'Julho'), (11, 'Novembro'), (5, 'Maio')]),
        ),
    ]
