# Generated by Django 4.0.1 on 2022-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0069_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (3, 'Março'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (11, 'Novembro'), (6, 'Junho'), (3, 'Março'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril')]),
        ),
    ]
