# Generated by Django 4.0.1 on 2022-11-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0070_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (12, 'Dezembro'), (10, 'Outubro'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (7, 'Julho'), (11, 'Novembro'), (3, 'Março'), (8, 'Agosto'), (1, 'Janeiro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (12, 'Dezembro'), (10, 'Outubro'), (2, 'Fevereiro'), (9, 'Setembro'), (6, 'Junho'), (7, 'Julho'), (11, 'Novembro'), (3, 'Março'), (8, 'Agosto'), (1, 'Janeiro'), (5, 'Maio')]),
        ),
    ]
