# Generated by Django 4.0.1 on 2022-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0072_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosapp',
            name='evento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='reserva',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (12, 'Dezembro'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (12, 'Dezembro'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (8, 'Agosto')]),
        ),
    ]
