# Generated by Django 4.0.1 on 2022-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0073_alter_codigosapp_evento_alter_codigosapp_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='enfermeiras',
            field=models.ManyToManyField(blank=True, related_name='enfermeiras', to='peraltas.Monitor'),
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='monitores_embarque',
            field=models.ManyToManyField(blank=True, related_name='monitores_embarque', to='peraltas.Monitor'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (12, 'Dezembro'), (1, 'Janeiro'), (9, 'Setembro'), (4, 'Abril'), (5, 'Maio'), (11, 'Novembro'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (12, 'Dezembro'), (1, 'Janeiro'), (9, 'Setembro'), (4, 'Abril'), (5, 'Maio'), (11, 'Novembro'), (3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='monitores_acampamento',
            field=models.ManyToManyField(related_name='monitores_acampamento', to='peraltas.Monitor'),
        ),
    ]
