# Generated by Django 4.0.1 on 2022-12-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0074_escalaacampamento_enfermeiras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (10, 'Outubro'), (3, 'Março'), (11, 'Novembro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (12, 'Dezembro'), (9, 'Setembro'), (7, 'Julho'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (10, 'Outubro'), (3, 'Março'), (11, 'Novembro'), (5, 'Maio')]),
        ),
        migrations.RemoveField(
            model_name='escalahotelaria',
            name='monitores_hotelaria',
        ),
        migrations.AddField(
            model_name='escalahotelaria',
            name='monitores_hotelaria',
            field=models.JSONField(null=True),
        ),
    ]
