# Generated by Django 4.0.1 on 2022-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0075_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalahotelaria',
            name='monitores_escalados',
            field=models.ManyToManyField(to='peraltas.Monitor'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (11, 'Novembro'), (9, 'Setembro'), (1, 'Janeiro'), (3, 'Março'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (5, 'Maio')]),
        ),
    ]
