# Generated by Django 4.0.1 on 2022-12-13 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0076_escalahotelaria_monitores_escalados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='data_final_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (10, 'Outubro'), (4, 'Abril'), (12, 'Dezembro'), (3, 'Março'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (10, 'Outubro'), (4, 'Abril'), (12, 'Dezembro'), (3, 'Março'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (8, 'Agosto'), (11, 'Novembro'), (2, 'Fevereiro')]),
        ),
    ]
