# Generated by Django 4.0.1 on 2022-12-13 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0077_fichadeevento_data_final_inscricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (10, 'Outubro'), (3, 'Março'), (7, 'Julho'), (2, 'Fevereiro'), (4, 'Abril'), (5, 'Maio'), (9, 'Setembro'), (11, 'Novembro'), (1, 'Janeiro'), (8, 'Agosto'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_final_inscricao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
