# Generated by Django 4.0.1 on 2022-12-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0078_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostransporte',
            name='dados_veiculos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadostransporte',
            name='empresa_onibus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.empresaonibus'),
        ),
        migrations.AlterField(
            model_name='dadostransporte',
            name='endereco_embarque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dadostransporte',
            name='horario_embarque',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (8, 'Agosto'), (7, 'Julho'), (2, 'Fevereiro'), (3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (8, 'Agosto'), (7, 'Julho'), (2, 'Fevereiro'), (3, 'Março'), (5, 'Maio'), (10, 'Outubro'), (6, 'Junho'), (1, 'Janeiro'), (12, 'Dezembro'), (11, 'Novembro'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_final_inscricao',
            field=models.DateField(blank=True),
        ),
    ]
