# Generated by Django 4.0.1 on 2022-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0079_alter_dadostransporte_dados_veiculos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (1, 'Janeiro'), (10, 'Outubro'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (2, 'Fevereiro'), (12, 'Dezembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(8, 'Agosto'), (1, 'Janeiro'), (10, 'Outubro'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (3, 'Março'), (2, 'Fevereiro'), (12, 'Dezembro')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_final_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
