# Generated by Django 4.0.1 on 2022-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0080_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='etiquetas_embarque',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='servico_bordo',
        ),
        migrations.AddField(
            model_name='produtosperaltas',
            name='hora_padrao_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtosperaltas',
            name='hora_padrao_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (12, 'Dezembro'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (5, 'Maio'), (7, 'Julho'), (2, 'Fevereiro'), (12, 'Dezembro'), (4, 'Abril'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março'), (11, 'Novembro')]),
        ),
    ]
