# Generated by Django 4.0.1 on 2022-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0081_remove_informacoesadcionais_etiquetas_embarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='cantina',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0),
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='roupa_de_cama',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (7, 'Julho'), (1, 'Janeiro'), (5, 'Maio'), (6, 'Junho'), (10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro')]),
        ),
    ]
