# Generated by Django 4.0.1 on 2022-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0082_informacoesadcionais_cantina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro'), (2, 'Fevereiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (4, 'Abril'), (11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro'), (2, 'Fevereiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='cantina',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=''),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='roupa_de_cama',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=''),
        ),
    ]
