# Generated by Django 4.0.1 on 2022-12-16 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0083_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (5, 'Maio'), (12, 'Dezembro'), (4, 'Abril'), (1, 'Janeiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (8, 'Agosto'), (10, 'Outubro'), (2, 'Fevereiro'), (5, 'Maio'), (12, 'Dezembro'), (4, 'Abril'), (1, 'Janeiro'), (3, 'Março')]),
        ),
        migrations.RemoveField(
            model_name='fichadeevento',
            name='produto',
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtosperaltas'),
            preserve_default=False,
        ),
    ]
