# Generated by Django 4.0.1 on 2022-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0084_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='transporte_fechado_internamente',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=0),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (11, 'Novembro'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (1, 'Janeiro'), (10, 'Outubro'), (12, 'Dezembro'), (8, 'Agosto'), (4, 'Abril'), (11, 'Novembro'), (9, 'Setembro'), (5, 'Maio'), (6, 'Junho'), (3, 'Março')]),
        ),
    ]
