# Generated by Django 4.0.1 on 2022-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0085_informacoesadcionais_transporte_fechado_internamente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='transporte_fechado_internamente',
        ),
        migrations.AddField(
            model_name='dadostransporte',
            name='transporte_fechado_internamente',
            field=models.IntegerField(blank=True, choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (12, 'Dezembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (4, 'Abril'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (12, 'Dezembro')]),
        ),
    ]
