# Generated by Django 4.0.1 on 2022-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0086_remove_informacoesadcionais_transporte_fechado_internamente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostransporte',
            name='transporte_fechado_internamente',
            field=models.IntegerField(blank=True, choices=[('', ''), (0, 'Não'), (1, 'Sim')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (2, 'Fevereiro'), (12, 'Dezembro'), (10, 'Outubro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (6, 'Junho'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (2, 'Fevereiro'), (12, 'Dezembro'), (10, 'Outubro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Peraltas', 'Peraltas'), ('CEU', 'Fundação CEU'), ('Peraltas CEU', 'Peraltas + Fundação CEU')], max_length=100, null=True),
        ),
    ]
