# Generated by Django 4.0.1 on 2022-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0087_alter_dadostransporte_transporte_fechado_internamente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (7, 'Julho'), (9, 'Setembro'), (12, 'Dezembro'), (2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(5, 'Maio'), (7, 'Julho'), (9, 'Setembro'), (12, 'Dezembro'), (2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (3, 'Março')]),
        ),
    ]
