# Generated by Django 4.0.1 on 2022-12-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0088_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_preenchimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
