# Generated by Django 4.0.1 on 2022-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0089_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='pre_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (11, 'Novembro'), (2, 'Fevereiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (12, 'Dezembro'), (1, 'Janeiro'), (4, 'Abril'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (9, 'Setembro'), (11, 'Novembro'), (2, 'Fevereiro'), (5, 'Maio'), (3, 'Março'), (7, 'Julho'), (12, 'Dezembro'), (1, 'Janeiro'), (4, 'Abril'), (6, 'Junho')]),
        ),
    ]
