# Generated by Django 4.0.1 on 2022-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0090_fichadeevento_agendado_fichadeevento_pre_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecolegio',
            name='codigo_app_pf',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='codigo_app_pj',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (7, 'Julho'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto')]),
        ),
    ]
