# Generated by Django 4.0.1 on 2022-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0091_alter_clientecolegio_codigo_app_pf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (11, 'Novembro'), (2, 'Fevereiro'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (6, 'Junho'), (7, 'Julho'), (4, 'Abril'), (11, 'Novembro'), (2, 'Fevereiro'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='professores_com_alunos',
            field=models.BooleanField(default=False),
        ),
    ]
