# Generated by Django 4.0.1 on 2022-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0092_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (10, 'Outubro'), (6, 'Junho'), (2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (4, 'Abril'), (5, 'Maio'), (11, 'Novembro'), (9, 'Setembro'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (3, 'Março'), (10, 'Outubro'), (6, 'Junho'), (2, 'Fevereiro'), (7, 'Julho'), (1, 'Janeiro'), (4, 'Abril'), (5, 'Maio'), (11, 'Novembro'), (9, 'Setembro'), (8, 'Agosto')]),
        ),
    ]
