# Generated by Django 4.0.1 on 2022-12-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0093_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (12, 'Dezembro'), (11, 'Novembro'), (8, 'Agosto'), (4, 'Abril'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (12, 'Dezembro'), (11, 'Novembro'), (8, 'Agosto'), (4, 'Abril'), (3, 'Março'), (6, 'Junho'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (10, 'Outubro'), (2, 'Fevereiro')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='informacoes_adcionais',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.informacoesadcionais'),
        ),
    ]
