# Generated by Django 4.0.1 on 2022-12-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0094_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (2, 'Fevereiro'), (4, 'Abril'), (6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (8, 'Agosto'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (12, 'Dezembro'), (5, 'Maio'), (2, 'Fevereiro'), (4, 'Abril'), (6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (3, 'Março'), (8, 'Agosto'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='informacoes_adcionais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.informacoesadcionais'),
        ),
    ]
