# Generated by Django 4.0.1 on 2022-12-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0095_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (1, 'Janeiro'), (9, 'Setembro'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (8, 'Agosto'), (12, 'Dezembro'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Enfermeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('pode_pernoitar', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
