# Generated by Django 4.0.1 on 2022-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0096_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (8, 'Agosto'), (3, 'Março'), (11, 'Novembro'), (7, 'Julho'), (12, 'Dezembro'), (2, 'Fevereiro'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (1, 'Janeiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (8, 'Agosto'), (3, 'Março'), (11, 'Novembro'), (7, 'Julho'), (12, 'Dezembro'), (2, 'Fevereiro'), (5, 'Maio'), (4, 'Abril'), (9, 'Setembro'), (1, 'Janeiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='enfermeiras',
            field=models.ManyToManyField(blank=True, related_name='enfermeiras', to='peraltas.Enfermeira'),
        ),
    ]
