# Generated by Django 4.0.1 on 2022-12-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0097_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='ficha_de_evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.fichadeevento'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (11, 'Novembro'), (3, 'Março'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (4, 'Abril'), (1, 'Janeiro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (11, 'Novembro'), (3, 'Março'), (9, 'Setembro'), (8, 'Agosto'), (12, 'Dezembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
        ),
    ]
