# Generated by Django 4.0.1 on 2022-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0098_escalaacampamento_ficha_de_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (8, 'Agosto'), (4, 'Abril'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (5, 'Maio'), (3, 'Março'), (1, 'Janeiro'), (6, 'Junho'), (11, 'Novembro'), (7, 'Julho'), (9, 'Setembro'), (8, 'Agosto'), (4, 'Abril'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
        migrations.DeleteModel(
            name='PreReserva',
        ),
    ]
