# Generated by Django 4.0.1 on 2023-01-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0100_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='setor',
            field=models.CharField(choices=[('ceu', 'CEU'), ('peraltas', 'Peraltas')], default='ceu', max_length=8),
            preserve_default=False,
        ),
    ]
