# Generated by Django 4.0.1 on 2023-01-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0101_escalaacampamento_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='vendedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
        ),
    ]
