# Generated by Django 4.0.1 on 2023-01-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0102_alter_fichadeevento_vendedora'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecolegio',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
