# Generated by Django 4.0.1 on 2023-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0103_clientecolegio_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosperaltas',
            name='n_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias de duração'),
        ),
    ]
