# Generated by Django 4.0.1 on 2023-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0104_produtosperaltas_n_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='obs_edicao_horario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtosperaltas',
            name='n_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de pernoites'),
        ),
    ]
