# Generated by Django 4.0.1 on 2023-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0105_fichadeevento_obs_edicao_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='informacoes_transporte',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='lista_segurados',
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='transporte_fechado_internamente',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=0),
        ),
    ]
