# Generated by Django 4.0.1 on 2023-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0012_remove_ordemdeservico_nome_motorista_and_more'),
        ('peraltas', '0106_remove_informacoesadcionais_informacoes_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='transporte_fechado_internamente',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=''),
        ),
        migrations.DeleteModel(
            name='DadosTransporte',
        ),
    ]
