# Generated by Django 4.0.1 on 2023-01-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0107_alter_informacoesadcionais_transporte_fechado_internamente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoatividade',
            name='obrigatoria',
            field=models.BooleanField(default=False),
        ),
    ]
