# Generated by Django 4.0.1 on 2023-01-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0108_grupoatividade_obrigatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='transporte_fechado_internamente',
            field=models.IntegerField(blank=True, choices=[('', ''), (0, 'Não'), (1, 'Sim')], default='', null=True),
        ),
    ]
