# Generated by Django 4.0.1 on 2023-01-31 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0109_alter_informacoesadcionais_transporte_fechado_internamente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('pernoite', models.BooleanField(default=True)),
                ('n_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de pernoites')),
            ],
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_preenchimento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_convidada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade reservada'),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='produto_corporativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.produtocorporativo'),
        ),
    ]
