# Generated by Django 4.0.1 on 2023-01-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0110_produtocorporativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='atividades_ceu_a_definir',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='informacoes_locacoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='vendedora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peraltas.vendedor'),
            preserve_default=False,
        ),
    ]
