# Generated by Django 4.0.1 on 2023-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0111_fichadeevento_atividades_ceu_a_definir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocorporativo',
            name='hora_padrao_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtocorporativo',
            name='hora_padrao_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
