# Generated by Django 4.0.1 on 2023-02-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0112_produtocorporativo_hora_padrao_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecolegio',
            name='responsavel_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_cadastro_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='responsavel_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_atualizacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='responsavel_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_cadastro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='responsavel_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel_alteracao', to=settings.AUTH_USER_MODEL),
        ),
    ]
