# Generated by Django 4.0.1 on 2023-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0113_clientecolegio_responsavel_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='exclusividade',
            field=models.BooleanField(default=False),
        ),
    ]
