# Generated by Django 4.0.1 on 2023-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0114_fichadeevento_exclusividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='link_foto',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=0),
        ),
    ]
