# Generated by Django 4.0.1 on 2023-02-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0115_informacoesadcionais_link_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='link_foto',
            field=models.IntegerField(choices=[('', ''), (0, 'Não'), (1, 'Sim')], default=''),
        ),
        migrations.CreateModel(
            name='EventosCancelados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('cnpj_cliente', models.CharField(max_length=18)),
                ('estagio_evento', models.CharField(choices=[('pre_reserva', 'Pré reserva'), ('reserva_confirmada', 'Reserva confirmada'), ('ficha_evento', 'Ficha de evento'), ('ordem_servico', 'Ordem de serviço')], max_length=20)),
                ('atendente', models.CharField(max_length=50)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('motivo_cancelamento', models.TextField()),
                ('produto_contratado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtosperaltas')),
            ],
        ),
    ]
