# Generated by Django 4.0.1 on 2023-02-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0116_alter_informacoesadcionais_link_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscancelados',
            name='produto_corporativo_contratado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtocorporativo'),
        ),
    ]
