# Generated by Django 4.0.1 on 2023-03-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0117_eventoscancelados_produto_corporativo_contratado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLimitePeraltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_limite_peraltas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadePeraltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_disponiveis', models.TextField(max_length=500)),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('ano', models.CharField(max_length=20)),
                ('n_dias', models.IntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor')),
            ],
        ),
        migrations.DeleteModel(
            name='DiaLimiteAcampamento',
        ),
        migrations.DeleteModel(
            name='DiaLimiteHotelaria',
        ),
        migrations.RemoveField(
            model_name='disponibilidadehotelaria',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='escalaacampamento',
            name='setor',
        ),
        migrations.DeleteModel(
            name='DisponibilidadeAcampamento',
        ),
        migrations.DeleteModel(
            name='DisponibilidadeHotelaria',
        ),
    ]
