# Generated by Django 4.0.1 on 2023-03-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0118_dialimiteperaltas_disponibilidadeperaltas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
