# Generated by Django 4.0.1 on 2023-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0119_monitor_valor_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
