# Generated by Django 4.0.1 on 2023-03-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0120_alter_monitor_valor_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadeperaltas',
            name='enfermeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.enfermeira'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeperaltas',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.monitor'),
        ),
    ]
