# Generated by Django 4.0.1 on 2023-03-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0121_disponibilidadeperaltas_enfermeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='professores_com_alunos',
            field=models.BooleanField(),
        ),
    ]
