# Generated by Django 4.0.1 on 2023-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0122_alter_fichadeevento_professores_com_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='professores_com_alunos',
            field=models.BooleanField(default=False),
        ),
    ]
