# Generated by Django 4.0.1 on 2023-03-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0123_alter_fichadeevento_professores_com_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecolegio',
            name='codigo_app_pf',
        ),
    ]
