# Generated by Django 4.0.1 on 2023-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0124_remove_clientecolegio_codigo_app_pf'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='ida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='lanche_bordo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='volta',
            field=models.BooleanField(default=False),
        ),
    ]
