# Generated by Django 4.0.1 on 2023-04-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0125_informacoesadcionais_ida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='biologo',
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='biologos',
            field=models.ManyToManyField(blank=True, related_name='biologos', to='peraltas.Monitor'),
        ),
    ]
