# Generated by Django 4.0.1 on 2023-04-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0126_remove_informacoesadcionais_biologo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='racional_coordenadores',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='racional_monitores',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
