# Generated by Django 4.0.1 on 2023-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0127_escalaacampamento_racional_coordenadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='permicao_coordenadores',
            field=models.BooleanField(default=False, verbose_name='Permitir 3 coordenadores'),
        ),
    ]
