# Generated by Django 4.0.1 on 2023-04-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0128_escalaacampamento_permicao_coordenadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='fixo',
            field=models.BooleanField(default=False),
        ),
    ]
