# Generated by Django 4.0.1 on 2023-04-13 01:37
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('peraltas', '0129_monitor_fixo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaacampamento',
            name='check_in_cliente',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='escalaacampamento',
            name='check_out_cliente',
            field=models.DateTimeField(),
        ),
        ############################################
        migrations.AddField(
            model_name='fichadeevento',
            name='data_preenchimento',
            field=models.DateField(blank=True, null=True, default=datetime.date.today),
        ),
        migrations.RenameField(
            model_name='fichadeevento',
            old_name='data_preenchimento',
            new_name='data_preenchimento_pre_reserva',
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='data_confirmacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='data_preenchimento_ficha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='fichadeevento',
            old_name='data_preenchimento_pre_reserva',
            new_name='data_preenchimento',
        ),
        migrations.RemoveField(
            model_name='fichadeevento',
            name='data_confirmacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='fichadeevento',
            name='data_preenchimento_ficha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
