# Generated by Django 4.0.1 on 2023-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0130_alter_escalaacampamento_check_in_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='outro_produto',
        ),
        migrations.AddField(
            model_name='produtosperaltas',
            name='brotas_eco',
            field=models.BooleanField(default=False),
        ),
    ]
