# Generated by Django 4.0.1 on 2023-04-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0131_remove_fichadeevento_outro_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalaacampamento',
            name='permicao_coordenadores',
        ),
        migrations.RemoveField(
            model_name='escalaacampamento',
            name='racional_coordenadores',
        ),
    ]
