# Generated by Django 4.0.1 on 2023-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0132_remove_escalaacampamento_permicao_coordenadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeira',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='enfermeira',
            name='valor_pernoite',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='valor_diaria_biologo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='valor_diaria_coordenacao',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
