# Generated by Django 4.0.1 on 2023-04-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0133_enfermeira_valor_diaria_enfermeira_valor_pernoite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='pre_escala',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='ultima_pre_reserva',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
