# Generated by Django 4.0.1 on 2023-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0134_escalaacampamento_pre_escala_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escalaacampamento',
            old_name='ultima_pre_reserva',
            new_name='ultima_pre_escala',
        ),
        migrations.AddField(
            model_name='escalahotelaria',
            name='pre_escala',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escalahotelaria',
            name='ultima_pre_escala',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
