# Generated by Django 4.0.1 on 2023-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0135_rename_ultima_pre_reserva_escalaacampamento_ultima_pre_escala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='peraltas.Monitor'),
        ),
    ]
