# Generated by Django 4.0.1 on 2023-04-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0136_escalaacampamento_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalahotelaria',
            name='coodenadores',
            field=models.ManyToManyField(blank=True, related_name='coodendadores', to='peraltas.Monitor'),
        ),
    ]
