# Generated by Django 4.0.1 on 2023-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0137_escalahotelaria_coodenadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalahotelaria',
            name='tecnicos_hotelaria',
            field=models.ManyToManyField(blank=True, related_name='tecnicos_hotelaria', to='peraltas.Monitor'),
        ),
    ]
