# Generated by Django 4.0.1 on 2023-05-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0138_escalahotelaria_tecnicos_hotelaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalahotelaria',
            name='coodenadores',
        ),
        migrations.AddField(
            model_name='escalahotelaria',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, related_name='coordendadores', to='peraltas.Monitor'),
        ),
    ]
