# Generated by Django 4.0.1 on 2023-05-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0023_ordemdeservico_data_preenchimento'),
        ('peraltas', '0139_remove_escalahotelaria_coodenadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha_de_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.fichadeevento')),
                ('ordem_de_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordemDeServico.ordemdeservico')),
            ],
        ),
    ]
