# Generated by Django 4.0.1 on 2023-05-14 14:28

from django.db import migrations

from ordemDeServico.models import OrdemDeServico
from peraltas.models import Eventos, FichaDeEvento


def popular_eventos(apps, schema_editor):
    fichas = apps.get_model('peraltas', 'FichaDeEvento')

    for ficha_bd in fichas.objects.iterator():
        ficha = FichaDeEvento.objects.get(id=ficha_bd.id)

        try:
            ordem = OrdemDeServico.objects.get(ficha_de_evento=ficha)
        except OrdemDeServico.DoesNotExist:
            evento = Eventos.objects.create(ficha_de_evento=ficha)
        else:
            evento = Eventos.objects.create(
                ordem_de_servico=ordem,
                ficha_de_evento=ficha
            )

        evento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0140_eventos'),
    ]

    operations = [
        migrations.RunPython(popular_eventos)
    ]
