# Generated by Django 4.0.1 on 2023-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0141_auto_20230514_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='observacoes',
            field=models.TextField(null=True),
        ),
    ]
