# Generated by Django 4.0.1 on 2023-05-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0142_alter_eventos_options_escalaacampamento_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
