# Generated by Django 4.0.1 on 2023-05-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0143_codigospadrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='aceite_do_termo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
