# Generated by Django 4.0.1 on 2023-05-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0023_ordemdeservico_data_preenchimento'),
        ('peraltas', '0144_monitor_aceite_do_termo_vendedor_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='ordem_de_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordemDeServico.ordemdeservico'),
        ),
    ]
