# Generated by Django 4.0.1 on 2023-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0146_alter_eventos_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='atividades_ceu_a_definir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Atividades CEU a definir'),
        ),
    ]
