# Generated by Django 4.0.1 on 2023-06-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0147_alter_fichadeevento_atividades_ceu_a_definir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_preenchimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
