# Generated by Django 4.0.1 on 2023-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0148_alter_fichadeevento_data_preenchimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='reversion_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
