# Generated by Django 4.0.1 on 2023-06-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0149_fichadeevento_reversion_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='reversion_start_date',
        ),
    ]
