# Generated by Django 4.0.1 on 2023-06-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0150_remove_fichadeevento_reversion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_preenchimento',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
