# Generated by Django 4.0.1 on 2023-06-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0026_delete_detectordebombas'),
        ('peraltas', '0151_alter_fichadeevento_data_preenchimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='agendado',
            field=models.BooleanField(default=False, verbose_name='Agendado'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='atividades_ceu',
            field=models.ManyToManyField(blank=True, to='ceu.Atividades', verbose_name='Atividades CEU'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='atividades_eco',
            field=models.ManyToManyField(blank=True, to='peraltas.AtividadesEco', verbose_name='Atividades extra'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='atividades_peraltas',
            field=models.ManyToManyField(blank=True, to='peraltas.GrupoAtividade', verbose_name='Atividades Peraltas'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='check_in',
            field=models.DateTimeField(verbose_name='Check in'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='check_out',
            field=models.DateTimeField(verbose_name='Check out'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='codigos_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.codigosapp', verbose_name='Códigos APP'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_final_inscricao',
            field=models.DateField(blank=True, null=True, verbose_name='Data final da inscrição'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='data_preenchimento',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Data de preenchimento'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Peraltas', 'Peraltas'), ('CEU', 'Fundação CEU'), ('Peraltas CEU', 'Peraltas + Fundação CEU')], max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='escala',
            field=models.BooleanField(default=False, verbose_name='Escala'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='exclusividade',
            field=models.BooleanField(default=False, verbose_name='Exclusividade'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='ficha_financeira',
            field=models.BooleanField(default=False, verbose_name='Ficha financeira'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='informacoes_adcionais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.informacoesadcionais', verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='informacoes_locacoes',
            field=models.JSONField(blank=True, null=True, verbose_name='Informações de locações'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='locacoes_ceu',
            field=models.ManyToManyField(blank=True, to='ceu.Locaveis', verbose_name='Locações no CEU'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='material_apoio',
            field=models.FileField(blank=True, null=True, upload_to='materiais_apoio/%Y/%m/%d', verbose_name='Material de apoio'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='obs_edicao_horario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação da edição do horário'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='observacoes_refeicoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações das refeições'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='os',
            field=models.BooleanField(default=False, verbose_name='Ordem de serviço'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='perfil_participantes',
            field=models.ManyToManyField(blank=True, to='peraltas.PerfilsParticipantes', verbose_name='Perfíl dos participantes'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='pre_reserva',
            field=models.BooleanField(default=False, verbose_name='Pré reserva'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtosperaltas', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='produto_corporativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.produtocorporativo', verbose_name='Produto corporativo'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='professores_com_alunos',
            field=models.BooleanField(default=False, verbose_name='Professores dormirão com alunos?'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_confirmada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade confirmada'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_homens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de homens'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_meninas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de meninas'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_meninos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de menino'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_mulheres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de mulheres'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_professores',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de professores'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_profs_homens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de professores homens'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_profs_mulheres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de professores mulheres'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='refeicoes',
            field=models.JSONField(blank=True, null=True, verbose_name='Refeições'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='responsavel_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.responsavel', verbose_name='Responsável pelo evento'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='vendedora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.vendedor', verbose_name='Vendedora'),
        ),
    ]
