# Generated by Django 4.0.1 on 2023-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0152_alter_fichadeevento_agendado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='data_divulgacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista para divulgação'),
        ),
    ]
