# Generated by Django 4.0.1 on 2023-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0153_fichadeevento_data_divulgacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscancelados',
            name='participantes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='tipo_evento',
            field=models.CharField(choices=[('colegio', 'Colégio'), ('corporativo', 'Corporativo')], default='colegio', max_length=12),
            preserve_default=False,
        ),
    ]
