# Generated by Django 4.0.1 on 2023-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0154_atividadeperaltas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeseco',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
