# Generated by Django 4.0.1 on 2023-08-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0154_eventoscancelados_participantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscancelados',
            name='data_evento',
            field=models.DateField(default='2023-03-08'),
            preserve_default=False,
        ),
    ]
