# Generated by Django 4.0.1 on 2023-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0155_eventoscancelados_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='agencia',
            field=models.BooleanField(default=False),
        ),
    ]
