# Generated by Django 4.0.1 on 2023-10-15 21:20

from django.db import migrations, models


def calcular_adesao(apps, schema_editor):
    fichas = apps.get_model('peraltas', 'FichaDeEvento')

    for ficha in fichas.objects.all():
        estimada = ficha.qtd_convidada if ficha.qtd_convidada and ficha.qtd_convidada > 0 else 1
        reservada = ficha.qtd_confirmada if ficha.qtd_confirmada and ficha.qtd_confirmada >= 0 else 0
        ficha.adesao = (reservada / estimada) * 100
        ficha.save()


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0156_fichadeevento_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='adesao',
            field=models.FloatField(blank=True, null=True, verbose_name='Adesão'),
        ),
        migrations.RunPython(calcular_adesao)
    ]
