# Generated by Django 4.0.1 on 2023-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0157_fichadeevento_adesao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='codigosapp',
            old_name='pagamento',
            new_name='evento_app',
        ),
        migrations.AddField(
            model_name='codigosapp',
            name='ficha_financeira',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codigosapp',
            name='tipo_de_pagamento',
            field=models.ManyToManyField(blank=True, to='peraltas.TiposPagamentos'),
        ),
    ]
