# Generated by Django 4.0.1 on 2023-10-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0158_tipospagamentos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigosapp',
            old_name='evento',
            new_name='eficha',
        ),
    ]
