# Generated by Django 4.0.1 on 2023-10-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0160_fichadeevento_id_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_eficha',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade E-ficha'),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_offline',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade offline'),
        ),
        migrations.AddField(
            model_name='tipospagamentos',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
