# Generated by Django 4.0.1 on 2023-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0161_fichadeevento_qtd_eficha_fichadeevento_qtd_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosapp',
            name='evento_app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='ficha_financeira',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
