# Generated by Django 4.0.1 on 2023-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0162_alter_codigosapp_evento_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosperaltas',
            name='meninos_e_meninas',
            field=models.BooleanField(default=False),
        ),
    ]
