# Generated by Django 4.0.1 on 2024-01-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0155_atividadeseco_valor'),
        ('peraltas', '0163_produtosperaltas_meninos_e_meninas'),
    ]

    operations = [
    ]
