# Generated by Django 4.0.1 on 2025-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0164_merge_20240128_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='whats',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='fone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
