# Generated by Django 4.0.1 on 2024-03-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0164_merge_20240128_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='monitoria',
            field=models.IntegerField(blank=True, choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20'), (3, 'Monitoria completa (em quarto - 1/12)'), (4, 'Monitoria completa (fora do quarto - 1/12')], null=True),
        ),
    ]
