# Generated by Django 4.0.1 on 2024-04-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0165_tipoaividadeperaltas_atividadeseco_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeseco',
            name='intencao_atividade',
            field=models.CharField(choices=[('lazer', 'Lazer'), ('estudo', 'Estudo')], default='estudo', max_length=6, verbose_name='Intenção da atividade'),
        ),
    ]
