# Generated by Django 4.0.1 on 2025-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_tipospagamentos_and_more'),
        ('peraltas', '0165_responsavel_whats_alter_responsavel_fone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiposPagamentos',
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='tipo_de_pagamento',
            field=models.ManyToManyField(blank=True, to='financeiro.TiposPagamentos'),
        ),
    ]
