# Generated by Django 4.0.1 on 2024-04-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0166_atividadeseco_intencao_atividade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoAividadePeraltas',
            new_name='TipoAtividadePeraltas',
        ),
    ]
