# Generated by Django 4.0.1 on 2024-04-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0166_eventoscancelados_colaborador_excluiu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalaacampamento',
            options={'permissions': (('confirmar_escala', 'Confirmar Escala'),)},
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='agendado',
            field=models.BooleanField(default=False, verbose_name='Evento confirmado'),
        ),
    ]
