# Generated by Django 4.0.1 on 2024-05-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0167_rename_tipoaividadeperaltas_tipoatividadeperaltas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255, verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='IntencaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencao', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='atividadeseco',
            name='tipo_atividade',
        ),
        migrations.RemoveField(
            model_name='atividadeseco',
            name='intencao_atividade',
        ),
        migrations.DeleteModel(
            name='TipoAtividadePeraltas',
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='peraltas.Disciplinas'),
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='intencao_atividade',
            field=models.ManyToManyField(blank=True, to='peraltas.IntencaoAtividade'),
        ),
    ]
