# Generated by Django 4.0.1 on 2024-05-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0168_disciplinas_intencaoatividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeseco',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='disciplina_primaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disciplina_primaria_peraltas', to='peraltas.disciplinas', verbose_name='Disciplina primaria'),
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='disciplinas_secundarias',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_secundarias_peraltas', to='peraltas.Disciplinas', verbose_name='Disciplinas secundárias'),
        ),
    ]
