# Generated by Django 4.0.1 on 2024-06-04 05:10

from django.db import migrations, models


def separar_data_hora(apps, schema_editor):
    Eventos = apps.get_model('peraltas', 'Eventos')

    for evento in Eventos.objects.all():
        ficha = evento.ficha_de_evento
        ordem = evento.ordem_de_servico

        if ordem:
            evento.data_check_in = ordem.check_in.date()
            evento.hora_check_in = ordem.check_in.time()
            evento.data_check_out = ordem.check_out.date()
            evento.hora_check_out = ordem.check_out.time()
        else:
            evento.data_check_in = ficha.check_in.date()
            evento.hora_check_in = ficha.check_in.time()
            evento.data_check_out = ficha.check_out.date()
            evento.hora_check_out = ficha.check_out.time()

        evento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0168_eventos_adesao_eventos_check_in_eventos_check_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='check_out',
        ),
        migrations.AddField(
            model_name='eventos',
            name='data_check_in',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='data_check_out',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_check_in',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora_check_out',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.RunPython(separar_data_hora),
    ]
