# Generated by Django 4.0.1 on 2024-05-11 22:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0169_remove_atividadeseco_disciplinas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas',
            name='cor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
