# Generated by Django 4.0.1 on 2024-06-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0025_auto_20231020_2158'),
        ('peraltas', '0169_remove_eventos_check_in_remove_eventos_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='ordem_de_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordemDeServico.ordemdeservico'),
        ),
    ]
