# Generated by Django 4.0.1 on 2024-07-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0170_alter_eventos_ordem_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='adesao',
            field=models.FloatField(default=0.0, verbose_name='Adesão'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='codigo_pagamento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Código de pagamento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_check_in',
            field=models.DateField(verbose_name='Data de check in'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_check_out',
            field=models.DateField(verbose_name='Data de check out'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_preenchimento',
            field=models.DateField(verbose_name='Data de preenchimento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='dias_evento',
            field=models.IntegerField(verbose_name='Dias de evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='estagio_evento',
            field=models.CharField(choices=[('pre_reserva', 'Pré reserva'), ('confirmado', 'Evento confirmado'), ('ficha_evento', 'Ficha de evento'), ('ordem_servico', 'Ordem de serviço')], max_length=25, verbose_name='Estágio do evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ficha_de_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.fichadeevento', verbose_name='Ficha de evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_check_in',
            field=models.TimeField(verbose_name='Hora de check in'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='hora_check_out',
            field=models.TimeField(verbose_name='Hora de check out'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='produto_corporativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtocorporativo', verbose_name='Produto Corporativo'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='produto_peraltas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtosperaltas', verbose_name='Produto Peraltas'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='qtd_confirmado',
            field=models.IntegerField(verbose_name='QTD confirmado'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='qtd_previa',
            field=models.IntegerField(verbose_name='QTD reservado'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tipo_evento',
            field=models.CharField(max_length=25, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='veio_ano_anterior',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Veio no ano anterior'),
        ),
    ]
