# Generated by Django 4.0.1 on 2024-05-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0170_disciplinas_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadeseco',
            old_name='disciplinas_secundarias',
            new_name='disciplinas',
        ),
    ]
