# Generated by Django 4.0.1 on 2024-07-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0171_alter_eventos_adesao_alter_eventos_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoscancelados',
            old_name='data_evento',
            new_name='data_check_in_evento',
        ),
        migrations.RenameField(
            model_name='eventoscancelados',
            old_name='participantes',
            new_name='participantes_confirmados',
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='adesao',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='codigo_pagamento',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='data_check_out_evento',
            field=models.DateField(default='2024-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='hora_check_in_evento',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='hora_check_out_evento',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='participantes_reservados',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoscancelados',
            name='veio_ano_anterior',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
            preserve_default=False,
        ),
    ]
