# Generated by Django 4.0.1 on 2024-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0171_rename_disciplinas_secundarias_atividadeseco_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeseco',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_secundarias_peraltas', to='peraltas.Disciplinas', verbose_name='Disciplinas trabalhadas'),
        ),
    ]
