# Generated by Django 4.0.1 on 2024-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0172_rename_data_evento_eventoscancelados_data_check_in_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscancelados',
            name='dias_evento',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventoscancelados',
            name='veio_ano_anterior',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
