# Generated by Django 4.0.1 on 2024-08-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0173_eventoscancelados_dias_evento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'permissions': [('ver_relatorios_eventos', 'Relatório de eventos')], 'verbose_name_plural': 'Eventos'},
        ),
    ]
