# Generated by Django 4.0.1 on 2024-08-28 13:48

from django.db import migrations, models
import django.db.models.deletion
import peraltas.models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0175_alter_fichadeevento_vendedora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='colaborador',
            field=models.ForeignKey(default=peraltas.models.atribuir_diretoria_vendedor, on_delete=django.db.models.deletion.SET_DEFAULT, to='peraltas.vendedor', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='vendedora',
            field=models.ForeignKey(default=peraltas.models.atribuir_diretoria_vendedor, on_delete=django.db.models.deletion.SET_DEFAULT, to='peraltas.vendedor', verbose_name='Vendedora'),
        ),
    ]
