# Generated by Django 4.0.1 on 2024-08-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0176_alter_eventos_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecolegio',
            name='responsavel_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_alteracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='responsavel_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_cadastro_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
