# Generated by Django 4.0.1 on 2024-08-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0177_alter_clientecolegio_responsavel_alteracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='responsavel_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_atualizacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='responsavel_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_cadastro', to=settings.AUTH_USER_MODEL),
        ),
    ]
