# Generated by Django 4.0.1 on 2024-09-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0179_alter_eventoscancelados_colaborador_excluiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelmonitoria',
            name='coordenacao',
            field=models.BooleanField(default=False),
        ),
    ]
