# Generated by Django 4.0.1 on 2024-09-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0180_nivelmonitoria_coordenacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='fotos_e_filmagens',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='som',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='video',
        ),
    ]
