# Generated by Django 4.0.1 on 2024-09-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0181_remove_monitor_fotos_e_filmagens_remove_monitor_som_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='nivel',
        ),
        migrations.AddField(
            model_name='monitor',
            name='nivel_acampamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_acampamento', to='peraltas.nivelmonitoria'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='nivel_corporativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_corporativo', to='peraltas.nivelmonitoria'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='nivel_hotelaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_hotelaria', to='peraltas.nivelmonitoria'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='nivel_tecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nivel_tecnica', to='peraltas.nivelmonitoria'),
        ),
    ]
