# Generated by Django 4.0.1 on 2024-09-28 19:53

from django.db import migrations, models


def criar_setores_base(apps, schema_editor):
    Setores = apps.get_model('peraltas', 'SetorMonitoria')
    setores_base = [
        Setores(setor='Acampamento'),
        Setores(setor='Hotelaria'),
        Setores(setor='Corporativo'),
        Setores(setor='Técnica')
    ]
    Setores.objects.bulk_create(setores_base)


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0182_remove_monitor_nivel_monitor_nivel_acampamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(criar_setores_base)
    ]
