# Generated by Django 4.0.1 on 2024-09-28 20:04

from django.db import migrations, models
import django.db.models.deletion
import peraltas.models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0183_setormonitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelmonitoria',
            name='setor_monitoria',
            field=models.ForeignKey(default=peraltas.models.get_first_setor_monitoria, on_delete=django.db.models.deletion.CASCADE, to='peraltas.setormonitoria'),
        ),
    ]
