# Generated by Django 4.0.1 on 2024-09-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0184_nivelmonitoria_setor_monitoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='nivel_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.nivelmonitoria', verbose_name='Nível da atividade'),
        ),
    ]
