# Generated by Django 4.0.1 on 2024-10-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0186_alter_atividadeperaltas_nivel_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeira',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peraltas.nivelmonitoria'),
        ),
    ]
