# Generated by Django 4.0.1 on 2024-10-30 12:11

from django.db import migrations, models
import django.db.models.deletion


def popular_novos_campos(apps, schema_editor):
    Eventos = apps.get_model('peraltas', 'Eventos')

    for evento in Eventos.objects.all():
        evento.cnpj = evento.cliente.cnpj
        evento.responsavel = evento.ficha_de_evento.responsavel_evento
        cargos = ', '.join([c.cargo for c in evento.responsavel.cargo.all()])
        evento.cargo_responsavel = cargos
        evento.telefone_responsavel = evento.responsavel.fone
        evento.email_responsavel = evento.responsavel.email_responsavel_evento
        evento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0187_enfermeira_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='cargo_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo responsável'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='email_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email responsável'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peraltas.responsavel', verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telefone responsável'),
        ),
        migrations.RunPython(popular_novos_campos)
    ]
