# Generated by Django 4.0.1 on 2024-10-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0188_eventos_cargo_responsavel_eventos_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='email_responsavel',
            field=models.CharField(max_length=255, verbose_name='email responsável'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.responsavel', verbose_name='Responsavel'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='telefone_responsavel',
            field=models.CharField(max_length=255, verbose_name='telefone responsável'),
        ),
    ]
