# Generated by Django 4.0.1 on 2024-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0189_alter_eventos_cnpj_alter_eventos_email_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='observacoes_refeicoes',
            field=models.TextField(default=' ', verbose_name='Observações das refeições'),
            preserve_default=False,
        ),
    ]
