# Generated by Django 4.0.1 on 2024-12-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0190_alter_fichadeevento_observacoes_refeicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocorporativo',
            name='brotas_eco',
            field=models.BooleanField(default=0),
        ),
    ]
