# Generated by Django 4.0.1 on 2025-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0191_produtocorporativo_brotas_eco'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaacampamento',
            name='avaliou_coordenadores',
            field=models.ManyToManyField(blank=True, related_name='avaliou_coordenadores', to='peraltas.Monitor'),
        ),
    ]
