# Generated by Django 4.0.1 on 2025-05-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0191_produtocorporativo_brotas_eco'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcoesProfessoresEmQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='professores_em_quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.opcoesprofessoresemquarto'),
        ),
    ]
