# Generated by Django 4.0.1 on 2025-05-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0192_opcoesprofessoresemquarto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='professores_com_alunos',
        ),
    ]
