# Generated by Django 4.0.1 on 2025-05-23 01:45

from django.db import migrations, models


def popula_professores_dormem_em_quarto(apps, schema_editor):
    InformacoesAdcionais = apps.get_model('peraltas', 'InformacoesAdcionais')
    ids_para_ativar = [
        121, 359, 378, 95, 55, 276, 56, 342, 129, 40, 240, 275, 198, 120, 242,
        222, 114, 283, 183, 163, 207, 210, 197, 181, 190, 267, 317, 367, 291,
        305, 341, 313, 375, 540, 509, 366, 390, 362, 409, 384, 383, 722, 548,
        672, 537, 460, 634, 747, 556, 735, 531, 547, 549, 728, 561, 727, 806,
        536, 849, 668, 587, 717, 632
    ]
    InformacoesAdcionais.objects.filter(id__in=ids_para_ativar).update(professores_dormem_em_quarto=True)


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0193_remove_fichadeevento_professores_com_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='professores_dormem_em_quarto',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(popula_professores_dormem_em_quarto),
    ]
