# Generated by Django 4.0.1 on 2025-05-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0192_escalaacampamento_avaliou_coordenadores'),
        ('peraltas', '0194_informacoesadcionais_professores_dormem_em_quarto'),
    ]

    operations = [
    ]
