# Generated by Django 4.0.1 on 2025-07-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0166_delete_tipospagamentos_and_more'),
        ('peraltas', '0195_merge_20250530_0053'),
    ]

    operations = [
    ]
