# Generated by Django 4.0.1 on 2025-07-31 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0162_orcamento_motivo_recusa_alter_orcamento_obs_recusa'),
        ('peraltas', '0196_merge_20250722_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamento.orcamento', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='fichadeevento',
            name='ficha_financeira',
        ),
    ]
