# Generated by Django 4.0.1 on 2025-07-31 18:47
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0030_alter_fichafinanceira_options'),
        ('peraltas', '0197_fichadeevento_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='ficha_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.fichafinanceira'),
        ),
    ]
