# Generated by Django 4.0.1 on 2025-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0198_fichadeevento_ficha_financeira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichadeevento',
            options={'permissions': (('ver_pre_reserva', 'Visualizar pré reserva'), ('ver_eventos_confirmados', 'Visualizar eventos confirmados'))},
        ),
    ]
