# Generated by Django 4.0.1 on 2024-03-24 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pre_orcamento.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ceu', '0028_tipoatividadesceu_atividades_serie_and_more'),
        ('orcamento', '0070_alter_orcamentoopicional_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0165_tipoaividadeperaltas_atividadeseco_serie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('nome_colegio', models.CharField(max_length=255, verbose_name='Nome do colégio')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome do responsável')),
                ('telefone_responsavel', models.CharField(max_length=255, verbose_name='Telefone do responsável')),
            ],
        ),
        migrations.CreateModel(
            name='PreOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_viagem', models.CharField(choices=[('', ''), ('lazer', 'Lazer'), ('estudo', 'Estudo')], default='', max_length=6, verbose_name='Tipo de viagem')),
                ('validade', models.DateField(default=pre_orcamento.models.default_validade)),
                ('atividades_ceu_aceitas', models.ManyToManyField(blank=True, related_name='atividades_ceu_aceitas', to='ceu.Atividades', verbose_name='Atividades CEU aceitas')),
                ('atividades_ceu_sugeridas', models.ManyToManyField(blank=True, related_name='atividades_ceu_sugeridas', to='ceu.Atividades', verbose_name='Atividades CEU sugeridas')),
                ('atividades_peraltas_aceitas', models.ManyToManyField(blank=True, related_name='atividades_peraltas_aceitas', to='peraltas.AtividadesEco', verbose_name='Atividades Peraltas aceitas')),
                ('atividades_peraltas_sugeridas', models.ManyToManyField(blank=True, related_name='atividades_peraltas_sugeridas', to='peraltas.AtividadesEco', verbose_name='Atividades Peraltas sugeridas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_orcamento.precadastro', verbose_name='Cliente')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('serie_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.perfilsparticipantes', verbose_name='Série do grupo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.statusorcamento', verbose_name='Status')),
                ('tipo_pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtosperaltas', verbose_name='Tipo de pacote')),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
