# Generated by Django 4.0.1 on 2024-03-28 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pre_orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorcamento',
            name='data_preenchimento',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Data de preenchimento'),
        ),
    ]
