# Generated by Django 4.0.1 on 2024-04-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_orcamento', '0002_preorcamento_data_preenchimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastro',
            name='nome_colegio',
            field=models.CharField(max_length=255, verbose_name='Nome do grupo'),
        ),
    ]
