# Generated by Django 4.0.1 on 2024-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0167_rename_tipoaividadeperaltas_tipoatividadeperaltas'),
        ('pre_orcamento', '0003_alter_precadastro_nome_colegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorcamento',
            name='serie_grupo',
        ),
        migrations.AddField(
            model_name='preorcamento',
            name='serie_grupo',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.PerfilsParticipantes', verbose_name='Série do grupo'),
        ),
    ]
