# Generated by Django 4.0.1 on 2024-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0167_rename_tipoaividadeperaltas_tipoatividadeperaltas'),
        ('pre_orcamento', '0004_remove_preorcamento_serie_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorcamento',
            name='serie_grupo',
            field=models.ManyToManyField(blank=True, to='peraltas.PerfilsParticipantes', verbose_name='Série do grupo'),
        ),
    ]
