# Generated by Django 4.0.1 on 2024-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0167_rename_tipoaividadeperaltas_tipoatividadeperaltas'),
        ('pre_orcamento', '0005_alter_preorcamento_serie_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorcamento',
            name='tipo_pacote',
        ),
        migrations.AddField(
            model_name='preorcamento',
            name='tipo_pacote',
            field=models.ManyToManyField(blank=True, to='peraltas.ProdutosPeraltas', verbose_name='Tipo de pacote'),
        ),
    ]
