# Generated by Django 4.0.1 on 2024-05-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0172_alter_atividadeseco_disciplinas'),
        ('pre_orcamento', '0006_remove_preorcamento_tipo_pacote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorcamento',
            name='tipo_viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.intencaoatividade', verbose_name='Tipo de viagem'),
        ),
    ]
