# Generated by Django 4.0.1 on 2024-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0172_alter_atividadeseco_disciplinas'),
        ('pre_orcamento', '0007_alter_preorcamento_tipo_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorcamento',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='peraltas.Disciplinas', verbose_name='Disciplinas'),
        ),
    ]
