# Generated by Django 4.0.1 on 2022-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locaveis',
            name='localvel',
            field=models.BooleanField(default=False),
        ),
    ]
