# Generated by Django 4.0.1 on 2022-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0002_professores_n_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='n_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atividades',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
    ]
