# Generated by Django 4.0.1 on 2022-03-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0002_locaveis_localvel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locaveis',
            old_name='localvel',
            new_name='locavel',
        ),
    ]
