# Generated by Django 4.0.1 on 2022-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0003_rename_localvel_locaveis_locavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='locaveis',
            name='lotacao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
