# Generated by Django 4.0.1 on 2022-03-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0004_locaveis_lotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estruturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrutura', models.CharField(max_length=100)),
                ('locavel', models.BooleanField(default=False)),
                ('lotacao', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='locaveis',
            name='estrutura',
        ),
        migrations.RemoveField(
            model_name='locaveis',
            name='locavel',
        ),
        migrations.RemoveField(
            model_name='locaveis',
            name='lotacao',
        ),
        migrations.AddField(
            model_name='locaveis',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ceu.estruturas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividades',
            name='local_da_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='local', to='ceu.estruturas'),
        ),
    ]
