# Generated by Django 4.0.1 on 2022-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0004_valores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valores',
            old_name='valor_atividade',
            new_name='valor_pago',
        ),
        migrations.RemoveField(
            model_name='valores',
            name='valor_diaria',
        ),
        migrations.AddField(
            model_name='valores',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
