# Generated by Django 4.0.1 on 2022-03-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0005_estruturas_remove_locaveis_estrutura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locaveis',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceu.estruturas', unique=True),
        ),
    ]
