# Generated by Django 4.0.1 on 2022-03-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0006_alter_locaveis_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locaveis',
            name='local',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ceu.estruturas'),
        ),
    ]
