# Generated by Django 4.0.1 on 2022-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0007_reembolsosprofessores_valores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolsosprofessores',
            name='mes_referente',
            field=models.IntegerField(choices=[(1, 'janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novemmbro'), (12, 'Dezembro')]),
        ),
    ]
