# Generated by Django 4.0.1 on 2022-04-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0016_alter_reembolsosprofessores_comprovante_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolsosprofessores',
            name='comprovante_reembolso',
            field=models.FileField(upload_to='comprovantes/<function ReembolsosProfessores.nome_completo at 0x00000208B8381240>/%Y/%m'),
        ),
    ]
