# Generated by Django 4.0.1 on 2022-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0021_alter_reembolsosprofessores_comprovante_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='atividade',
            field=models.CharField(max_length=100, verbose_name='Nome da atividade'),
        ),
    ]
