# Generated by Django 4.0.1 on 2022-08-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0022_alter_atividades_atividade'),
        ('ceu', '0023_alter_atividades_limitacao'),
    ]

    operations = [
    ]
