# Generated by Django 4.0.1 on 2022-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0044_alter_disponibilidadeacampamento_mes_and_more'),
        ('ceu', '0023_alter_atividades_limitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorDeBombas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True)),
                ('data_final', models.DateField(blank=True)),
                ('dados_atividades', models.JSONField()),
                ('mostrar', models.BooleanField(default=False)),
                ('grupos', models.ManyToManyField(to='peraltas.ClienteColegio')),
            ],
        ),
    ]
