# Generated by Django 4.0.1 on 2022-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0002_ordemdeservico_ficha_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='evento_terminado',
            field=models.BooleanField(default=False),
        ),
    ]
