# Generated by Django 4.0.1 on 2022-05-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0003_ordemdeservico_evento_terminado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='evento_terminado',
            new_name='escala',
        ),
    ]
