# Generated by Django 4.0.1 on 2022-08-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0004_rename_evento_terminado_ordemdeservico_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='escala_ceu',
            field=models.BooleanField(default=False),
        ),
    ]
