# Generated by Django 4.0.1 on 2022-11-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0069_alter_disponibilidadeacampamento_mes_and_more'),
        ('ordemDeServico', '0005_ordemdeservico_escala_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='monitor_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor_embarque', to='peraltas.monitor'),
        ),
    ]
