# Generated by Django 4.0.1 on 2022-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0006_ordemdeservico_monitor_embarque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='atividades_eco',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='atividades_eco',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
