# Generated by Django 4.0.1 on 2022-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0007_remove_ordemdeservico_atividades_eco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='empresa',
            field=models.CharField(choices=[('Peraltas', 'Peraltas'), ('CEU', 'Fundação CEU'), ('Peraltas CEU', 'Peraltas + Fundação CEU')], max_length=15),
        ),
    ]
