# Generated by Django 4.0.1 on 2022-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0008_alter_ordemdeservico_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='nome_motorista',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
