# Generated by Django 4.0.1 on 2023-01-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0102_alter_fichadeevento_vendedora'),
        ('ordemDeServico', '0009_ordemdeservico_nome_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='telefone_motorista',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='ficha_de_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.fichadeevento'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
        ),
    ]
