# Generated by Django 4.0.1 on 2023-01-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0106_remove_informacoesadcionais_informacoes_transporte_and_more'),
        ('ordemDeServico', '0010_ordemdeservico_telefone_motorista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='dados_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.dadostransporte'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='lista_segurados',
            field=models.FileField(blank=True, upload_to='seguros/%Y/%m/%d'),
        ),
    ]
