# Generated by Django 4.0.1 on 2023-01-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0106_remove_informacoesadcionais_informacoes_transporte_and_more'),
        ('ordemDeServico', '0011_ordemdeservico_dados_transporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='nome_motorista',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='telefone_motorista',
        ),
        migrations.CreateModel(
            name='DadosTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_embarque', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_embarque', models.TimeField(blank=True, null=True)),
                ('nome_motorista', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_motorista', models.CharField(blank=True, max_length=15, null=True)),
                ('dados_veiculos', models.JSONField(blank=True, null=True)),
                ('empresa_onibus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peraltas.empresaonibus')),
            ],
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dados_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordemDeServico.dadostransporte'),
        ),
    ]
