# Generated by Django 4.0.1 on 2023-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0012_remove_ordemdeservico_nome_motorista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostransporte',
            name='telefone_motorista',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
