# Generated by Django 4.0.1 on 2023-04-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0131_remove_fichadeevento_outro_produto_and_more'),
        ('ordemDeServico', '0014_remove_capos_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='monitor_responsavel',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='monitor_responsavel',
            field=models.ManyToManyField(to='peraltas.Monitor'),
        ),
    ]
