# Generated by Django 4.0.1 on 2023-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0015_remove_ordemdeservico_monitor_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='permicao_coordenadores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='racional_coordenadores',
            field=models.IntegerField(default=120),
        ),
    ]
