# Generated by Django 4.0.1 on 2023-04-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordemDeServico', '0016_ordemdeservico_permicao_coordenadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='racional_coordenadores',
            field=models.IntegerField(blank=True, default=120),
        ),
    ]
