# Generated by Django 4.0.1 on 2023-04-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0133_enfermeira_valor_diaria_enfermeira_valor_pernoite_and_more'),
        ('ordemDeServico', '0017_alter_ordemdeservico_racional_coordenadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadostransporte',
            name='monitor_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.monitor'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='dados_transporte_temp',
            field=models.ManyToManyField(related_name='Dados_transporte_temp', to='ordemDeServico.DadosTransporte'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dados_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordemDeServico.dadostransporte'),
        ),
    ]
