# Generated by Django 4.0.1 on 2023-04-21 03:27

from django.db import migrations, models
import django.db.models.deletion

from ordemDeServico.models import OrdemDeServico, DadosTransporte


def popular_dados_transporte_e_monitor_embarque(apps, schema_editor):
    OrdemDeServico = apps.get_model('ordemDeServico', 'OrdemDeServico')
    DadosTransporte = apps.get_model('ordemDeServico', 'DadosTransporte')
    Monitor = apps.get_model('peraltas', 'Monitor')

    for ordem in OrdemDeServico.objects.all():
        if ordem.dados_transporte and ordem.monitor_embarque:
            transporte = DadosTransporte.objects.get(id=ordem.dados_transporte.id)
            transporte.monitor_embarque = Monitor.objects.get(id=ordem.monitor_embarque.id)
            transporte.save()
            ordem.dados_transporte_temp.set([ordem.dados_transporte.id])


class Migration(migrations.Migration):
    dependencies = [
        ('peraltas', '0133_enfermeira_valor_diaria_enfermeira_valor_pernoite_and_more'),
        ('ordemDeServico', '0017_alter_ordemdeservico_racional_coordenadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadostransporte',
            name='monitor_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='peraltas.monitor'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='dados_transporte_temp',
            field=models.ManyToManyField(related_name='Dados_transporte_temp', to='ordemDeServico.DadosTransporte'),
        ),
        migrations.RunPython(popular_dados_transporte_e_monitor_embarque),
    ]
