# Generated by Django 4.0.1 on 2023-04-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0019_auto_20230421_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='dados_transporte',
        ),
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='dados_transporte_temp',
            new_name='dados_transporte'
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='monitor_embarque',
        ),
    ]
