# Generated by Django 4.0.1 on 2023-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0020_remove_ordemdeservico_dados_transporte_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dados_transporte',
            field=models.ManyToManyField(blank=True, to='ordemDeServico.DadosTransporte'),
        ),
    ]
