# Generated by Django 4.0.1 on 2023-04-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0021_ordemdeservico_dados_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='ficha_de_avaliacao',
            field=models.FileField(blank=True, null=True, upload_to='avaliacoes/%Y/%m/%d'),
        ),
    ]
