# Generated by Django 4.0.1 on 2023-05-14 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0022_ordemdeservico_ficha_de_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='data_preenchimento',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
