# Generated by Django 4.0.1 on 2023-10-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0023_ordemdeservico_data_preenchimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(max_length=255, verbose_name='Tipo de veículo')),
            ],
        ),
    ]
