# Generated by Django 4.0.1 on 2023-10-21 00:43

from django.db import migrations


def revisar_carros(apps, schema_editor):
    DadosTransporte = apps.get_model('ordemDeServico', 'DadosTransporte')
    veiculos = apps.get_model('ordemDeServico', 'TipoVeiculo')

    for veiculo in DadosTransporte.objects.all():
        antigo = veiculo.dados_veiculos

        if not isinstance(antigo, list) and not 'veiculo' in antigo.keys():
            try:
                novo = [
                    {'veiculo': veiculos.objects.get(tipo_veiculo__icontains='micro').id if antigo['micro_onibus'] != 0 else '', 'n': antigo['micro_onibus'] if antigo['micro_onibus'] != 0 else ''},
                    {'veiculo': veiculos.objects.get(tipo_veiculo__icontains='46').id if antigo['onibus_46'] != 0 else '', 'n': antigo['onibus_46'] if antigo['onibus_46'] != 0 else ''},
                    {'veiculo': veiculos.objects.get(tipo_veiculo__icontains='50').id if antigo['onibus_50'] != 0 else '', 'n': antigo['onibus_50'] if antigo['onibus_50'] != 0 else ''}
                ]
            except Exception as e:
                ...
            else:
                veiculo.dados_veiculos = novo
                veiculo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0024_tipoveiculo'),
    ]

    operations = [
        migrations.RunPython(revisar_carros)
    ]
