# Generated by Django 4.0.1 on 2024-08-28 14:08

from django.db import migrations, models
import django.db.models.deletion
import ordemDeServico.models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0176_alter_eventos_colaborador_and_more'),
        ('ordemDeServico', '0025_auto_20231020_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ForeignKey(default=ordemDeServico.models.atribuir_diretoria_vendedor, on_delete=django.db.models.deletion.SET_DEFAULT, to='peraltas.vendedor'),
        ),
    ]
