# Generated by Django 4.0.1 on 2024-08-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0178_alter_responsavel_responsavel_atualizacao_and_more'),
        ('ordemDeServico', '0026_alter_ordemdeservico_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostransporte',
            name='monitor_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peraltas.monitor'),
        ),
    ]
