# Generated by Django 4.0.1 on 2025-01-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0027_alter_dadostransporte_monitor_embarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='observacoes_ficha_de_evento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
