# Generated by Django 4.0.1 on 2025-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0191_produtocorporativo_brotas_eco'),
        ('ordemDeServico', '0028_ordemdeservico_observacoes_ficha_de_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='avaliou_monitoria',
            field=models.ManyToManyField(blank=True, editable=False, related_name='avaliou_monitoria', to='peraltas.Monitor'),
        ),
    ]
