# Generated by Django 4.0.1 on 2025-05-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0029_ordemdeservico_avaliou_monitoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='cliente_monitoria',
            field=models.BooleanField(default=False),
        ),
    ]
