# Generated by Django 4.0.1 on 2025-05-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0030_ordemdeservico_cliente_monitoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='cliente_monitoria',
            new_name='cliente_avaliou',
        ),
    ]
