# Generated by Django 4.0.1 on 2025-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0031_rename_cliente_monitoria_ordemdeservico_cliente_avaliou'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='motivo_nao_responder_ceu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='nao_respondeu_avaliacao_ceu',
            field=models.BooleanField(default=False),
        ),
    ]
