# Generated by Django 4.0.1 on 2022-03-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0002_vendedor'),
        ('ordemDeServico', '0002_ordemdeservico_delete_ordemdeservicoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
            preserve_default=False,
        ),
    ]
