# Generated by Django 4.0.1 on 2022-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0003_ordemdeservico_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='cidade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
