# Generated by Django 4.0.1 on 2022-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0004_ordemdeservico_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='empresa',
            field=models.CharField(choices=[('Peraltas', 'Peraltas'), ('Fundação CEU', 'Fundação CEU')], default='Peraltas', max_length=15),
            preserve_default=False,
        ),
    ]
