# Generated by Django 4.0.1 on 2022-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0006_ordemdeservico_loacao_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='relatorio_ceu_entregue',
            field=models.BooleanField(default=False),
        ),
    ]
