# Generated by Django 4.0.1 on 2022-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0003_clientecolegio_produtosperaltas'),
        ('ordemDeServico', '0007_ordemdeservico_relatorio_ceu_entregue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ManyToManyField(to='peraltas.Vendedor'),
        ),
    ]
