# Generated by Django 4.0.1 on 2022-03-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0003_clientecolegio_produtosperaltas'),
        ('ordemDeServico', '0008_remove_ordemdeservico_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
            preserve_default=False,
        ),
    ]
