# Generated by Django 4.0.1 on 2022-03-17 19:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0009_remove_ordemdeservico_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='tipo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Colégio', 'Colégio'), ('Empresa', 'Empresa')], max_length=7),
        ),
    ]
