# Generated by Django 4.0.1 on 2022-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0010_alter_ordemdeservico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='tipo',
            field=models.CharField(choices=[('Colégio', 'Colégio'), ('Empresa', 'Empresa')], max_length=7),
        ),
    ]
