# Generated by Django 4.0.1 on 2022-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0011_alter_ordemdeservico_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='empresa',
            field=models.CharField(choices=[('Peraltas', 'Peraltas'), ('CEU', 'Fundação CEU')], max_length=15),
        ),
    ]
