# Generated by Django 4.0.1 on 2022-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemDeServico', '0012_remove_ordemdeservico_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='tipo',
            field=models.CharField(choices=[('Colégio', 'Colégio'), ('Empresa', 'Empresa')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
