# Generated by Django 4.0.1 on 2022-03-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0034_informacoesadcionais_locacoes_ceu'),
        ('ordemDeServico', '0013_ordemdeservico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='atividades_eco',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.AtividadesEco'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='atividades_peraltas',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.AtividadePeraltas'),
        ),
    ]
