# Generated by Django 4.0.1 on 2022-04-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0050_remove_clientecolegio_responsavel_evento_and_more'),
        ('ordemDeServico', '0016_rename_loacao_ceu_ordemdeservico_locacao_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='ficha_de_evento',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.fichadeevento'),
            preserve_default=False,
        ),
    ]
