# Generated by Django 4.0.1 on 2022-04-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0052_remove_monitor_nome_remove_vendedor_nome_vendedor_and_more'),
        ('ordemDeServico', '0017_ordemdeservico_ficha_de_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
        ),
    ]
