# Generated by Django 4.0.1 on 2022-04-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0052_remove_monitor_nome_remove_vendedor_nome_vendedor_and_more'),
        ('ordemDeServico', '0018_alter_ordemdeservico_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='vendedor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
            preserve_default=False,
        ),
    ]
