# Generated by Django 4.0.1 on 2024-11-13 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peraltas', '0189_alter_eventos_cnpj_alter_eventos_email_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_adulto', models.PositiveIntegerField(default=0)),
                ('pax_crianca', models.PositiveIntegerField(default=0)),
                ('pax_monitoria', models.PositiveIntegerField(default=0)),
                ('total_pax', models.PositiveIntegerField(default=0, editable=False)),
                ('dados_cafe_da_manha', models.JSONField(blank=True, null=True)),
                ('dados_lanche_da_manha', models.JSONField(blank=True, null=True)),
                ('dados_almoco', models.JSONField(blank=True, null=True)),
                ('dados_lanche_da_tarde', models.JSONField(blank=True, null=True)),
                ('dados_jantar', models.JSONField(blank=True, null=True)),
                ('dados_lanche_da_noite', models.JSONField(blank=True, null=True)),
                ('ficha_de_evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peraltas.fichadeevento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peraltas.produtosperaltas')),
            ],
        ),
        migrations.CreateModel(
            name='Cozinheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
