# Generated by Django 4.0.1 on 2024-11-16 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0189_alter_eventos_cnpj_alter_eventos_email_responsavel_and_more'),
        ('cozinha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('total_pax_adulto', models.PositiveIntegerField(default=0)),
                ('total_pax_crianca', models.PositiveIntegerField(default=0)),
                ('total_pax_monitoria', models.PositiveIntegerField(default=0)),
                ('total_geral_pax', models.PositiveIntegerField(default=0, editable=False)),
                ('dados_cafe_da_manha', models.JSONField(blank=True, null=True)),
                ('dados_lanche_da_manha', models.JSONField(blank=True, null=True)),
                ('dados_almoco', models.JSONField(blank=True, null=True)),
                ('dados_lanche_da_tarde', models.JSONField(blank=True, null=True)),
                ('dados_jantar', models.JSONField(blank=True, null=True)),
                ('dados_lanche_da_noite', models.JSONField(blank=True, null=True)),
                ('fichas_de_evento', models.ManyToManyField(to='peraltas.FichaDeEvento')),
                ('grupos', models.ManyToManyField(to='peraltas.ClienteColegio')),
            ],
        ),
    ]
