# Generated by Django 4.0.1 on 2024-11-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0002_relatoriodia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodia',
            name='total_geral_pax',
        ),
        migrations.RemoveField(
            model_name='relatoriodia',
            name='total_pax_adulto',
        ),
        migrations.RemoveField(
            model_name='relatoriodia',
            name='total_pax_crianca',
        ),
        migrations.RemoveField(
            model_name='relatoriodia',
            name='total_pax_monitoria',
        ),
    ]
