# Generated by Django 4.0.1 on 2024-11-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0003_remove_relatoriodia_total_geral_pax_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriodia',
            options={'permissions': (('ver_descritivo_refeicoes', 'Ver descritivo as refeições'),)},
        ),
    ]
