# Generated by Django 4.0.1 on 2024-12-02 18:47
from datetime import datetime

from django.db import migrations, models, IntegrityError


def cadastrar_refeicoes(apps, schema_editor):
    horas_padrao = {
        'cafe_manha': {
            'inicio': '07:30',
            'final': '09:30',
        },
        'lanche_manha': {
            'inicio': '10:00',
            'final': '11:00',
        },
        'almoco': {
            'inicio': '12:00',
            'final': '14:30',
        },
        'lanche_tarde': {
            'inicio': '15:00',
            'final': '16:00',
        },
        'jantar': {
            'inicio': '18:45',
            'final': '20:30',
        },
        'lanche_noite': {
            'inicio': '22:00',
            'final': '23:30',
        },
    }
    HorarioRefeicoes = apps.get_model('cozinha', 'HorarioRefeicoes')
    refeicoes_padrao = dict(HorarioRefeicoes._meta.get_field('refeicao').choices)

    for refeicao, _ in refeicoes_padrao.items():
        try:
            HorarioRefeicoes.objects.create(
                refeicao=refeicao,
                hora_inicio=datetime.strptime(horas_padrao[refeicao]['inicio'], '%H:%M'),
                hora_final=datetime.strptime(horas_padrao[refeicao]['final'], '%H:%M'),
            )
        except IntegrityError:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('cozinha', '0004_alter_relatoriodia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioRefeicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(
                    choices=[('cafe_manha', 'Café da manhã'), ('lanche_manha', 'Lanche da manhã'), ('almoco', 'Almoço'),
                             ('lanche_tarde', 'Lanche da tarde'), ('jantar', 'Jantar'),
                             ('lanche_noite', 'Lanche da noite')], max_length=100, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
            ],
        ),
        migrations.RunPython(cadastrar_refeicoes)
    ]
