# Generated by Django 4.0.1 on 2024-12-03 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cozinha', '0005_horariorefeicoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVisualizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_refeicoes', models.DateField()),
                ('data_hora_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='relatoriodia',
            name='fichas_de_evento',
        ),
        migrations.RemoveField(
            model_name='relatoriodia',
            name='grupos',
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
        migrations.DeleteModel(
            name='RelatorioDia',
        ),
    ]
