# Generated by Django 4.0.1 on 2024-12-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0006_registrovisualizacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovisualizacoes',
            options={'verbose_name_plural': 'Registro de visualizações'},
        ),
    ]
