# Generated by Django 4.0.1 on 2025-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0008_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariorefeicoes',
            name='hospedagem',
            field=models.BooleanField(default=False),
        ),
    ]
