# Generated by Django 4.0.1 on 2022-04-21 22:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePeraltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadesEco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('codigo_app_pj', models.CharField(max_length=10)),
                ('codigo_app_pf', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=600)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CodigosApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_pj', models.CharField(blank=True, max_length=20)),
                ('cliente_pf', models.CharField(blank=True, max_length=20)),
                ('evento', models.CharField(blank=True, max_length=20)),
                ('reserva', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesAdcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.BooleanField()),
                ('terceirizado', models.BooleanField()),
                ('endereco_embarque', models.CharField(blank=True, max_length=255)),
                ('etiquetas_embarque', models.BooleanField()),
                ('servico_bordo', models.IntegerField(blank=True, choices=[(1, 'Padrão'), (2, 'Diferenciado')], null=True)),
                ('monitoria', models.IntegerField(blank=True, choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20'), (3, 'Monitoria completa (em quarto - 1/10)')], null=True)),
                ('biologo', models.BooleanField()),
                ('quais_atividades', models.CharField(blank=True, max_length=255)),
                ('seguro', models.BooleanField()),
                ('exclusividade', models.BooleanField()),
                ('fotos_site', models.BooleanField()),
                ('abada', models.BooleanField()),
                ('camiseta', models.BooleanField()),
                ('festas', models.BooleanField()),
                ('enfermaria', models.IntegerField(blank=True, choices=[(1, 'Padrão'), (2, 'Garantia')], null=True)),
                ('horario_garantia', models.TimeField(blank=True, null=True)),
                ('roupa_de_cama', models.BooleanField()),
                ('camera_on_line', models.BooleanField()),
                ('cd_para_aluno', models.BooleanField()),
                ('bate_bate', models.BooleanField()),
                ('fogueira', models.BooleanField()),
                ('outros', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilsParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=255)),
                ('ano', models.CharField(blank=True, max_length=255)),
                ('idade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosPeraltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('pernoite', models.BooleanField(default=True)),
                ('colegio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fone', models.CharField(max_length=16)),
                ('email_responsavel_evento', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('nota', models.FloatField(default=0.0)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoClienteResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio')),
                ('responsavel', models.ManyToManyField(to='peraltas.Responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('nota', models.FloatField(default=0.0)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaDeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outro_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('professores_com_alunos', models.BooleanField()),
                ('qtd_professores', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_profs_homens', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_profs_mulheres', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_convidada', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_confirmada', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_meninos', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_meninas', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_homens', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_mulheres', models.PositiveIntegerField(blank=True, null=True)),
                ('refeicoes', models.JSONField(blank=True, null=True)),
                ('observacoes_refeicoes', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('data_preenchimento', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('os', models.BooleanField(default=False)),
                ('atividades_ceu', models.ManyToManyField(blank=True, to='ceu.Atividades')),
                ('atividades_eco', models.ManyToManyField(blank=True, to='peraltas.AtividadesEco')),
                ('atividades_peraltas', models.ManyToManyField(blank=True, to='peraltas.AtividadePeraltas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio')),
                ('codigos_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.codigosapp')),
                ('informacoes_adcionais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.informacoesadcionais')),
                ('locacoes_ceu', models.ManyToManyField(blank=True, to='ceu.Locaveis')),
                ('perfil_participantes', models.ManyToManyField(blank=True, to='peraltas.PerfilsParticipantes')),
                ('produto', models.ManyToManyField(to='peraltas.ProdutosPeraltas')),
                ('responsavel_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.responsavel')),
                ('vendedora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor')),
            ],
        ),
    ]
