# Generated by Django 4.0.1 on 2022-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0002_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=600)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosPeraltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
            ],
        ),
    ]
