# Generated by Django 4.0.1 on 2022-03-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0004_locaveis_lotacao'),
        ('peraltas', '0003_clientecolegio_produtosperaltas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesEco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CodigosApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_pj', models.CharField(max_length=20)),
                ('cliente_pf', models.CharField(max_length=20)),
                ('evento', models.CharField(max_length=20)),
                ('reserva', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilsParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=255)),
                ('idade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResumoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('forma_pagamento', models.CharField(max_length=255)),
                ('vencimentos', models.CharField(max_length=255)),
                ('contrato', models.IntegerField(choices=[(1, 'Grupo'), (2, 'Individual')])),
                ('nota_fiscal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesAdcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.BooleanField()),
                ('endereco_embarque', models.CharField(max_length=255)),
                ('etiquetas_embarque', models.BooleanField()),
                ('servico_bordo', models.IntegerField(choices=[(1, 'Padrão'), (2, 'Diferenciado')])),
                ('monitoria', models.IntegerField(choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20'), (3, 'Monitoria completa (em quarto - 1/10)')])),
                ('biologo', models.BooleanField()),
                ('quais_atividades', models.CharField(blank=True, max_length=255)),
                ('seguro', models.BooleanField()),
                ('exclusividade', models.BooleanField()),
                ('fotos_site', models.BooleanField()),
                ('abada', models.BooleanField()),
                ('camiseta', models.BooleanField()),
                ('enfermaria', models.IntegerField()),
                ('horario_garantia', models.TimeField(blank=True, null=True)),
                ('roupa_de_cama', models.BooleanField()),
                ('camera_on_line', models.BooleanField()),
                ('cd_para_aluno', models.BooleanField()),
                ('bate_bate', models.BooleanField()),
                ('fogueira', models.BooleanField()),
                ('outros', models.CharField(blank=True, max_length=300)),
                ('atividades_ceu', models.ManyToManyField(to='ceu.Atividades')),
                ('atividades_eco', models.ManyToManyField(to='peraltas.AtividadesEco')),
            ],
        ),
        migrations.CreateModel(
            name='FichaDeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_evento', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fone', models.CharField(max_length=9)),
                ('email_responsavel_evento', models.EmailField(max_length=254)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('professores_com_alunos', models.BooleanField()),
                ('qtd_convidada', models.PositiveIntegerField()),
                ('qtd_confirmada', models.PositiveIntegerField(blank=True, null=True)),
                ('refeicoes', models.JSONField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('informacoes_adcionais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.informacoesadcionais')),
                ('perfil_participantes', models.ManyToManyField(to='peraltas.PerfilsParticipantes')),
                ('produto', models.ManyToManyField(to='peraltas.ProdutosPeraltas')),
                ('resumo_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.resumofinanceiro')),
                ('vendedora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor')),
            ],
        ),
    ]
