# Generated by Django 4.0.1 on 2022-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0004_atividadeseco_codigosapp_perfilsparticipantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePeraltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
