# Generated by Django 4.0.1 on 2022-03-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0005_atividadeperaltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio'),
            preserve_default=False,
        ),
    ]
