# Generated by Django 4.0.1 on 2022-03-18 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0006_fichadeevento_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='fichadeevento',
            name='email_responsavel_evento',
        ),
        migrations.RemoveField(
            model_name='fichadeevento',
            name='fone',
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fone', models.CharField(max_length=9)),
                ('email_responsavel_evento', models.EmailField(max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio')),
            ],
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='responsavel_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.responsavel'),
        ),
    ]
