# Generated by Django 4.0.1 on 2022-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0008_fichadeevento_ficha_financeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (3, 'Março'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (12, 'Dezembro'), (9, 'Setembro'), (2, 'Fevereiro'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (3, 'Março'), (8, 'Agosto'), (5, 'Maio'), (7, 'Julho'), (12, 'Dezembro'), (9, 'Setembro'), (2, 'Fevereiro'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril')]),
        ),
    ]
