# Generated by Django 4.0.1 on 2022-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0008_perfilsparticipantes_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilsparticipantes',
            name='ano',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
