# Generated by Django 4.0.1 on 2022-03-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0010_fichadeevento_codigos_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='outro_produto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='vendedora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.vendedor'),
        ),
    ]
