# Generated by Django 4.0.1 on 2022-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0010_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionaisFormatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcional_formatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionaisGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcional_geral', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='abada',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='bate_bate',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='camera_on_line',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='camiseta',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='cd_para_aluno',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='exclusividade',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='festas',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='fogueira',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='fotos_site',
        ),
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='roupa_de_cama',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (1, 'Janeiro'), (11, 'Novembro'), (5, 'Maio'), (10, 'Outubro'), (9, 'Setembro'), (6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (12, 'Dezembro'), (4, 'Abril'), (3, 'Março')]),
        ),
    ]
