# Generated by Django 4.0.1 on 2022-03-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0011_fichadeevento_outro_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='cliente',
        ),
        migrations.AddField(
            model_name='clientecolegio',
            name='responsavel_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.responsavel'),
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
