# Generated by Django 4.0.1 on 2022-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0011_fichadeevento_outro_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='cliente',
            new_name='responsavel_por',
        ),
        migrations.AddField(
            model_name='clientecolegio',
            name='responsavel_evento',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
