# Generated by Django 4.0.1 on 2022-05-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0011_opcionaisformatura_opcionaisgerais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLimiteAcampamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_limite_acampamento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaLimiteHotelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_limite_acampamento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalaAcampamneto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitores_acampamento', models.CharField(max_length=255)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalaHotelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitores_hotelaria', models.CharField(max_length=255)),
                ('data', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='opcionais_formatura',
            field=models.ManyToManyField(blank=True, to='peraltas.OpcionaisFormatura'),
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='opcionais_geral',
            field=models.ManyToManyField(blank=True, to='peraltas.OpcionaisGerais'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (4, 'Abril'), (2, 'Fevereiro'), (7, 'Julho'), (6, 'Junho'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(11, 'Novembro'), (10, 'Outubro'), (5, 'Maio'), (12, 'Dezembro'), (4, 'Abril'), (2, 'Fevereiro'), (7, 'Julho'), (6, 'Junho'), (1, 'Janeiro'), (8, 'Agosto'), (9, 'Setembro'), (3, 'Março')]),
        ),
    ]
