# Generated by Django 4.0.1 on 2022-05-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0012_dialimiteacampamento_dialimitehotelaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialimitehotelaria',
            old_name='dia_limite_acampamento',
            new_name='dia_limite_hotelaria',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (3, 'Março'), (11, 'Novembro'), (12, 'Dezembro'), (6, 'Junho'), (9, 'Setembro'), (7, 'Julho'), (4, 'Abril'), (10, 'Outubro'), (1, 'Janeiro'), (8, 'Agosto'), (5, 'Maio')]),
        ),
    ]
