# Generated by Django 4.0.1 on 2022-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0012_remove_responsavel_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecolegio',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
