# Generated by Django 4.0.1 on 2022-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0013_alter_clientecolegio_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='fone',
            field=models.CharField(max_length=11),
        ),
    ]
