# Generated by Django 4.0.1 on 2022-03-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0014_alter_responsavel_fone'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='responsavel_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='responsavel_evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
