# Generated by Django 4.0.1 on 2022-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0015_responsavel_responsavel_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='responsavel_por',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='responsavel_por',
            field=models.ManyToManyField(to='peraltas.ClienteColegio'),
        ),
    ]
