# Generated by Django 4.0.1 on 2022-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0016_remove_responsavel_responsavel_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='responsavel_por',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.ClienteColegio'),
        ),
    ]
