# Generated by Django 4.0.1 on 2022-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0016_rename_escalaacampamneto_escalaacampamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='escala',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (4, 'Abril'), (1, 'Janeiro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(9, 'Setembro'), (12, 'Dezembro'), (11, 'Novembro'), (6, 'Junho'), (10, 'Outubro'), (4, 'Abril'), (1, 'Janeiro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março'), (8, 'Agosto')]),
        ),
    ]
