# Generated by Django 4.0.1 on 2022-03-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0017_alter_responsavel_responsavel_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='responsavel_por',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='responsavel_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.clientecolegio'),
            preserve_default=False,
        ),
    ]
