# Generated by Django 4.0.1 on 2022-05-28 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0017_fichadeevento_escala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalaacampamento',
            name='data',
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='check_in_cliente',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='escalaacampamento',
            name='check_out_cliente',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (1, 'Janeiro'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (10, 'Outubro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (1, 'Janeiro'), (4, 'Abril'), (8, 'Agosto'), (6, 'Junho'), (10, 'Outubro'), (3, 'Março'), (9, 'Setembro'), (11, 'Novembro'), (12, 'Dezembro'), (7, 'Julho'), (5, 'Maio')]),
        ),
    ]
