# Generated by Django 4.0.1 on 2022-03-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0019_alter_informacoesadcionais_enfermaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='festas',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
