# Generated by Django 4.0.1 on 2022-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0020_informacoesadcionais_festas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_professores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
