# Generated by Django 4.0.1 on 2022-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0021_fichadeevento_qtd_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='atividades_eco',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.AtividadesEco'),
        ),
    ]
