# Generated by Django 4.0.1 on 2022-03-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0024_resumofinanceiro_observacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumofinanceiro',
            old_name='observacoes',
            new_name='observacoes_financeiras',
        ),
    ]
