# Generated by Django 4.0.1 on 2022-03-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0025_rename_observacoes_resumofinanceiro_observacoes_financeiras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosapp',
            name='cliente_pf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='cliente_pj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='evento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='codigosapp',
            name='reserva',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resumofinanceiro',
            name='vencimentos',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
