# Generated by Django 4.0.1 on 2022-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0025_prereserva_ficha_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='outros',
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (11, 'Novembro'), (12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(4, 'Abril'), (11, 'Novembro'), (12, 'Dezembro'), (2, 'Fevereiro'), (1, 'Janeiro'), (3, 'Março'), (9, 'Setembro'), (7, 'Julho'), (10, 'Outubro'), (8, 'Agosto'), (5, 'Maio'), (6, 'Junho')]),
        ),
    ]
