# Generated by Django 4.0.1 on 2022-03-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0004_locaveis_lotacao'),
        ('peraltas', '0026_alter_codigosapp_cliente_pf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='atividades_ceu',
            field=models.ManyToManyField(blank=True, to='ceu.Atividades'),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='endereco_embarque',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='monitoria',
            field=models.IntegerField(blank=True, choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20'), (3, 'Monitoria completa (em quarto - 1/10)')], null=True),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='servico_bordo',
            field=models.IntegerField(blank=True, choices=[(1, 'Padrão'), (2, 'Diferenciado')], null=True),
        ),
    ]
