# Generated by Django 4.0.1 on 2022-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0027_alter_informacoesadcionais_atividades_ceu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_convidada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
