# Generated by Django 4.0.1 on 2022-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0028_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (5, 'Maio'), (10, 'Outubro'), (11, 'Novembro'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto'), (7, 'Julho'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (1, 'Janeiro'), (2, 'Fevereiro'), (5, 'Maio'), (10, 'Outubro'), (11, 'Novembro'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto'), (7, 'Julho'), (6, 'Junho')]),
        ),
    ]
