# Generated by Django 4.0.1 on 2022-03-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0028_alter_fichadeevento_qtd_convidada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='codigos_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.codigosapp'),
        ),
    ]
