# Generated by Django 4.0.1 on 2022-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0029_alter_fichadeevento_codigos_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumofinanceiro',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
