# Generated by Django 4.0.1 on 2022-07-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0029_nivelmonitoria_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.nivelmonitoria'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (8, 'Agosto'), (7, 'Julho'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (2, 'Fevereiro'), (9, 'Setembro'), (10, 'Outubro'), (4, 'Abril'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (8, 'Agosto'), (7, 'Julho'), (12, 'Dezembro'), (5, 'Maio'), (1, 'Janeiro'), (2, 'Fevereiro'), (9, 'Setembro'), (10, 'Outubro'), (4, 'Abril'), (11, 'Novembro')]),
        ),
    ]
