# Generated by Django 4.0.1 on 2022-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0030_monitor_nivel_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesadcionais',
            name='terceirizado',
        ),
        migrations.AddField(
            model_name='informacoesadcionais',
            name='hora_embarque',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (1, 'Janeiro'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (1, 'Janeiro'), (10, 'Outubro'), (11, 'Novembro'), (6, 'Junho'), (4, 'Abril'), (8, 'Agosto'), (9, 'Setembro'), (7, 'Julho'), (5, 'Maio'), (2, 'Fevereiro'), (3, 'Março')]),
        ),
    ]
