# Generated by Django 4.0.1 on 2022-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0031_fichadeevento_data_preenchimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='os',
            field=models.BooleanField(default=False),
        ),
    ]
