# Generated by Django 4.0.1 on 2022-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0032_fichadeevento_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
