# Generated by Django 4.0.1 on 2022-07-20 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0032_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='atividadeperaltas',
            old_name='atividade',
            new_name='nome_atividade',
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='idade_max',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='idade_min',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='lista_materiais',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='local',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='manual_atividade',
            field=models.FileField(blank=True, upload_to='manuais_atividades/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='monitores_max',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='monitores_min',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='nivel_atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.nivelmonitoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='participantes_max',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='participantes_min',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (3, 'Março'), (6, 'Junho'), (4, 'Abril'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (9, 'Setembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (8, 'Agosto'), (12, 'Dezembro'), (3, 'Março'), (6, 'Junho'), (4, 'Abril'), (5, 'Maio'), (2, 'Fevereiro'), (10, 'Outubro'), (7, 'Julho'), (11, 'Novembro'), (9, 'Setembro')]),
        ),
        migrations.AddField(
            model_name='atividadeperaltas',
            name='tipo_atividade',
            field=models.ManyToManyField(to='peraltas.TipoAtividade'),
        ),
    ]
