# Generated by Django 4.0.1 on 2022-07-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0033_tipoatividade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadeseco',
            old_name='atividade',
            new_name='nome_atividade_eco',
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='biologo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='idade_max',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='idade_min',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='lista_materiais',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='local',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='manual_atividade',
            field=models.FileField(blank=True, upload_to='manuais_atividades/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='monitores_max',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='monitores_min',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='nivel_atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.nivelmonitoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='participantes_max',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='participantes_min',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeseco',
            name='tipo_atividade',
            field=models.ManyToManyField(to='peraltas.TipoAtividade'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (5, 'Maio'), (4, 'Abril'), (10, 'Outubro'), (7, 'Julho'), (2, 'Fevereiro'), (9, 'Setembro'), (1, 'Janeiro'), (8, 'Agosto')]),
        ),
    ]
