# Generated by Django 4.0.1 on 2022-03-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceu', '0005_estruturas_remove_locaveis_estrutura_and_more'),
        ('peraltas', '0033_fichadeevento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='locacoes_ceu',
            field=models.ManyToManyField(blank=True, to='ceu.Locaveis'),
        ),
    ]
