# Generated by Django 4.0.1 on 2022-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0034_informacoesadcionais_locacoes_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeperaltas',
            name='atividade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
