# Generated by Django 4.0.1 on 2022-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0035_atividadeperaltas_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumofinanceiro',
            name='valor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
