# Generated by Django 4.0.1 on 2022-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0036_alter_resumofinanceiro_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumofinanceiro',
            name='valor_por_participantes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
