# Generated by Django 4.0.1 on 2022-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0037_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='material_apoio',
            field=models.FileField(blank=True, null=True, upload_to='materiais_apoio/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (6, 'Junho'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (9, 'Setembro'), (4, 'Abril'), (3, 'Março'), (8, 'Agosto'), (12, 'Dezembro'), (1, 'Janeiro'), (5, 'Maio'), (11, 'Novembro'), (6, 'Junho'), (2, 'Fevereiro'), (10, 'Outubro')]),
        ),
    ]
