# Generated by Django 4.0.1 on 2022-03-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0037_alter_resumofinanceiro_valor_por_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='responsavel_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.clientecolegio'),
        ),
    ]
