# Generated by Django 4.0.1 on 2022-08-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0038_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (2, 'Fevereiro'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (7, 'Julho'), (8, 'Agosto'), (10, 'Outubro'), (1, 'Janeiro'), (5, 'Maio'), (9, 'Setembro'), (2, 'Fevereiro'), (4, 'Abril'), (12, 'Dezembro'), (6, 'Junho'), (11, 'Novembro')]),
        ),
    ]
