# Generated by Django 4.0.1 on 2022-08-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0038_fichadeevento_material_apoio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (8, 'Agosto'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril'), (3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (9, 'Setembro'), (5, 'Maio'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(2, 'Fevereiro'), (8, 'Agosto'), (7, 'Julho'), (10, 'Outubro'), (4, 'Abril'), (3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (9, 'Setembro'), (5, 'Maio'), (1, 'Janeiro'), (11, 'Novembro')]),
        ),
    ]
