# Generated by Django 4.0.1 on 2022-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0038_alter_fichadeevento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecolegio',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='fone',
            field=models.CharField(max_length=16),
        ),
    ]
