# Generated by Django 4.0.1 on 2022-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0039_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeperaltas',
            name='nivel_atividade',
        ),
        migrations.RemoveField(
            model_name='atividadeperaltas',
            name='tipo_atividade',
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='lista_materiais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lista de materiais'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='manual_atividade',
            field=models.FileField(blank=True, null=True, upload_to='manuais_atividades_acampamento/%Y/%m/%d', verbose_name='Manual'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='participantes_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo de participantes'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='participantes_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número mínimo de participantes'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro'), (9, 'Setembro'), (7, 'Julho'), (1, 'Janeiro'), (3, 'Março'), (11, 'Novembro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(12, 'Dezembro'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (2, 'Fevereiro'), (8, 'Agosto'), (10, 'Outubro'), (9, 'Setembro'), (7, 'Julho'), (1, 'Janeiro'), (3, 'Março'), (11, 'Novembro')]),
        ),
    ]
