# Generated by Django 4.0.1 on 2022-03-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0039_alter_clientecolegio_cnpj_alter_responsavel_fone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='responsavel_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peraltas.responsavel'),
        ),
    ]
