# Generated by Django 4.0.1 on 2022-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0039_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (7, 'Julho'), (6, 'Junho'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (12, 'Dezembro'), (4, 'Abril'), (8, 'Agosto')]),
        ),
    ]
