# Generated by Django 4.0.1 on 2022-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0040_remove_atividadeperaltas_nivel_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prereserva',
            name='vt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (9, 'Setembro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (1, 'Janeiro'), (9, 'Setembro'), (11, 'Novembro'), (3, 'Março'), (5, 'Maio'), (12, 'Dezembro'), (7, 'Julho'), (8, 'Agosto'), (2, 'Fevereiro'), (6, 'Junho'), (4, 'Abril')]),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='monitoria',
            field=models.IntegerField(blank=True, choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20'), (3, 'Monitoria completa (em quarto - 1/12)')], null=True),
        ),
    ]
