# Generated by Django 4.0.1 on 2022-08-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0040_remove_atividadeperaltas_nivel_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='monitores_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeperaltas',
            name='monitores_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número mínimo de monitores'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (7, 'Julho'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (6, 'Junho'), (12, 'Dezembro'), (10, 'Outubro'), (5, 'Maio'), (1, 'Janeiro'), (7, 'Julho'), (2, 'Fevereiro'), (9, 'Setembro'), (11, 'Novembro'), (4, 'Abril'), (8, 'Agosto')]),
        ),
    ]
