# Generated by Django 4.0.1 on 2022-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0040_alter_fichadeevento_responsavel_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='observacoes_refeicoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientecolegio',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
