# Generated by Django 4.0.1 on 2022-08-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0041_alter_atividadeperaltas_monitores_max_and_more'),
        ('peraltas', '0041_prereserva_vt_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
    ]
