# Generated by Django 4.0.1 on 2022-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0041_fichadeevento_observacoes_refeicoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_homens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_mulheres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_profs_homens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_profs_mulheres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichadeevento',
            name='qtd_professores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
