# Generated by Django 4.0.1 on 2022-08-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0042_merge_20220810_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeseco',
            name='nivel_atividade',
        ),
        migrations.RemoveField(
            model_name='atividadeseco',
            name='tipo_atividade',
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='lista_materiais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lista de materiais'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='monitores_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='monitores_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número mínimo de monitores'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='participantes_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo de participantes'),
        ),
        migrations.AlterField(
            model_name='atividadeseco',
            name='participantes_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número mínimo de participantes'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (12, 'Dezembro'), (5, 'Maio'), (6, 'Junho'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(3, 'Março'), (12, 'Dezembro'), (5, 'Maio'), (6, 'Junho'), (2, 'Fevereiro'), (11, 'Novembro'), (10, 'Outubro'), (4, 'Abril'), (8, 'Agosto'), (1, 'Janeiro'), (9, 'Setembro'), (7, 'Julho')]),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='monitoria',
            field=models.IntegerField(blank=True, choices=[(1, '1/2 monitoria (fora de quarto - 1/20)'), (2, '1/2 monitoria (dentro de quarto - 1/20)'), (3, 'Monitoria completa (em quarto - 1/12)')], null=True),
        ),
        migrations.AlterField(
            model_name='informacoesadcionais',
            name='tipo_veiculo',
            field=models.IntegerField(blank=True, choices=[(1, 'Micro ônibus'), (2, 'Ônibus 46 lugares'), (3, 'Ônibus 50 lugares')], null=True),
        ),
    ]
