# Generated by Django 4.0.1 on 2022-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0042_fichadeevento_qtd_homens_fichadeevento_qtd_mulheres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_meninas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='qtd_meninos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtosperaltas',
            name='pernoite',
            field=models.BooleanField(default=True),
        ),
    ]
