# Generated by Django 4.0.1 on 2022-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0043_remove_atividadeseco_nivel_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeseco',
            name='manual_atividade',
            field=models.FileField(blank=True, null=True, upload_to='manuais_atividades_eco/%Y/%m/%d', verbose_name='Manual'),
        ),
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (5, 'Maio'), (11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(10, 'Outubro'), (8, 'Agosto'), (2, 'Fevereiro'), (12, 'Dezembro'), (7, 'Julho'), (3, 'Março'), (4, 'Abril'), (9, 'Setembro'), (5, 'Maio'), (11, 'Novembro'), (1, 'Janeiro'), (6, 'Junho')]),
        ),
    ]
