# Generated by Django 4.0.1 on 2022-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0043_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (8, 'Agosto'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (11, 'Novembro'), (4, 'Abril'), (1, 'Janeiro'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(7, 'Julho'), (2, 'Fevereiro'), (8, 'Agosto'), (9, 'Setembro'), (12, 'Dezembro'), (5, 'Maio'), (11, 'Novembro'), (4, 'Abril'), (1, 'Janeiro'), (10, 'Outubro'), (3, 'Março'), (6, 'Junho')]),
        ),
    ]
