# Generated by Django 4.0.1 on 2022-04-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0044_produtosperaltas_colegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='produto',
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='peraltas.produtosperaltas'),
            preserve_default=False,
        ),
    ]
