# Generated by Django 4.0.1 on 2022-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0044_alter_atividadeseco_manual_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadeacampamento',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (4, 'Abril'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (10, 'Outubro')]),
        ),
        migrations.AlterField(
            model_name='disponibilidadehotelaria',
            name='mes',
            field=models.IntegerField(choices=[(6, 'Junho'), (1, 'Janeiro'), (8, 'Agosto'), (2, 'Fevereiro'), (4, 'Abril'), (7, 'Julho'), (5, 'Maio'), (12, 'Dezembro'), (3, 'Março'), (11, 'Novembro'), (9, 'Setembro'), (10, 'Outubro')]),
        ),
    ]
