# Generated by Django 4.0.1 on 2022-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0045_remove_fichadeevento_produto_fichadeevento_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='produto',
        ),
        migrations.AddField(
            model_name='fichadeevento',
            name='produto',
            field=models.ManyToManyField(to='peraltas.ProdutosPeraltas'),
        ),
    ]
