# Generated by Django 4.0.1 on 2022-04-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0046_remove_fichadeevento_produto_fichadeevento_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadeevento',
            name='resumo_financeiro',
        ),
        migrations.AddField(
            model_name='clientecolegio',
            name='codigo_app_pf',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientecolegio',
            name='codigo_app_pj',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResumoFinanceiro',
        ),
    ]
