# Generated by Django 4.0.1 on 2022-04-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0047_remove_fichadeevento_resumo_financeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesadcionais',
            name='terceirizado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
