# Generated by Django 4.0.1 on 2022-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0050_remove_clientecolegio_responsavel_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='perfil_participantes',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.PerfilsParticipantes'),
        ),
    ]
