# Generated by Django 4.0.1 on 2022-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0052_remove_monitor_nome_remove_vendedor_nome_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='perfil_participantes',
            field=models.ManyToManyField(blank=True, null=True, to='peraltas.PerfilsParticipantes'),
        ),
    ]
