# Generated by Django 4.0.1 on 2022-04-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraltas', '0055_alter_fichadeevento_perfil_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadeevento',
            name='perfil_participantes',
            field=models.ManyToManyField(blank=True, to='peraltas.PerfilsParticipantes'),
        ),
    ]
