# Generated by Django 4.0.1 on 2022-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peraltas', '0049_alter_disponibilidadeacampamento_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorDeBombas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True)),
                ('data_final', models.DateField(blank=True)),
                ('dados_atividades', models.JSONField()),
                ('grupos', models.ManyToManyField(to='peraltas.ClienteColegio')),
            ],
        ),
    ]
