# Generated by Django 4.0.1 on 2022-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectordebombas',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
