# Generated by Django 4.0.1 on 2023-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_detectordebombas_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectordebombas',
            name='setor',
            field=models.CharField(choices=[('', ''), ('CEU', 'CEU'), ('Peraltas', 'Peraltas')], default='CEU', max_length=8),
            preserve_default=False,
        ),
    ]
