# Generated by Django 4.0.1 on 2023-01-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_detectordebombas_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectordebombas',
            name='setor',
            field=models.CharField(choices=[('', ''), ('ceu', 'CEU'), ('peraltas', 'Peraltas')], max_length=8),
        ),
    ]
